///////////////////////////////////////////////////////////////////////////////
// kuka_interfaceServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_kuka_interface = 0x3F000000;
#define SRVNAME_KUKA_INTERFACE "kuka_interface"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_kuka_interfaceCkuka_module = {0xddb082d4,0xbfc6,0x4ac9,{0x84,0x2c,0x11,0xca,0x36,0x71,0xfa,0xb0}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_kuka_moduleAxisVelocityLimit = 0x0000000A;
const PTCID PID_kuka_moduleAxisMotorTorqueLimit = 0x0000000B;
const PTCID PID_kuka_moduleAxisMotorTorqueSaturation = 0x0000000D;
const PTCID PID_kuka_moduleAxisSensorTorqueLimit = 0x0000000C;
const PTCID PID_kuka_moduleAxisPositionSoftReserve = 0x0000000E;
const PTCID PID_kuka_moduleLinearAxisParameters = 0x00000025;
const PTCID PID_kuka_modulemass_tool = 0x0000001D;
const PTCID PID_kuka_modulecog_tool = 0x00000022;
const PTCID PID_kuka_moduletcp_tool = 0x0000001C;
const PTCID PID_kuka_moduleWorldTranslation = 0x00000010;
const PTCID PID_kuka_moduleWorldRotation = 0x0000000F;
const PTCID PID_kuka_moduleWorkspaceLimitPreset = 0x00000021;
const PTCID PID_kuka_moduleCustomWorkspaceLimits = 0x00000011;
const PTCID PID_kuka_moduleIs9DOF = 0x0000001A;
const PTCID PID_kuka_moduleTask = 0x00000001;
const PTCID PID_kuka_moduleControllerFastCyclic = 0x00000006;
const PTCID PID_kuka_moduleControllerFastPostCyclic = 0x00000007;
const PTCID PID_kuka_modulePostCyclicCaller = 0x00000008;
const PTCID PID_kuka_modulefast_control_motor_enable = 0x00000009;
const PTCID PID_kuka_modulefast_control_motor_torque = 0x00000004;
const PTCID PID_kuka_modulefast_sensor_motor_torque_feedback = 0x00000002;
const PTCID PID_kuka_modulefast_sensor_torque = 0x00000003;
const PTCID PID_kuka_modulefast_sensor_position = 0x00000005;
const PTCID PID_kuka_modulefast_control_axis_enable = 0x0000001B;
const PTCID PID_kuka_modulefast_control_axis_force = 0x00000012;
const PTCID PID_kuka_modulefast_control_axis_position = 0x00000013;
const PTCID PID_kuka_modulefast_control_axis_velocity = 0x00000014;
const PTCID PID_kuka_modulefast_sensor_axis_force = 0x00000015;
const PTCID PID_kuka_modulefast_sensor_axis_position = 0x00000016;
const PTCID PID_kuka_modulefast_sensor_axis_velocity = 0x00000017;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
#if !defined(_TC_TYPE_4E6FCA7C_44FD_44F3_9458_4217B8A62937_INCLUDED_)
#define _TC_TYPE_4E6FCA7C_44FD_44F3_9458_4217B8A62937_INCLUDED_
#pragma pack(push,1)
typedef struct _PDS1_Tx
{
	unsigned char Command;
	ULONG Time_stamp;
	unsigned char Error_SafeOs_Runtime : 1;
	unsigned char Not_used : 7;
	unsigned char VMT_Response;
	USHORT FCS_0;
	ULONG Position_1;
	unsigned char Position_Checksum_1;
	unsigned char Position_mastered_1 : 1;
	unsigned char Position_referencing_1 : 1;
	unsigned char Position_encoder_error_1 : 1;
	unsigned char Position_extrapolated_1 : 1;
	unsigned char Position_Status_1 : 4;
	USHORT FCS_1;
	SHORT Torque_1;
	unsigned char GMS_mastered_1 : 1;
	unsigned char GMS_referencing_1 : 1;
	unsigned char GMS_error_1 : 1;
	unsigned char GMS_extrapolated_1 : 1;
	unsigned char GMS_Status_1 : 4;
	unsigned char Actual_STO_1 : 1;
	unsigned char Actual_SBC_1 : 1;
	unsigned char Error_STO_1 : 1;
	unsigned char Error_SBC_1 : 1;
	unsigned char Error_brake_control_1 : 1;
	unsigned char Brake_not_safe_1 : 1;
	unsigned char Not_used_1 : 2;
	USHORT Mastering_notch_depth_1;
	USHORT FCS_2;
	SHORT Gravity_acceleration_X;
	SHORT Gravity_acceleration_Y;
	SHORT Gravity_acceleration_Z;
	USHORT FCS_3;
	unsigned char Gravity_acceleration_mastered : 1;
	unsigned char Gravity_acceleration_referencing : 1;
	unsigned char Gravity_acceleration_error : 1;
	unsigned char Gravity_acceleration_extrapolated : 1;
	unsigned char Gravity_acceleration_status : 4;
	unsigned char Not_used_2;
	ULONG Not_used_3;
	USHORT FCS_4;
	USHORT Connection_ID;
	USHORT Device_status;
	USHORT Motor_status_1;
	SHORT Motor_torque_1;
	USHORT Mux_value_1;
	unsigned char Motor_error_internal_1 : 1;
	unsigned char Motor_warning_I2t_1 : 1;
	unsigned char Motor_error_I2t_1 : 1;
	unsigned char Motor_error_overcurrent_1 : 1;
	unsigned char Motor_error_total_current_1 : 1;
	unsigned char Motor_error_over_voltage_1 : 1;
	unsigned char Motor_warning_low_voltage_1 : 1;
	unsigned char Motor_error_control_deviation_1 : 1;
	unsigned char Motor_error_current_offset_1 : 1;
	unsigned char Motor_warning_temperature_warning_1 : 1;
	unsigned char Motor_error_temperature_error_1 : 1;
	unsigned char Motor_error_unknown_command_1 : 1;
	unsigned char Motor_error_STO_intern_1 : 1;
	unsigned char Not_used_4 : 3;
	unsigned char Brake_released_1 : 1;
	unsigned char Brake_cooling_off_1 : 1;
	unsigned char Brake_credit_reserved_1 : 1;
	unsigned char Brake_credit_withheld_1 : 1;
	unsigned char Brake_energy_warning_1 : 1;
	unsigned char Brake_energy_error_1 : 1;
	unsigned char Brake_cycles_warning_1 : 1;
	unsigned char Brake_cycles_error_1 : 1;
	unsigned char Brake_memory_error_1 : 1;
	unsigned char Brake_current_error_1 : 1;
	unsigned char Brake_overcurrent_error_1 : 1;
	unsigned char Brake_coil_temperature_error_1 : 1;
	unsigned char Brake_actuator_temperature_error_1 : 1;
	unsigned char Brake_overflow_error_1 : 1;
	unsigned char Brake_parameter_plausibility_error_1 : 1;
	unsigned char Brake_parameter_CRC_error_1 : 1;
	unsigned char Brake_twochannel_error_state_1 : 1;
	unsigned char Brake_twochannel_error_actuating_value_1 : 1;
	unsigned char Brake_twochannel_error_i2_value_1 : 1;
	unsigned char Brake_twochannel_error_energy_1 : 1;
	unsigned char Brake_twochannel_error_cycles_1 : 1;
	unsigned char Not_used_5 : 2;
	unsigned char Brake_twochannel_error_channel_1 : 1;
	unsigned char Error_static_STO_1 : 1;
	unsigned char Error_dynamic_1_STO_1 : 1;
	unsigned char Error_dynamic_2_STO_1 : 1;
	unsigned char Error_HS_SBC_1 : 1;
	unsigned char Error_LS_SBC_1 : 1;
	unsigned char Error_LS_SBC_1_1 : 1;
	unsigned char Error_internal_SOUT_1 : 1;
	unsigned char Error_twochannel_SOUT_1 : 1;
	ULONG Not_used_6;
	ULONG Not_used_7;
	ULONG Not_used_8;
} PDS1_Tx, *PPDS1_Tx;
#pragma pack(pop)
#endif // !defined(_TC_TYPE_4E6FCA7C_44FD_44F3_9458_4217B8A62937_INCLUDED_)

#if !defined(_TC_TYPE_6C145723_1AB9_4A43_8457_2AB534A81D13_INCLUDED_)
#define _TC_TYPE_6C145723_1AB9_4A43_8457_2AB534A81D13_INCLUDED_
#pragma pack(push,1)
typedef struct _PDS1_Rx
{
	unsigned char Command;
	ULONG Used_Time_stamp;
	unsigned char Ack_Error_SafeOs_Runtime : 1;
	unsigned char Not_used : 7;
	unsigned char VMT_Challenge;
	USHORT FCS_0;
	USHORT Maximum_velocity_1;
	USHORT Not_used_1;
	unsigned char Not_used_2;
	unsigned char Ack_mastered_1 : 1;
	unsigned char Ack_referenced_1 : 1;
	unsigned char Ack_encoder_error_1 : 1;
	unsigned char Not_used_3 : 1;
	unsigned char Enable_SLS_1 : 1;
	unsigned char Ack_error_SLS_1 : 1;
	unsigned char Not_used_4 : 2;
	USHORT FCS_1;
	USHORT Torque_collision_level_1;
	unsigned char Ack_GMS_mastered_1 : 1;
	unsigned char Ack_GMS_referenced_1 : 1;
	unsigned char Ack_GMS_encoder_error_1 : 1;
	unsigned char Not_used_5 : 1;
	unsigned char Enable_SCD_1 : 1;
	unsigned char Ack_error_SCD_1 : 1;
	unsigned char Not_used_6 : 1;
	unsigned char Soft_stop_1 : 1;
	unsigned char Motion_enable_1 : 1;
	unsigned char Open_Brake_1 : 1;
	unsigned char Ack_error_STO_1 : 1;
	unsigned char Ack_error_SBC_1 : 1;
	unsigned char Ack_Error_brake_control_1 : 1;
	unsigned char Ack_Error_mastering_notch_depth_1 : 1;
	unsigned char Not_used_7 : 2;
	SHORT Cross_force_compensation_1;
	USHORT FCS_2;
	ULONG Not_used_8;
	USHORT Not_used_9;
	USHORT FCS_3;
	unsigned char Ack_gravity_acceleration_mastered : 1;
	unsigned char Ack_gravity_acceleration_referenced : 1;
	unsigned char Ack_gravity_acceleration_error : 1;
	unsigned char Not_used_10 : 5;
	unsigned char Not_used_11;
	ULONG Not_used_12;
	USHORT FCS_4;
	USHORT Connection_ID;
	USHORT Device_control;
	USHORT Motor_control_1;
	SHORT Motor_torque_1;
	USHORT Not_used_13;
	unsigned char Ack_Motor_error_internal_1 : 1;
	unsigned char Ack_Motor_warning_I2t_1 : 1;
	unsigned char Ack_Motor_error_I2t_1 : 1;
	unsigned char Ack_Motor_error_overcurrent_1 : 1;
	unsigned char Ack_Motor_error_total_current_1 : 1;
	unsigned char Ack_Motor_error_over_voltage_1 : 1;
	unsigned char Ack_Motor_warning_low_voltage_1 : 1;
	unsigned char Ack_Motor_error_control_deviation_1 : 1;
	unsigned char Ack_Motor_error_current_offset_1 : 1;
	unsigned char Ack_Motor_warning_temperature_warning_1 : 1;
	unsigned char Ack_Motor_error_temperature_error_1 : 1;
	unsigned char Ack_Motor_error_unknown_command_1 : 1;
	unsigned char Ack_Motor_error_STO_intern_1 : 1;
	unsigned char Not_used_14 : 3;
	unsigned char Not_used_15;
	unsigned char Ack_Brake_memory_error_1 : 1;
	unsigned char Ack_Brake_current_error_1 : 1;
	unsigned char Ack_Brake_overcurrent_error_1 : 1;
	unsigned char Ack_Brake_coil_temperature_error_1 : 1;
	unsigned char Ack_Brake_actuator_temperature_error_1 : 1;
	unsigned char Ack_Brake_overflow_error_1 : 1;
	unsigned char Ack_Brake_parameter_plausibility_error_1 : 1;
	unsigned char Ack_Brake_parameter_CRC_error_1 : 1;
	unsigned char Ack_Brake_twochannel_error_state_1 : 1;
	unsigned char Ack_Brake_twochannel_error_actuating_value_1 : 1;
	unsigned char Ack_Brake_twochannel_error_i2_value_1 : 1;
	unsigned char Ack_Brake_twochannel_error_energy_1 : 1;
	unsigned char Ack_Brake_twochannel_error_cycles_1 : 1;
	unsigned char Not_used_16 : 2;
	unsigned char Ack_Brake_twochannel_error_channel_1 : 1;
	unsigned char Ack_error_static_STO_1 : 1;
	unsigned char Ack_error_dynamic_1_STO_1 : 1;
	unsigned char Ack_error_dynamic_2_STO_1 : 1;
	unsigned char Ack_error_HS_SBC_1 : 1;
	unsigned char Ack_error_LS_SBC_1 : 1;
	unsigned char Ack_error_LS_SBC_1_1 : 1;
	unsigned char Ack_error_internal_SOUT_1 : 1;
	unsigned char Ack_error_twochannel_SOUT_1 : 1;
	ULONG Not_used_17;
	ULONG Not_used_18;
	ULONG Not_used_19;
} PDS1_Rx, *PPDS1_Rx;
#pragma pack(pop)
#endif // !defined(_TC_TYPE_6C145723_1AB9_4A43_8457_2AB534A81D13_INCLUDED_)

#if !defined(_TC_TYPE_FA86A25A_BF44_4E83_95EA_F9A94802B144_INCLUDED_)
#define _TC_TYPE_FA86A25A_BF44_4E83_95EA_F9A94802B144_INCLUDED_
#pragma pack(push,1)
typedef struct _PDS23_Tx
{
	unsigned char Command;
	ULONG Time_stamp;
	unsigned char Error_SafeOs_Runtime : 1;
	unsigned char Not_used : 7;
	unsigned char VMT_Response;
	USHORT FCS_0;
	ULONG Position_1;
	unsigned char Position_Checksum_1;
	unsigned char Position_mastered_1 : 1;
	unsigned char Position_referencing_1 : 1;
	unsigned char Position_encoder_error_1 : 1;
	unsigned char Position_extrapolated_1 : 1;
	unsigned char Position_Status_1 : 4;
	USHORT FCS_1;
	SHORT Torque_1;
	unsigned char GMS_mastered_1 : 1;
	unsigned char GMS_referencing_1 : 1;
	unsigned char GMS_error_1 : 1;
	unsigned char GMS_extrapolated_1 : 1;
	unsigned char GMS_Status_1 : 4;
	unsigned char Actual_STO_1 : 1;
	unsigned char Actual_SBC_1 : 1;
	unsigned char Error_STO_1 : 1;
	unsigned char Error_SBC_1 : 1;
	unsigned char Error_brake_control_1 : 1;
	unsigned char Brake_not_safe_1 : 1;
	unsigned char Not_used_1 : 2;
	USHORT Mastering_notch_depth_1;
	USHORT FCS_2;
	ULONG Position_2;
	unsigned char Position_Checksum_2;
	unsigned char Position_mastered_2 : 1;
	unsigned char Position_referencing_2 : 1;
	unsigned char Position_encoder_error_2 : 1;
	unsigned char Position_extrapolated_2 : 1;
	unsigned char Position_Status_2 : 4;
	USHORT FCS_3;
	SHORT Torque_2;
	unsigned char GMS_mastered_2 : 1;
	unsigned char GMS_referencing_2 : 1;
	unsigned char GMS_error_2 : 1;
	unsigned char GMS_extrapolated_2 : 1;
	unsigned char GMS_Status_2 : 4;
	unsigned char Actual_STO_2 : 1;
	unsigned char Actual_SBC_2 : 1;
	unsigned char Error_STO_2 : 1;
	unsigned char Error_SBC_2 : 1;
	unsigned char Error_brake_control_2 : 1;
	unsigned char Brake_not_safe_2 : 1;
	unsigned char Not_used_2 : 2;
	USHORT Mastering_notch_depth_2;
	USHORT FCS_4;
	USHORT Connection_ID;
	USHORT Device_status;
	USHORT Motor_status_1;
	SHORT Motor_torque_1;
	USHORT Mux_value_1;
	unsigned char Motor_error_internal_1 : 1;
	unsigned char Motor_warning_I2t_1 : 1;
	unsigned char Motor_error_I2t_1 : 1;
	unsigned char Motor_error_overcurrent_1 : 1;
	unsigned char Motor_error_total_current_1 : 1;
	unsigned char Motor_error_over_voltage_1 : 1;
	unsigned char Motor_warning_low_voltage_1 : 1;
	unsigned char Motor_error_control_deviation_1 : 1;
	unsigned char Motor_error_current_offset_1 : 1;
	unsigned char Motor_warning_temperature_warning_1 : 1;
	unsigned char Motor_error_temperature_error_1 : 1;
	unsigned char Motor_error_unknown_command_1 : 1;
	unsigned char Motor_error_STO_intern_1 : 1;
	unsigned char Not_used_3 : 3;
	unsigned char Brake_released_1 : 1;
	unsigned char Brake_cooling_off_1 : 1;
	unsigned char Brake_credit_reserved_1 : 1;
	unsigned char Brake_credit_withheld_1 : 1;
	unsigned char Brake_energy_warning_1 : 1;
	unsigned char Brake_energy_error_1 : 1;
	unsigned char Brake_cycles_warning_1 : 1;
	unsigned char Brake_cycles_error_1 : 1;
	unsigned char Brake_memory_error_1 : 1;
	unsigned char Brake_current_error_1 : 1;
	unsigned char Brake_overcurrent_error_1 : 1;
	unsigned char Brake_coil_temperature_error_1 : 1;
	unsigned char Brake_actuator_temperature_error_1 : 1;
	unsigned char Brake_overflow_error_1 : 1;
	unsigned char Brake_parameter_plausibility_error_1 : 1;
	unsigned char Brake_parameter_CRC_error_1 : 1;
	unsigned char Brake_twochannel_error_state_1 : 1;
	unsigned char Brake_twochannel_error_actuating_value_1 : 1;
	unsigned char Brake_twochannel_error_i2_value_1 : 1;
	unsigned char Brake_twochannel_error_energy_1 : 1;
	unsigned char Brake_twochannel_error_cycles_1 : 1;
	unsigned char Not_used_4 : 2;
	unsigned char Brake_twochannel_error_channel_1 : 1;
	unsigned char Error_static_STO_1 : 1;
	unsigned char Error_dynamic_1_STO_1 : 1;
	unsigned char Error_dynamic_2_STO_1 : 1;
	unsigned char Error_HS_SBC_1 : 1;
	unsigned char Error_LS_SBC_1 : 1;
	unsigned char Error_LS_SBC_1_1 : 1;
	unsigned char Error_internal_SOUT_1 : 1;
	unsigned char Error_twochannel_SOUT_1 : 1;
	USHORT Motor_status_2;
	SHORT Motor_torque_2;
	USHORT Mux_value_2;
	unsigned char Motor_error_internal_2 : 1;
	unsigned char Motor_warning_I2t_2 : 1;
	unsigned char Motor_error_I2t_2 : 1;
	unsigned char Motor_error_overcurrent_2 : 1;
	unsigned char Motor_error_total_current_2 : 1;
	unsigned char Motor_error_over_voltage_2 : 1;
	unsigned char Motor_warning_low_voltage_2 : 1;
	unsigned char Motor_error_control_deviation_2 : 1;
	unsigned char Motor_error_current_offset_2 : 1;
	unsigned char Motor_warning_temperature_warning_2 : 1;
	unsigned char Motor_error_temperature_error_2 : 1;
	unsigned char Motor_error_unknown_command_2 : 1;
	unsigned char Motor_error_STO_intern_2 : 1;
	unsigned char Not_used_5 : 3;
	unsigned char Brake_released_2 : 1;
	unsigned char Brake_cooling_off_2 : 1;
	unsigned char Brake_credit_reserved_2 : 1;
	unsigned char Brake_credit_withheld_2 : 1;
	unsigned char Brake_energy_warning_2 : 1;
	unsigned char Brake_energy_error_2 : 1;
	unsigned char Brake_cycles_warning_2 : 1;
	unsigned char Brake_cycles_error_2 : 1;
	unsigned char Brake_memory_error_2 : 1;
	unsigned char Brake_current_error_2 : 1;
	unsigned char Brake_overcurrent_error_2 : 1;
	unsigned char Brake_coil_temperature_error_2 : 1;
	unsigned char Brake_actuator_temperature_error_2 : 1;
	unsigned char Brake_overflow_error_2 : 1;
	unsigned char Brake_parameter_plausibility_error_2 : 1;
	unsigned char Brake_parameter_CRC_error_2 : 1;
	unsigned char Brake_twochannel_error_state_2 : 1;
	unsigned char Brake_twochannel_error_actuating_value_2 : 1;
	unsigned char Brake_twochannel_error_i2_value_2 : 1;
	unsigned char Brake_twochannel_error_energy_2 : 1;
	unsigned char Brake_twochannel_error_cycles_2 : 1;
	unsigned char Not_used_6 : 2;
	unsigned char Brake_twochannel_error_channel_2 : 1;
	unsigned char Error_static_STO_2 : 1;
	unsigned char Error_dynamic_1_STO_2 : 1;
	unsigned char Error_dynamic_2_STO_2 : 1;
	unsigned char Error_HS_SBC_2 : 1;
	unsigned char Error_LS_SBC_2 : 1;
	unsigned char Error_LS_SBC_2_1 : 1;
	unsigned char Error_internal_SOUT_2 : 1;
	unsigned char Error_twochannel_SOUT_2 : 1;
} PDS23_Tx, *PPDS23_Tx;
#pragma pack(pop)
#endif // !defined(_TC_TYPE_FA86A25A_BF44_4E83_95EA_F9A94802B144_INCLUDED_)

#if !defined(_TC_TYPE_EB55F131_75A4_4536_97BA_2833018AE3F6_INCLUDED_)
#define _TC_TYPE_EB55F131_75A4_4536_97BA_2833018AE3F6_INCLUDED_
#pragma pack(push,1)
typedef struct _PDS23_Rx
{
	unsigned char Command;
	ULONG Used_Time_stamp;
	unsigned char Ack_Error_SafeOs_Runtime : 1;
	unsigned char Not_used : 7;
	unsigned char VMT_Challenge;
	USHORT FCS_0;
	USHORT Maximum_velocity_1;
	USHORT Not_used_1;
	unsigned char Not_used_2;
	unsigned char Ack_mastered_1 : 1;
	unsigned char Ack_referenced_1 : 1;
	unsigned char Ack_encoder_error_1 : 1;
	unsigned char Not_used_3 : 1;
	unsigned char Enable_SLS_1 : 1;
	unsigned char Ack_error_SLS_1 : 1;
	unsigned char Not_used_4 : 2;
	USHORT FCS_1;
	USHORT Torque_collision_level_1;
	unsigned char Ack_GMS_mastered_1 : 1;
	unsigned char Ack_GMS_referenced_1 : 1;
	unsigned char Ack_GMS_encoder_error_1 : 1;
	unsigned char Not_used_5 : 1;
	unsigned char Enable_SCD_1 : 1;
	unsigned char Ack_error_SCD_1 : 1;
	unsigned char Not_used_6 : 1;
	unsigned char Soft_stop_1 : 1;
	unsigned char Motion_enable_1 : 1;
	unsigned char Open_Brake_1 : 1;
	unsigned char Ack_error_STO_1 : 1;
	unsigned char Ack_error_SBC_1 : 1;
	unsigned char Ack_Error_brake_control_1 : 1;
	unsigned char Ack_Error_mastering_notch_depth_1 : 1;
	unsigned char Not_used_7 : 2;
	SHORT Cross_force_compensation_1;
	USHORT FCS_2;
	USHORT Maximum_velocity_2;
	USHORT Not_used_8;
	unsigned char Not_used_9;
	unsigned char Ack_mastered_2 : 1;
	unsigned char Ack_referenced_2 : 1;
	unsigned char Ack_encoder_error_2 : 1;
	unsigned char Not_used_10 : 1;
	unsigned char Enable_SLS_2 : 1;
	unsigned char Ack_error_SLS_2 : 1;
	unsigned char Not_used_11 : 2;
	USHORT FCS_3;
	USHORT Torque_collision_level_2;
	unsigned char Ack_GMS_mastered_2 : 1;
	unsigned char Ack_GMS_referenced_2 : 1;
	unsigned char Ack_GMS_encoder_error_2 : 1;
	unsigned char Not_used_12 : 1;
	unsigned char Enable_SCD_2 : 1;
	unsigned char Ack_error_SCD_2 : 1;
	unsigned char Not_used_13 : 1;
	unsigned char Soft_stop_2 : 1;
	unsigned char Motion_enable_2 : 1;
	unsigned char Open_Brake_2 : 1;
	unsigned char Ack_error_STO_2 : 1;
	unsigned char Ack_error_SBC_2 : 1;
	unsigned char Ack_Error_brake_control_2 : 1;
	unsigned char Ack_Error_mastering_notch_depth_2 : 1;
	unsigned char Not_used_14 : 2;
	SHORT Cross_force_compensation_2;
	USHORT FCS_4;
	USHORT Connection_ID;
	USHORT Device_control;
	USHORT Motor_control_1;
	SHORT Motor_torque_1;
	USHORT Not_used_15;
	unsigned char Ack_Motor_error_internal_1 : 1;
	unsigned char Ack_Motor_warning_I2t_1 : 1;
	unsigned char Ack_Motor_error_I2t_1 : 1;
	unsigned char Ack_Motor_error_overcurrent_1 : 1;
	unsigned char Ack_Motor_error_total_current_1 : 1;
	unsigned char Ack_Motor_error_over_voltage_1 : 1;
	unsigned char Ack_Motor_warning_low_voltage_1 : 1;
	unsigned char Ack_Motor_error_control_deviation_1 : 1;
	unsigned char Ack_Motor_error_current_offset_1 : 1;
	unsigned char Ack_Motor_warning_temperature_warning_1 : 1;
	unsigned char Ack_Motor_error_temperature_error_1 : 1;
	unsigned char Ack_Motor_error_unknown_command_1 : 1;
	unsigned char Ack_Motor_error_STO_intern_1 : 1;
	unsigned char Not_used_16 : 3;
	unsigned char Not_used_17;
	unsigned char Ack_Brake_memory_error_1 : 1;
	unsigned char Ack_Brake_current_error_1 : 1;
	unsigned char Ack_Brake_overcurrent_error_1 : 1;
	unsigned char Ack_Brake_coil_temperature_error_1 : 1;
	unsigned char Ack_Brake_actuator_temperature_error_1 : 1;
	unsigned char Ack_Brake_overflow_error_1 : 1;
	unsigned char Ack_Brake_parameter_plausibility_error_1 : 1;
	unsigned char Ack_Brake_parameter_CRC_error_1 : 1;
	unsigned char Ack_Brake_twochannel_error_state_1 : 1;
	unsigned char Ack_Brake_twochannel_error_actuating_value_1 : 1;
	unsigned char Ack_Brake_twochannel_error_i2_value_1 : 1;
	unsigned char Ack_Brake_twochannel_error_energy_1 : 1;
	unsigned char Ack_Brake_twochannel_error_cycles_1 : 1;
	unsigned char Not_used_18 : 2;
	unsigned char Ack_Brake_twochannel_error_channel_1 : 1;
	unsigned char Ack_error_static_STO_1 : 1;
	unsigned char Ack_error_dynamic_1_STO_1 : 1;
	unsigned char Ack_error_dynamic_2_STO_1 : 1;
	unsigned char Ack_error_HS_SBC_1 : 1;
	unsigned char Ack_error_LS_SBC_1 : 1;
	unsigned char Ack_error_LS_SBC_1_1 : 1;
	unsigned char Ack_error_internal_SOUT_1 : 1;
	unsigned char Ack_error_twochannel_SOUT_1 : 1;
	USHORT Motor_control_2;
	SHORT Motor_torque_2;
	USHORT Not_used_19;
	unsigned char Ack_Motor_error_internal_2 : 1;
	unsigned char Ack_Motor_warning_I2t_2 : 1;
	unsigned char Ack_Motor_error_I2t_2 : 1;
	unsigned char Ack_Motor_error_overcurrent_2 : 1;
	unsigned char Ack_Motor_error_total_current_2 : 1;
	unsigned char Ack_Motor_error_over_voltage_2 : 1;
	unsigned char Ack_Motor_warning_low_voltage_2 : 1;
	unsigned char Ack_Motor_error_control_deviation_2 : 1;
	unsigned char Ack_Motor_error_current_offset_2 : 1;
	unsigned char Ack_Motor_warning_temperature_warning_2 : 1;
	unsigned char Ack_Motor_error_temperature_error_2 : 1;
	unsigned char Ack_Motor_error_unknown_command_2 : 1;
	unsigned char Ack_Motor_error_STO_intern_2 : 1;
	unsigned char Not_used_20 : 3;
	unsigned char Not_used_21;
	unsigned char Ack_Brake_memory_error_2 : 1;
	unsigned char Ack_Brake_current_error_2 : 1;
	unsigned char Ack_Brake_overcurrent_error_2 : 1;
	unsigned char Ack_Brake_coil_temperature_error_2 : 1;
	unsigned char Ack_Brake_actuator_temperature_error_2 : 1;
	unsigned char Ack_Brake_overflow_error_2 : 1;
	unsigned char Ack_Brake_parameter_plausibility_error_2 : 1;
	unsigned char Ack_Brake_parameter_CRC_error_2 : 1;
	unsigned char Ack_Brake_twochannel_error_state_2 : 1;
	unsigned char Ack_Brake_twochannel_error_actuating_value_2 : 1;
	unsigned char Ack_Brake_twochannel_error_i2_value_2 : 1;
	unsigned char Ack_Brake_twochannel_error_energy_2 : 1;
	unsigned char Ack_Brake_twochannel_error_cycles_2 : 1;
	unsigned char Not_used_22 : 2;
	unsigned char Ack_Brake_twochannel_error_channel_2 : 1;
	unsigned char Ack_error_static_STO_2 : 1;
	unsigned char Ack_error_dynamic_1_STO_2 : 1;
	unsigned char Ack_error_dynamic_2_STO_2 : 1;
	unsigned char Ack_error_HS_SBC_2 : 1;
	unsigned char Ack_error_LS_SBC_2 : 1;
	unsigned char Ack_error_LS_SBC_1_2 : 1;
	unsigned char Ack_error_internal_SOUT_2 : 1;
	unsigned char Ack_error_twochannel_SOUT_2 : 1;
} PDS23_Rx, *PPDS23_Rx;
#pragma pack(pop)
#endif // !defined(_TC_TYPE_EB55F131_75A4_4536_97BA_2833018AE3F6_INCLUDED_)

#if !defined(_TC_TYPE_2438F91B_E188_4ED7_8594_54354F9ED6A4_INCLUDED_)
#define _TC_TYPE_2438F91B_E188_4ED7_8594_54354F9ED6A4_INCLUDED_
typedef struct _Safety_FSOE_6
{
	unsigned char FSoE_CMD;
	unsigned char FSoE_Data : 8;
	USHORT FSoE_CRC_0;
	USHORT FSoE_ConnID;
} Safety_FSOE_6, *PSafety_FSOE_6;
#endif // !defined(_TC_TYPE_2438F91B_E188_4ED7_8594_54354F9ED6A4_INCLUDED_)

#if !defined(_TC_TYPE_5C464485_6315_4D36_9FBD_50223B279D29_INCLUDED_)
#define _TC_TYPE_5C464485_6315_4D36_9FBD_50223B279D29_INCLUDED_
#pragma pack(push,1)
typedef struct _KsoePacket
{
	unsigned char Command;
	Safety_FSOE_6 SafeData0;
	USHORT FCS_0;
	Safety_FSOE_6 SafeData1;
	USHORT FCS_1;
	Safety_FSOE_6 SafeData2;
	USHORT FCS_2;
	Safety_FSOE_6 SafeData3;
	USHORT FCS_3;
	Safety_FSOE_6 SafeData4;
	USHORT FCS4;
	USHORT Connection_ID;
} KsoePacket, *PKsoePacket;
#pragma pack(pop)
#endif // !defined(_TC_TYPE_5C464485_6315_4D36_9FBD_50223B279D29_INCLUDED_)

#if !defined(_TC_TYPE_13E58839_8CC7_48B4_9308_7B3FE42FDDD9_INCLUDED_)
#define _TC_TYPE_13E58839_8CC7_48B4_9308_7B3FE42FDDD9_INCLUDED_
typedef double matrix_7_real_T[7];
#endif // !defined(_TC_TYPE_13E58839_8CC7_48B4_9308_7B3FE42FDDD9_INCLUDED_)

#if !defined(_TC_TYPE_9B42F47D_2922_4779_9D13_E026C0D38231_INCLUDED_)
#define _TC_TYPE_9B42F47D_2922_4779_9D13_E026C0D38231_INCLUDED_
#pragma pack(push,1)
typedef struct _MFT_FSoE_Inputs
{
	unsigned char FSOE_CMD;
	unsigned char SIND_INPUT_B0 : 1;
	unsigned char SIND_INPUT_A1 : 1;
	unsigned char SIND_INPUT_2 : 1;
	unsigned char SIND_INPUT_3 : 1;
	unsigned char SIND_ERR_B0 : 1;
	unsigned char SIND_ERR_A1 : 1;
	unsigned char SIND_ERR_2 : 1;
	unsigned char SIND_ERR_3 : 1;
	unsigned char RESERVED_00 : 2;
	unsigned char RESERVED_04 : 1;
	unsigned char RESERVED_05 : 1;
	unsigned char RESERVED_06 : 1;
	unsigned char RESERVED_07 : 1;
	unsigned char RESERVED_01 : 2;
	USHORT CRC0;
	USHORT DATA1;
	USHORT CRC1;
	USHORT DATA2;
	USHORT CRC2;
	USHORT DATA3;
	USHORT CRC3;
	USHORT DATA4;
	USHORT CRC4;
	USHORT CONNECTION_ID;
} MFT_FSoE_Inputs, *PMFT_FSoE_Inputs;
#pragma pack(pop)
#endif // !defined(_TC_TYPE_9B42F47D_2922_4779_9D13_E026C0D38231_INCLUDED_)

#if !defined(_TC_TYPE_EE6E175B_465D_4AAD_8EEF_5D49F5B3E789_INCLUDED_)
#define _TC_TYPE_EE6E175B_465D_4AAD_8EEF_5D49F5B3E789_INCLUDED_
#pragma pack(push,1)
typedef struct _MFT_FSoE_Outputs
{
	unsigned char FSOE_CMD;
	unsigned char SIND_ERR_ACK_B0 : 1;
	unsigned char SIND_ERR_ACK_A1 : 1;
	unsigned char SIND_ERR_ACK_2 : 1;
	unsigned char SIND_ERR_ACK_3 : 1;
	unsigned char RESERVED_00 : 4;
	unsigned char RESERVED_18 : 1;
	unsigned char RESERVED_19 : 1;
	unsigned char RESERVED_20 : 1;
	unsigned char RESERVED_21 : 1;
	unsigned char RESERVED_15 : 1;
	unsigned char RESERVED_16 : 1;
	unsigned char RESERVED_01 : 2;
	USHORT CRC0;
	USHORT DATA1;
	USHORT CRC1;
	USHORT DATA2;
	USHORT CRC2;
	USHORT DATA3;
	USHORT CRC3;
	USHORT DATA4;
	USHORT CRC4;
	USHORT CONNECTION_ID;
} MFT_FSoE_Outputs, *PMFT_FSoE_Outputs;
#pragma pack(pop)
#endif // !defined(_TC_TYPE_EE6E175B_465D_4AAD_8EEF_5D49F5B3E789_INCLUDED_)

#if !defined(_TC_TYPE_03EE26B8_E87F_4BC1_8BD8_1FB51CBF8236_INCLUDED_)
#define _TC_TYPE_03EE26B8_E87F_4BC1_8BD8_1FB51CBF8236_INCLUDED_
#pragma pack(push,1)
typedef struct _FSoE_Packet
{
	unsigned char FSOE_CMD;
	USHORT DATA0;
	USHORT CRC0;
	USHORT DATA1;
	USHORT CRC1;
	USHORT DATA2;
	USHORT CRC2;
	USHORT DATA3;
	USHORT CRC3;
	USHORT DATA4;
	USHORT CRC4;
	USHORT CONNECTION_ID;
} FSoE_Packet, *PFSoE_Packet;
#pragma pack(pop)
#endif // !defined(_TC_TYPE_03EE26B8_E87F_4BC1_8BD8_1FB51CBF8236_INCLUDED_)

#if !defined(_TC_TYPE_86FD7197_F76C_4674_AF3B_5DBD7A9BA18C_INCLUDED_)
#define _TC_TYPE_86FD7197_F76C_4674_AF3B_5DBD7A9BA18C_INCLUDED_
#pragma pack(push,1)
typedef struct _MotorcontrollerInput
{
	USHORT Statusword;
	char Modes_of_operation_display;
	LONG Position_actual_value;
	SHORT Torque_actual_value;
	LONG Velocity_actual_value;
} MotorcontrollerInput, *PMotorcontrollerInput;
#pragma pack(pop)
#endif // !defined(_TC_TYPE_86FD7197_F76C_4674_AF3B_5DBD7A9BA18C_INCLUDED_)

#if !defined(_TC_TYPE_CC802308_C90B_42FA_AFBB_D786DF564F4D_INCLUDED_)
#define _TC_TYPE_CC802308_C90B_42FA_AFBB_D786DF564F4D_INCLUDED_
#pragma pack(push,1)
typedef struct _MotorcontrollerOutput
{
	USHORT Controlword;
	char Modes_of_operation;
	SHORT Target_torque;
	LONG Target_velocity;
	LONG Target_position;
} MotorcontrollerOutput, *PMotorcontrollerOutput;
#pragma pack(pop)
#endif // !defined(_TC_TYPE_CC802308_C90B_42FA_AFBB_D786DF564F4D_INCLUDED_)

#if !defined(_TC_TYPE_BB70DAAD_4E7A_B6F5_9E66_27230D456EC9_INCLUDED_)
#define _TC_TYPE_BB70DAAD_4E7A_B6F5_9E66_27230D456EC9_INCLUDED_
typedef double matrix_2_real_T[2];
#endif // !defined(_TC_TYPE_BB70DAAD_4E7A_B6F5_9E66_27230D456EC9_INCLUDED_)

#if !defined(_TC_TYPE_6761E8AA_7A72_5550_E6F7_E2105630A466_INCLUDED_)
#define _TC_TYPE_6761E8AA_7A72_5550_E6F7_E2105630A466_INCLUDED_
typedef double matrix_3_real_T[3];
#endif // !defined(_TC_TYPE_6761E8AA_7A72_5550_E6F7_E2105630A466_INCLUDED_)

#if !defined(_TC_TYPE_7EE8C837_5422_822C_B31D_2AF1AD3DA250_INCLUDED_)
#define _TC_TYPE_7EE8C837_5422_822C_B31D_2AF1AD3DA250_INCLUDED_
typedef double matrix_9_real_T[9];
#endif // !defined(_TC_TYPE_7EE8C837_5422_822C_B31D_2AF1AD3DA250_INCLUDED_)

#if !defined(_TC_TYPE_B42637D1_178E_4D26_B41E_82267BEC09C2_INCLUDED_)
#define _TC_TYPE_B42637D1_178E_4D26_B41E_82267BEC09C2_INCLUDED_
typedef struct _Event
{
	SHORT code;
	SHORT type;
	SHORT axis_number;
	SHORT slave;
} Event, *PEvent;
#endif // !defined(_TC_TYPE_B42637D1_178E_4D26_B41E_82267BEC09C2_INCLUDED_)

typedef struct _kuka_moduleLinearAxisParameters
{
	double PositionSoftReserve;
	double VelocityLimit;
	double PositionFilterFrequency;
	double VelocityFilterFrequency;
	double AxisForceLimit;
	double AxisForceSaturation;
} kuka_moduleLinearAxisParameters, *Pkuka_moduleLinearAxisParameters;

enum kuka_moduleWorkspaceLimitPreset : SHORT {
	full = 0,
	leftOnly = 1,
	rightOnly = 2,
	custom = 3
};

#pragma pack(push,1)
typedef struct _kuka_moduleInput
{
	PDS1_Tx Input_PDS1;
	PDS23_Tx Input_PDS23_1;
	PDS23_Tx Input_PDS23_2;
	PDS23_Tx Input_PDS23_3;
	MFT_FSoE_Inputs Input_MFT;
	BYTE NSR_INPUT;
	AmsNetId Robot_AmsNetId;
} kuka_moduleInput, *Pkuka_moduleInput;
#pragma pack(pop)

#pragma pack(push,1)
typedef struct _kuka_moduleOutput
{
	PDS1_Rx Output_PDS1;
	PDS23_Rx Output_PDS23_1;
	PDS23_Rx Output_PDS23_2;
	PDS23_Rx Output_PDS23_3;
	MFT_FSoE_Outputs Output_MFT;
	BYTE NSR_INDICATOR;
} kuka_moduleOutput, *Pkuka_moduleOutput;
#pragma pack(pop)

#pragma pack(push,1)
typedef struct _kuka_moduleRobot_Inputs
{
	double MotionEnableRobot;
	double MotionDisableRobot;
	double MotionDisableLinearaxes;
	double MotionEnableLinearaxes;
	unsigned char ModeOfOperation;
} kuka_moduleRobot_Inputs, *Pkuka_moduleRobot_Inputs;
#pragma pack(pop)

#pragma pack(push,1)
typedef struct _kuka_moduleRobot_Sensors
{
	matrix_2_real_T sensor_position_linear;
	matrix_7_real_T sensor_position;
	matrix_2_real_T sensor_velocity_linear;
	matrix_7_real_T sensor_velocity;
	matrix_2_real_T sensor_force;
	matrix_7_real_T sensor_torque;
	matrix_7_real_T sensor_torque_derivative;
	matrix_7_real_T sensor_current_rms;
	matrix_7_real_T sensor_i2t_percent;
	double sensor_mft_enable_button_pressed;
	double sensor_mft_enable_button_panic;
	double sensor_mft_application_button;
	Event stop_event;
	double RobotState;
	double MotionEnabled;
	matrix_3_real_T cartesian_position;
	matrix_3_real_T cartesian_orientation;
	bool outside_workspace;
} kuka_moduleRobot_Sensors, *Pkuka_moduleRobot_Sensors;
#pragma pack(pop)

#pragma pack(push,1)
typedef struct _kuka_moduleMotorcontrollerInput
{
	MotorcontrollerInput Motorcontroller1Input;
	MotorcontrollerInput Motorcontroller2Input;
} kuka_moduleMotorcontrollerInput, *Pkuka_moduleMotorcontrollerInput;
#pragma pack(pop)

#pragma pack(push,1)
typedef struct _kuka_moduleMotorcontrollerOutput
{
	MotorcontrollerOutput Motorcontroller1Output;
	MotorcontrollerOutput Motorcontroller2Output;
} kuka_moduleMotorcontrollerOutput, *Pkuka_moduleMotorcontrollerOutput;
#pragma pack(pop)

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_kuka_moduleInput 1
#define ADI_kuka_moduleOutput 2
#define ADI_kuka_moduleRobot_Inputs 3
#define ADI_kuka_moduleRobot_Sensors 4
#define ADI_kuka_moduleMotorcontrollerInput 5
#define ADI_kuka_moduleMotorcontrollerOutput 6
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
