///////////////////////////////////////////////////////////////////////////////
// kuka_module.cpp
#include "TcPch.h"
#pragma hdrstop

#include "kuka_module.h"
#include "Robot1.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#endif
DEFINE_THIS_FILE()

///////////////////////////////////////////////////////////////////////////////
// Ckuka_module
///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////
// Collection of interfaces implemented by module Ckuka_module
BEGIN_INTERFACE_MAP(Ckuka_module)
	INTERFACE_ENTRY_ITCOMOBJECT()
	INTERFACE_ENTRY(IID_ITcADI, ITcADI)
	INTERFACE_ENTRY(IID_ITcWatchSource, ITcWatchSource)
///<AutoGeneratedContent id="InterfaceMap">
	INTERFACE_ENTRY(IID_ITcCyclic, ITcCyclic)
	INTERFACE_ENTRY(IID_ITcPostCyclic, ITcPostCyclic)
///</AutoGeneratedContent>
END_INTERFACE_MAP()

IMPLEMENT_ITCOMOBJECT(Ckuka_module)
IMPLEMENT_ITCOMOBJECT_SETSTATE_LOCKOP2(Ckuka_module)
IMPLEMENT_ITCADI(Ckuka_module)
IMPLEMENT_ITCWATCHSOURCE(Ckuka_module)

///////////////////////////////////////////////////////////////////////////////
// Set parameters of Ckuka_module 
BEGIN_SETOBJPARA_MAP(Ckuka_module)
	SETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="SetObjectParameterMap">
	SETOBJPARA_VALUE(PID_TcTraceLevel, m_TraceLevelMax)
	SETOBJPARA_VALUE(PID_kuka_moduleAxisVelocityLimit, m_AxisVelocityLimit)
	SETOBJPARA_VALUE(PID_kuka_moduleAxisMotorTorqueLimit, m_AxisMotorTorqueLimit)
	SETOBJPARA_VALUE(PID_kuka_moduleAxisMotorTorqueSaturation, m_AxisMotorTorqueSaturation)
	SETOBJPARA_VALUE(PID_kuka_moduleAxisSensorTorqueLimit, m_AxisSensorTorqueLimit)
	SETOBJPARA_VALUE(PID_kuka_moduleAxisPositionSoftReserve, m_AxisPositionSoftReserve)
	SETOBJPARA_VALUE(PID_kuka_moduleLinearAxisParameters, m_LinearAxisParameters)
	SETOBJPARA_VALUE(PID_kuka_modulemass_tool, m_mass_tool)
	SETOBJPARA_VALUE(PID_kuka_modulecog_tool, m_cog_tool)
	SETOBJPARA_VALUE(PID_kuka_moduletcp_tool, m_tcp_tool)
	SETOBJPARA_VALUE(PID_kuka_moduleWorldTranslation, m_WorldTranslation)
	SETOBJPARA_VALUE(PID_kuka_moduleWorldRotation, m_WorldRotation)
	SETOBJPARA_VALUE(PID_kuka_moduleWorkspaceLimitPreset, m_WorkspaceLimitPreset)
	SETOBJPARA_VALUE(PID_kuka_moduleCustomWorkspaceLimits, m_CustomWorkspaceLimits)
	SETOBJPARA_VALUE(PID_kuka_moduleIs9DOF, m_Is9DOF)
	SETOBJPARA_ITFPTR(PID_Ctx_TaskOid, m_spCyclicCaller)
	SETOBJPARA_ITFPTR(PID_kuka_moduleTask, m_spTask)
	SETOBJPARA_ITFPTR(PID_kuka_moduleControllerFastCyclic, m_spControllerFastCyclic)
	SETOBJPARA_ITFPTR(PID_kuka_moduleControllerFastPostCyclic, m_spControllerFastPostCyclic)
	SETOBJPARA_ITFPTR(PID_kuka_modulePostCyclicCaller, m_spPostCyclicCaller)
	SETOBJPARA_DATAPTR(PID_kuka_modulefast_control_motor_enable, m_spfast_control_motor_enable)
	SETOBJPARA_DATAPTR(PID_kuka_modulefast_control_motor_torque, m_spfast_control_motor_torque)
	SETOBJPARA_DATAPTR(PID_kuka_modulefast_sensor_motor_torque_feedback, m_spfast_sensor_motor_torque_feedback)
	SETOBJPARA_DATAPTR(PID_kuka_modulefast_sensor_torque, m_spfast_sensor_torque)
	SETOBJPARA_DATAPTR(PID_kuka_modulefast_sensor_position, m_spfast_sensor_position)
	SETOBJPARA_DATAPTR(PID_kuka_modulefast_control_axis_enable, m_spfast_control_axis_enable)
	SETOBJPARA_DATAPTR(PID_kuka_modulefast_control_axis_force, m_spfast_control_axis_force)
	SETOBJPARA_DATAPTR(PID_kuka_modulefast_control_axis_position, m_spfast_control_axis_position)
	SETOBJPARA_DATAPTR(PID_kuka_modulefast_control_axis_velocity, m_spfast_control_axis_velocity)
	SETOBJPARA_DATAPTR(PID_kuka_modulefast_sensor_axis_force, m_spfast_sensor_axis_force)
	SETOBJPARA_DATAPTR(PID_kuka_modulefast_sensor_axis_position, m_spfast_sensor_axis_position)
	SETOBJPARA_DATAPTR(PID_kuka_modulefast_sensor_axis_velocity, m_spfast_sensor_axis_velocity)
///</AutoGeneratedContent>
END_SETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get parameters of Ckuka_module 
BEGIN_GETOBJPARA_MAP(Ckuka_module)
	GETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="GetObjectParameterMap">
	GETOBJPARA_VALUE(PID_TcTraceLevel, m_TraceLevelMax)
	GETOBJPARA_VALUE(PID_kuka_moduleAxisVelocityLimit, m_AxisVelocityLimit)
	GETOBJPARA_VALUE(PID_kuka_moduleAxisMotorTorqueLimit, m_AxisMotorTorqueLimit)
	GETOBJPARA_VALUE(PID_kuka_moduleAxisMotorTorqueSaturation, m_AxisMotorTorqueSaturation)
	GETOBJPARA_VALUE(PID_kuka_moduleAxisSensorTorqueLimit, m_AxisSensorTorqueLimit)
	GETOBJPARA_VALUE(PID_kuka_moduleAxisPositionSoftReserve, m_AxisPositionSoftReserve)
	GETOBJPARA_VALUE(PID_kuka_moduleLinearAxisParameters, m_LinearAxisParameters)
	GETOBJPARA_VALUE(PID_kuka_modulemass_tool, m_mass_tool)
	GETOBJPARA_VALUE(PID_kuka_modulecog_tool, m_cog_tool)
	GETOBJPARA_VALUE(PID_kuka_moduletcp_tool, m_tcp_tool)
	GETOBJPARA_VALUE(PID_kuka_moduleWorldTranslation, m_WorldTranslation)
	GETOBJPARA_VALUE(PID_kuka_moduleWorldRotation, m_WorldRotation)
	GETOBJPARA_VALUE(PID_kuka_moduleWorkspaceLimitPreset, m_WorkspaceLimitPreset)
	GETOBJPARA_VALUE(PID_kuka_moduleCustomWorkspaceLimits, m_CustomWorkspaceLimits)
	GETOBJPARA_VALUE(PID_kuka_moduleIs9DOF, m_Is9DOF)
	GETOBJPARA_ITFPTR(PID_Ctx_TaskOid, m_spCyclicCaller)
	GETOBJPARA_ITFPTR(PID_kuka_moduleTask, m_spTask)
	GETOBJPARA_ITFPTR(PID_kuka_moduleControllerFastCyclic, m_spControllerFastCyclic)
	GETOBJPARA_ITFPTR(PID_kuka_moduleControllerFastPostCyclic, m_spControllerFastPostCyclic)
	GETOBJPARA_ITFPTR(PID_kuka_modulePostCyclicCaller, m_spPostCyclicCaller)
///</AutoGeneratedContent>
END_GETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get watch entries of Ckuka_module
BEGIN_OBJPARAWATCH_MAP(Ckuka_module)
	OBJPARAWATCH_DATAAREA_MAP()
///<AutoGeneratedContent id="ObjectParameterWatchMap">
	OBJPARAWATCH_VALUE(PID_kuka_moduletcp_tool, m_tcp_tool)
	OBJPARAWATCH_VALUE(PID_kuka_moduleIs9DOF, m_Is9DOF)
///</AutoGeneratedContent>
END_OBJPARAWATCH_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get data area members of Ckuka_module
BEGIN_OBJDATAAREA_MAP(Ckuka_module)
///<AutoGeneratedContent id="ObjectDataAreaMap">
	OBJDATAAREA_VALUE(ADI_kuka_moduleInput, m_Input)
	OBJDATAAREA_VALUE(ADI_kuka_moduleOutput, m_Output)
	OBJDATAAREA_VALUE(ADI_kuka_moduleRobot_Inputs, m_Robot_Inputs)
	OBJDATAAREA_VALUE(ADI_kuka_moduleRobot_Sensors, m_Robot_Sensors)
	OBJDATAAREA_VALUE(ADI_kuka_moduleMotorcontrollerInput, m_MotorcontrollerInput)
	OBJDATAAREA_VALUE(ADI_kuka_moduleMotorcontrollerOutput, m_MotorcontrollerOutput)
///</AutoGeneratedContent>
END_OBJDATAAREA_MAP()


///////////////////////////////////////////////////////////////////////////////
Ckuka_module::Ckuka_module()
  : m_Trace(m_TraceLevelMax, m_spSrv),
  counter(0), dc_last(0)
{
///<AutoGeneratedContent id="MemberInitialization">
	m_TraceLevelMax = tlAlways;
	m_AxisVelocityLimit = 0;
	m_AxisMotorTorqueLimit = 0;
	m_AxisMotorTorqueSaturation = 0;
	m_AxisSensorTorqueLimit = 0;
	m_AxisPositionSoftReserve = 0;
	memset(&m_LinearAxisParameters, 0, sizeof(m_LinearAxisParameters));
	m_mass_tool = 0;
	memset(&m_cog_tool, 0, sizeof(m_cog_tool));
	memset(&m_tcp_tool, 0, sizeof(m_tcp_tool));
	memset(&m_WorldTranslation, 0, sizeof(m_WorldTranslation));
	memset(&m_WorldRotation, 0, sizeof(m_WorldRotation));
	m_WorkspaceLimitPreset = full;
	memset(&m_CustomWorkspaceLimits, 0, sizeof(m_CustomWorkspaceLimits));
	m_Is9DOF = FALSE;
	memset(&m_Input, 0, sizeof(m_Input));
	memset(&m_Output, 0, sizeof(m_Output));
	memset(&m_Robot_Inputs, 0, sizeof(m_Robot_Inputs));
	memset(&m_Robot_Sensors, 0, sizeof(m_Robot_Sensors));
	memset(&m_MotorcontrollerInput, 0, sizeof(m_MotorcontrollerInput));
	memset(&m_MotorcontrollerOutput, 0, sizeof(m_MotorcontrollerOutput));
///</AutoGeneratedContent>
}

///////////////////////////////////////////////////////////////////////////////
Ckuka_module::~Ckuka_module() 
{
}


///////////////////////////////////////////////////////////////////////////////
// State Transitions 
///////////////////////////////////////////////////////////////////////////////
IMPLEMENT_ITCOMOBJECT_SETOBJSTATE_IP_PI(Ckuka_module)

///////////////////////////////////////////////////////////////////////////////
// State transition from PREOP to SAFEOP
//
// Initialize input parameters 
// Allocate memory
HRESULT Ckuka_module::SetObjStatePS(PTComInitDataHdr pInitData)
{
	m_Trace.Log(tlVerbose, FENTERA);

  double tmp;
	HRESULT hr = S_OK;
	IMPLEMENT_ITCOMOBJECT_EVALUATE_INITDATA(pInitData);

  //Prepare the limits
  memset((void*)&limits, 0, sizeof(limits));
  //Model
  limits.is9DOF = m_Is9DOF;
  //Motor Torque Limit
  //Values larger than 100% are admissable, since the absolute current limit exists in addition
  tmp = m_AxisMotorTorqueLimit;
  if (tmp > 400.0) tmp = 400.0;
  else if (tmp < 0.0) tmp = 0.0;
  limits.motor_torque_limit_fraction = tmp / 100.0;
  //Motor Torque Saturation
  //Values larger than 100% are admissable, since the absolute current limit exists in addition
  tmp = m_AxisMotorTorqueSaturation;
  if (tmp > 400.0) tmp = 400.0;
  else if (tmp < 0.0) tmp = 0.0;
  limits.motor_torque_saturation = tmp / 100.0;
  //Sensor Torque Limit
  tmp = m_AxisSensorTorqueLimit;
  if (tmp > 200.0) tmp = 200.0;
  else if (tmp < 0.0) tmp = 0.0;
  limits.sensor_torque_limit_fraction = tmp / 100.0;
  //Velocity Limit
  tmp=m_AxisVelocityLimit;
  if(tmp>100.0) tmp=100.0;
  else if(tmp<0.0) tmp=0.0;
  limits.velocity_limit_fraction=tmp/100.0;
  //Software Position Reserve
  tmp=m_AxisPositionSoftReserve;
  if(tmp<0.0) tmp=0.0;
  limits.position_reserve=tmp*PI/180.0;
  //For linear axes
  limits.laxis_position_reserve = m_LinearAxisParameters.PositionSoftReserve; 
  //Axis Force Limit
  tmp = m_LinearAxisParameters.AxisForceLimit;
  if (tmp > 400.0) tmp = 400.0;
  else if (tmp < 0.0) tmp = 0.0;
  limits.force_limit_fraction = tmp / 100.0;
  //Motor Torque Saturation
  tmp = m_LinearAxisParameters.AxisForceSaturation;
  if (tmp > 100.0) tmp = 100.0;
  else if (tmp < 0.0) tmp = 0.0;
  limits.force_saturation_fraction = tmp / 100.0;
  //Tool
  limits.tool_mass = m_mass_tool;
  limits.tool_cog[0] = m_cog_tool[0];
  limits.tool_cog[1] = m_cog_tool[1];
  limits.tool_cog[2] = m_cog_tool[2];
  limits.tool_tcp[0] = m_tcp_tool[0];
  limits.tool_tcp[1] = m_tcp_tool[1];
  limits.tool_tcp[2] = m_tcp_tool[2];
  limits.tool_tcp[3] = m_tcp_tool[3] * PI / 180.0;
  limits.tool_tcp[4] = m_tcp_tool[4] * PI / 180.0;
  limits.tool_tcp[5] = m_tcp_tool[5] * PI / 180.0;
  //World parameters
  limits.world_param[0] = m_WorldTranslation[0];
  limits.world_param[1] = m_WorldTranslation[1];
  limits.world_param[2] = m_WorldTranslation[2];
  limits.world_param[3] = m_WorldRotation[0] * PI / 180.0;
  limits.world_param[4] = m_WorldRotation[1] * PI / 180.0;
  limits.world_param[5] = m_WorldRotation[2] * PI / 180.0;
  //Workspace Limits
  if (m_WorkspaceLimitPreset == 0) {
	  //full
	  limits.workspace_limits[0] = 0.39;	//xmin
	  limits.workspace_limits[1] = 2.6;		//xmax		
  }
  else if (m_WorkspaceLimitPreset == 1) {
	  //left only
	  limits.workspace_limits[0] = 1.64;	
	  limits.workspace_limits[1] = 2.6;	
  }
  else if (m_WorkspaceLimitPreset == 2) {
	  //right only
	  limits.workspace_limits[0] = 0.39;
	  limits.workspace_limits[1] = 1.28;
  }
  // limits for y and z coordinates stay the same for all options
  limits.workspace_limits[2] = 0.24;	//ymin	
  limits.workspace_limits[3] = 1.685;	//ymax
  limits.workspace_limits[4] = 0;		//zmin
  limits.workspace_limits[5] = 1.58;	//zmax 
  if (m_WorkspaceLimitPreset == 3) {
	  // custom workspace limits
	  limits.workspace_limits[0] = m_CustomWorkspaceLimits[0];	//xmin
	  limits.workspace_limits[1] = m_CustomWorkspaceLimits[1];	//xmax
	  limits.workspace_limits[2] = m_CustomWorkspaceLimits[2];	//ymin
	  limits.workspace_limits[3] = m_CustomWorkspaceLimits[3];	//ymax
	  limits.workspace_limits[4] = m_CustomWorkspaceLimits[4];	//zmin
	  limits.workspace_limits[5] = m_CustomWorkspaceLimits[5];	//zmax
  }
  //Connect the Beckhoff I/O buffers with the slaves.
  robot1_parameters.ksoe_slave_parameters[0].input_buffer=&m_Input.Input_PDS1;
  robot1_parameters.ksoe_slave_parameters[0].output_buffer=&m_Output.Output_PDS1;
  robot1_parameters.ksoe_slave_parameters[1].input_buffer=&m_Input.Input_PDS23_1;
  robot1_parameters.ksoe_slave_parameters[1].output_buffer=&m_Output.Output_PDS23_1;
  robot1_parameters.ksoe_slave_parameters[2].input_buffer=&m_Input.Input_PDS23_2;
  robot1_parameters.ksoe_slave_parameters[2].output_buffer=&m_Output.Output_PDS23_2;
  robot1_parameters.ksoe_slave_parameters[3].input_buffer=&m_Input.Input_PDS23_3;
  robot1_parameters.ksoe_slave_parameters[3].output_buffer=&m_Output.Output_PDS23_3;
  robot1_parameters.fsoe_slave_parameters.input_buffer=&m_Input.Input_MFT;
  robot1_parameters.fsoe_slave_parameters.output_buffer=&m_Output.Output_MFT;
  robot1_parameters.NSR_INDICATOR=&m_Output.NSR_INDICATOR;
  robot1_parameters.NSR_INPUT=&m_Input.NSR_INPUT;

  robot1_parameters.motorcontroller_parameters[0].input_buffer = &m_MotorcontrollerInput.Motorcontroller1Input;
  robot1_parameters.motorcontroller_parameters[0].output_buffer = &m_MotorcontrollerOutput.Motorcontroller1Output;
  robot1_parameters.motorcontroller_parameters[1].input_buffer = &m_MotorcontrollerInput.Motorcontroller2Input;
  robot1_parameters.motorcontroller_parameters[1].output_buffer = &m_MotorcontrollerOutput.Motorcontroller2Output;

  // pass linear axis parameters
  // for x axis (i=0) and y axis (i=1)
  for (int i = 0; i < 2; i++) {
	  robot1_parameters.axis[i].position_limit_lower = limits.workspace_limits[2*i];
	  robot1_parameters.axis[i].position_limit_upper = limits.workspace_limits[2*i + 1];
	  robot1_parameters.axis[i].linear_velocity_limit = m_LinearAxisParameters.VelocityLimit;
	  robot1_parameters.axis[i].position_filter_f_0 = m_LinearAxisParameters.PositionFilterFrequency;
	  robot1_parameters.axis[i].velocity_filter_f_0 = m_LinearAxisParameters.VelocityFilterFrequency;
  }

  robot1=new Robot(&robot1_parameters, &limits, m_spSrv, &m_Trace);
  hr=(robot1==NULL?S_FALSE:S_OK);

  // cleanup on failure
  if(FAILED(hr)) {
    safe_delete(robot1);
  }

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to OP
//
// Register with other TwinCAT objects
HRESULT Ckuka_module::SetObjStateSO()
{
	m_Trace.Log(tlVerbose, FENTERA);
	HRESULT hr = S_OK;

  if(m_spTask.HasOID()) {
    if(!SUCCEEDED_DBG(hr=m_spSrv->TcQuerySmartObjectInterface(m_spTask))) {
      m_spTask=NULL;
    }
  }
  //Request the interfaces of the fast controller.
  if(m_spControllerFastCyclic.HasOID()) {
    if(!SUCCEEDED_DBG(m_spSrv->TcQuerySmartObjectInterface(m_spControllerFastCyclic))) {
      m_spControllerFastCyclic=NULL;
    }
  }
  if(m_spControllerFastPostCyclic.HasOID()) {
    if(!SUCCEEDED_DBG(m_spSrv->TcQuerySmartObjectInterface(m_spControllerFastPostCyclic))) {
      m_spControllerFastPostCyclic=NULL;
    }
  }

  // Initialize data pointer
  hr=FAILED(hr)?hr:InitDataPointer();
	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	// If following call is successful the CycleUpdate method will be called, 
	// possibly even before this method has been left.
	hr = FAILED(hr) ? hr : AddModuleToCaller(); 

	// Cleanup if transition failed at some stage
	if ( FAILED(hr) )
	{
		RemoveModuleFromCaller();
    DeinitDataPointer();
	}
	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from OP to SAFEOP
HRESULT Ckuka_module::SetObjStateOS()
{
	m_Trace.Log(tlVerbose, FENTERA);
	HRESULT hr = S_OK;

	RemoveModuleFromCaller();
  DeinitDataPointer();
  if(m_spTask) {
    m_spTask.Release();
  }
  m_spTask=NULL;

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to PREOP
HRESULT Ckuka_module::SetObjStateSP()
{
	m_Trace.Log(tlVerbose, FENTERA);
	HRESULT hr = S_OK;

  safe_delete(robot1);

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///<AutoGeneratedContent id="ImplementationOf_ITcCyclic">
HRESULT Ckuka_module::CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context)
{
  HRESULT hr=S_OK;
  AxisSensor input[ROBOT_NUM_AXIS];
  MFTSensor input_mft;
  AxisControl output[ROBOT_NUM_AXIS];
  MotorcontrollerModeOfOperation mode_of_operation;
  LONGLONG dc;
  DWORD dc_time_L;
  double q[ROBOT_NUM_AXIS];
  double qp[ROBOT_NUM_AXIS];
  
	//Get AmsNetId for Device1
	if (robot1_parameters.netid.b[0] == 0) {
		robot1_parameters.netid = m_Input.Robot_AmsNetId;
	}
  //Read sensor signals from robot
  memset(input, 0, ROBOT_NUM_AXIS*sizeof(AxisSensor));
  memset(&input_mft, 0, sizeof(MFTSensor));
  robot1->ReadSensor(input, &input_mft);
  //Provide them at the "Robot Sensors"-Outputs

  for (int i = 0; i < ROBOT_NUM_MOTORCONTROLLER; i++) {
	  m_Robot_Sensors.sensor_position_linear[i] = input[i].position_linear_filtered;
	  m_Robot_Sensors.sensor_velocity_linear[i] = input[i].velocity_linear_filtered;
	  m_Robot_Sensors.sensor_force[i] = input[i].force;
	  q[i] = input[i].position_linear_filtered;
	  qp[i] = input[i].velocity_linear_filtered;
  }
  for(int i=ROBOT_NUM_MOTORCONTROLLER; i<ROBOT_NUM_AXIS;i++) {
    m_Robot_Sensors.sensor_position[i-ROBOT_NUM_MOTORCONTROLLER]=input[i].position_filtered;
    m_Robot_Sensors.sensor_velocity[i - ROBOT_NUM_MOTORCONTROLLER]=input[i].velocity_filtered;
    m_Robot_Sensors.sensor_torque[i - ROBOT_NUM_MOTORCONTROLLER]=input[i].torque_filtered;
    m_Robot_Sensors.sensor_torque_derivative[i - ROBOT_NUM_MOTORCONTROLLER]=input[i].torque_derivative_filtered;
	m_Robot_Sensors.sensor_current_rms[i - ROBOT_NUM_MOTORCONTROLLER] = input[i].current_rms;
	m_Robot_Sensors.sensor_i2t_percent[i - ROBOT_NUM_MOTORCONTROLLER] = input[i].i2t_percent;
	q[i] = input[i].position_filtered;
	qp[i] = input[i].velocity_filtered;
  }
  m_Robot_Sensors.sensor_mft_enable_button_pressed=input_mft.enable_button_pressed;
  m_Robot_Sensors.sensor_mft_enable_button_panic=input_mft.enable_button_panic;
  m_Robot_Sensors.sensor_mft_application_button=input_mft.application_button_pressed;
  m_Robot_Sensors.RobotState=(int)robot1->getCollectiveState();
  m_Robot_Sensors.MotionEnabled=robot1->isMotionEnabled()?1.0:0.0;
  //Check if robot endeffector is within limits and stop if necessary
  m_Robot_Sensors.outside_workspace = robot1->CheckWorkspaceLimits(q, qp, m_Robot_Sensors.cartesian_position, m_Robot_Sensors.cartesian_orientation);
  memcpy(&m_Robot_Sensors.stop_event, robot1->getEvent(), sizeof(Event));
  //Enable or Disable robot according to current inputs
  motion_enable_logic.enableOrDisableRobot(robot1, &input_mft,
	  m_Robot_Inputs.MotionEnableRobot==1.0 || m_Robot_Inputs.MotionEnableLinearaxes==1.0,
	  m_Robot_Inputs.MotionDisableRobot!=0.0 || m_Robot_Inputs.MotionDisableLinearaxes!=0.0);
  //Transfer the read data to the fast controller
  if(m_spfast_sensor_motor_torque_feedback!=NULL) {
    for(int i= ROBOT_NUM_MOTORCONTROLLER;i<ROBOT_NUM_AXIS;i++) {
      (*m_spfast_sensor_motor_torque_feedback)[i- ROBOT_NUM_MOTORCONTROLLER]=input[i].motor_torque_feedback;
    }
  }
  if(m_spfast_sensor_position!=NULL) {
    for(int i= ROBOT_NUM_MOTORCONTROLLER;i<ROBOT_NUM_AXIS;i++) {
      (*m_spfast_sensor_position)[i- ROBOT_NUM_MOTORCONTROLLER]=input[i].position;
    }
  }
  if(m_spfast_sensor_torque!=NULL) {
    for(int i= ROBOT_NUM_MOTORCONTROLLER;i<ROBOT_NUM_AXIS;i++) {
      (*m_spfast_sensor_torque)[i- ROBOT_NUM_MOTORCONTROLLER]=input[i].torque;
    }
  }
  if (m_spfast_sensor_axis_force != NULL) {
	 for (int i = 0; i<ROBOT_NUM_MOTORCONTROLLER; i++) {
		 (*m_spfast_sensor_axis_force)[i] = input[i].force;
	 }
  }
  if (m_spfast_sensor_axis_position != NULL) {
	 for (int i = 0; i<ROBOT_NUM_MOTORCONTROLLER; i++) {
		 (*m_spfast_sensor_axis_position)[i] = input[i].position_linear;
	 }
  }
  if (m_spfast_sensor_axis_velocity != NULL) {
	  for (int i = 0; i<ROBOT_NUM_MOTORCONTROLLER; i++) {
		  (*m_spfast_sensor_axis_velocity)[i] = input[i].velocity;
	  }
  }

  //Call controller cyclic
  if(m_spControllerFastCyclic!=NULL) {
    m_spControllerFastCyclic->CycleUpdate(ipTask, ipCaller, context);
  }
  //Read outputs from fast controller and feed them to the robot
  mode_of_operation = (MotorcontrollerModeOfOperation)m_Robot_Inputs.ModeOfOperation;
  if(m_spfast_control_motor_torque!=NULL) {
    for(int i=ROBOT_NUM_MOTORCONTROLLER;i<ROBOT_NUM_AXIS;i++) {
      output[i].motor_torque=(*m_spfast_control_motor_torque)[i- ROBOT_NUM_MOTORCONTROLLER];
    }
  }
  else {
    //If none are availible, set them to invalid values (NaN).
    for(int i= ROBOT_NUM_MOTORCONTROLLER;i<ROBOT_NUM_AXIS;i++) {
      output[i].motor_torque=getnan_();
    }
  }

  if (m_spfast_control_axis_force != NULL) {
	 for (int i = 0; i<ROBOT_NUM_MOTORCONTROLLER; i++) {
		 output[i].motor_force = (*m_spfast_control_axis_force)[i];
	 }
  }
  else {
	 //If none are availible, set them to invalid values (NaN).
	 for (int i = 0; i<ROBOT_NUM_MOTORCONTROLLER; i++) {
		 output[i].motor_force = getnan_();
	 }
  }
  if (m_spfast_control_axis_position != NULL) {
	 for (int i = 0; i<ROBOT_NUM_MOTORCONTROLLER; i++) {
		 output[i].motor_position = (*m_spfast_control_axis_position)[i];
	 }
  }
  else {
	 //If none are availible, set them to invalid values (NaN).
	 for (int i = 0; i<ROBOT_NUM_MOTORCONTROLLER; i++) {
		 output[i].motor_position = getnan_();
	 }
  }
  if (m_spfast_control_axis_velocity != NULL) {
	 for (int i = 0; i<ROBOT_NUM_MOTORCONTROLLER; i++) {
		 output[i].motor_velocity = (*m_spfast_control_axis_velocity)[i];
	 }
  }
  else {
	 //If none are availible, set them to invalid values (NaN).
	 for (int i = 0; i<ROBOT_NUM_MOTORCONTROLLER; i++) {
		 output[i].motor_velocity = getnan_();
	 }
  }

  //If fast_control_motor_enable is connected, enable only those motors, which
  //have fast_control_motor_enable==1.0; All else are disabled.
  //If fast_control_motor_enable is not connected, always enable all motors.
  if (limits.is9DOF) {
	  if (m_spfast_control_axis_enable != NULL) {
		  output[0].motor_enable = (*m_spfast_control_axis_enable)[0] == 1.0;
		  output[1].motor_enable = (*m_spfast_control_axis_enable)[1] == 1.0;
	  }
	  else {
		  output[0].motor_enable = true;
		  output[1].motor_enable = true;
	  }
  }
  else {
	  output[0].motor_enable = false;
	  output[1].motor_enable = false;
  }
  if (m_spfast_control_motor_enable != NULL) {
	  for (int i = ROBOT_NUM_MOTORCONTROLLER; i < ROBOT_NUM_AXIS; i++) {
		  output[i].motor_enable = (*m_spfast_control_motor_enable)[i-ROBOT_NUM_MOTORCONTROLLER] == 1.0;
	  }
  }
  else {
	  for (int i = ROBOT_NUM_MOTORCONTROLLER; i < ROBOT_NUM_AXIS; i++) {
		  output[i].motor_enable = true;
	  }
  }
  //Write control outputs
  m_spTask->GetCurrentDcTime(&dc);
  dc_time_L=(DWORD)dc;
  robot1->WriteControl(input, output, mode_of_operation, dc_time_L);

	return hr;
}
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ImplementationOf_ITcPostCyclic">
HRESULT Ckuka_module::PostCyclicUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context)
{
  HRESULT hr=S_OK;

  if(m_spControllerFastPostCyclic) {
    m_spControllerFastPostCyclic->PostCyclicUpdate(ipTask, ipCaller, context);
  }

  return hr;
}
///</AutoGeneratedContent>

///////////////////////////////////////////////////////////////////////////////
HRESULT Ckuka_module::AddModuleToCaller()
{
	m_Trace.Log(tlVerbose, FENTERA);
	HRESULT hr = S_OK;
	if ( m_spCyclicCaller.HasOID() )
	{
		if ( SUCCEEDED_DBG(hr = m_spSrv->TcQuerySmartObjectInterface(m_spCyclicCaller)) )
		{
			if ( FAILED(hr = m_spCyclicCaller->AddModule(m_spCyclicCaller, THIS_CAST(ITcCyclic))) )
			{
				m_spCyclicCaller = NULL;
			}
		}
	}
	else
	{
		hr = ADS_E_INVALIDOBJID; 
		SUCCEEDED_DBGT(hr, "Invalid OID specified for cyclic caller task");
	}
  if(m_spPostCyclicCaller.HasOID()) {
    if(SUCCEEDED_DBG(hr=m_spSrv->TcQuerySmartObjectInterface(m_spPostCyclicCaller))) {
      if(FAILED(hr=m_spPostCyclicCaller->AddPostModule(m_spPostCyclicCaller, THIS_CAST(ITcPostCyclic)))) {
        m_spPostCyclicCaller=NULL;
      }
    }
  }
  else {
    hr=ADS_E_INVALIDOBJID;
    SUCCEEDED_DBGT(hr, "Invalid OID specified for postcyclic caller task");
  }

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
VOID Ckuka_module::RemoveModuleFromCaller()
{
	m_Trace.Log(tlVerbose, FENTERA);
	if ( m_spCyclicCaller )
	{
		m_spCyclicCaller->RemoveModule(m_spCyclicCaller);
	}
	m_spCyclicCaller	= NULL;
  if(m_spPostCyclicCaller) {
    m_spPostCyclicCaller->RemovePostModule(m_spPostCyclicCaller);
  }
  m_spPostCyclicCaller=NULL;
	m_Trace.Log(tlVerbose, FLEAVEA);
}

///////////////////////////////////////////////////////////////////////////////
HRESULT Ckuka_module::InitDataPointer() {
  m_Trace.Log(tlVerbose, FENTERA);

  HRESULT hr=S_OK;

  hr = FAILED(hr) ? hr : (m_spfast_control_motor_enable.HasOID() ? m_spfast_control_motor_enable.Init(m_spSrv) : hr);
  hr=FAILED(hr)?hr:(m_spfast_control_motor_torque.HasOID()?m_spfast_control_motor_torque.Init(m_spSrv):hr);
  hr=FAILED(hr)?hr:(m_spfast_sensor_motor_torque_feedback.HasOID()?m_spfast_sensor_motor_torque_feedback.Init(m_spSrv):hr);
  hr=FAILED(hr)?hr:(m_spfast_sensor_torque.HasOID()?m_spfast_sensor_torque.Init(m_spSrv):hr);
  hr=FAILED(hr)?hr:(m_spfast_sensor_position.HasOID()?m_spfast_sensor_position.Init(m_spSrv):hr);

  hr = FAILED(hr) ? hr : (m_spfast_control_axis_enable.HasOID() ? m_spfast_control_axis_enable.Init(m_spSrv) : hr);
  hr = FAILED(hr) ? hr : (m_spfast_control_axis_force.HasOID() ? m_spfast_control_axis_force.Init(m_spSrv) : hr);
  hr = FAILED(hr) ? hr : (m_spfast_control_axis_position.HasOID() ? m_spfast_control_axis_position.Init(m_spSrv) : hr);
  hr = FAILED(hr) ? hr : (m_spfast_control_axis_velocity.HasOID() ? m_spfast_control_axis_velocity.Init(m_spSrv) : hr);
  hr = FAILED(hr) ? hr : (m_spfast_sensor_axis_force.HasOID() ? m_spfast_sensor_axis_force.Init(m_spSrv) : hr);
  hr = FAILED(hr) ? hr : (m_spfast_sensor_axis_position.HasOID() ? m_spfast_sensor_axis_position.Init(m_spSrv) : hr);
  hr = FAILED(hr) ? hr : (m_spfast_sensor_axis_velocity.HasOID() ? m_spfast_sensor_axis_velocity.Init(m_spSrv) : hr);
    
  if(m_spfast_sensor_motor_torque_feedback!=NULL) {
    for(int i= ROBOT_NUM_MOTORCONTROLLER;i<ROBOT_NUM_AXIS;i++) {
      (*m_spfast_sensor_motor_torque_feedback)[i- ROBOT_NUM_MOTORCONTROLLER]=0.0;
    }
  }
  if(m_spfast_sensor_position!=NULL) {
    for(int i= ROBOT_NUM_MOTORCONTROLLER;i<ROBOT_NUM_AXIS;i++) {
      (*m_spfast_sensor_position)[i- ROBOT_NUM_MOTORCONTROLLER]=0.0;
    }
  }
  if(m_spfast_sensor_torque!=NULL) {
    for(int i= ROBOT_NUM_MOTORCONTROLLER;i<ROBOT_NUM_AXIS;i++) {
      (*m_spfast_sensor_torque)[i- ROBOT_NUM_MOTORCONTROLLER]=0.0;
    }
  }

  if (m_spfast_control_axis_force != NULL) {
	 for (int i = 0; i<ROBOT_NUM_MOTORCONTROLLER; i++) {
		 (*m_spfast_control_axis_force)[i] = 0.0;
	 }
  }
  if (m_spfast_control_axis_position != NULL) {
	 for (int i = 0; i<ROBOT_NUM_MOTORCONTROLLER; i++) {
		 (*m_spfast_control_axis_position)[i] = 0.0;
	 }
  }
  if (m_spfast_control_axis_velocity != NULL) {
	 for (int i = 0; i<ROBOT_NUM_MOTORCONTROLLER; i++) {
		 (*m_spfast_control_axis_velocity)[i] = 0.0;
	 }
  }
  if (m_spfast_sensor_axis_force != NULL) {
	 for (int i = 0; i<ROBOT_NUM_MOTORCONTROLLER; i++) {
		 (*m_spfast_sensor_axis_force)[i] = 0.0;
	 }
  }
  if (m_spfast_sensor_axis_position != NULL) {
	 for (int i = 0; i<ROBOT_NUM_MOTORCONTROLLER; i++) {
		 (*m_spfast_sensor_axis_position)[i] = 0.0;
	 }
  }
  if (m_spfast_sensor_axis_velocity != NULL) {
	 for (int i = 0; i<ROBOT_NUM_MOTORCONTROLLER; i++) {
		 (*m_spfast_sensor_axis_velocity)[i] = 0.0;
   }
  }

  m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
  return hr;
}

///////////////////////////////////////////////////////////////////////////////
VOID Ckuka_module::DeinitDataPointer() {
  m_Trace.Log(tlVerbose, FENTERA);

  m_spfast_control_motor_enable = NULL;
  m_spfast_control_motor_torque=NULL;
  m_spfast_sensor_motor_torque_feedback=NULL;
  m_spfast_sensor_torque=NULL;
  m_spfast_sensor_position=NULL;

  m_spfast_control_axis_enable = NULL;
  m_spfast_control_axis_force = NULL;
  m_spfast_control_axis_position = NULL;
  m_spfast_control_axis_velocity = NULL;
  m_spfast_sensor_axis_force = NULL;
  m_spfast_sensor_axis_position = NULL;
  m_spfast_sensor_axis_velocity = NULL;
}
