///////////////////////////////////////////////////////////////////////////////
// ArcLinAxisContr.h
#pragma once

#include "ArcLinAxisControlInterfaces.h"
#include "StateMachine.h"
#include <orc/OrcTypes.h>
#include <orc/robots/LinearAxis.h>

#include "TcFileAccessInterfaces.h"

#define ROBOT_ENABLE_COOLDOWN 1000*8

class CArcLinAxisContr 
	: public ITComObject
	, public ITcADI
	, public ITcWatchSource
///<AutoGeneratedContent id="InheritanceList">
	, public ITcCyclic
///</AutoGeneratedContent>
{
public:
	DECLARE_IUNKNOWN()
	DECLARE_IPERSIST_LIB()
	DECLARE_ITCOMOBJECT_LOCKOP()
	DECLARE_ITCADI()
	DECLARE_ITCWATCHSOURCE()
	DECLARE_OBJPARAWATCH_MAP()
	DECLARE_OBJDATAAREA_MAP()

	CArcLinAxisContr();
	virtual	~CArcLinAxisContr();


///<AutoGeneratedContent id="InterfaceMembers">
	// ITcCyclic
	virtual HRESULT TCOMAPI CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context);

///</AutoGeneratedContent>

protected:
	DECLARE_ITCOMOBJECT_SETSTATE();

	HRESULT AddModuleToCaller();
	VOID RemoveModuleFromCaller();

	HRESULT InitDataPointer();
	VOID DeinitDataPointer();

	// Tracing
	CTcTrace m_Trace;

///<AutoGeneratedContent id="Members">
	typedef _TCOM_SMARTDATAPTR<udp_msg> udp_msgDataPtr;

	TcTraceLevel m_TraceLevelMax;
	ModeOfOperation_e m_mode_of_operation;
	double m_Ts;
	STRING127 m_MujocoModelPath;
	ArcLinAxisContrInputs m_Inputs;
	ArcLinAxisContrOutputs m_Outputs;
	ArcLinAxisContrmotor_interface_in m_motor_interface_in;
	ArcLinAxisContrmotor_interface_out m_motor_interface_out;
	ITcCyclicCallerInfoPtr m_spCyclicCaller;
	udp_msgDataPtr m_spudp_tx_msg;
	udp_msgDataPtr m_spudp_rx_msg;
///</AutoGeneratedContent>

	// TODO: Custom variable
	ULONG TaskCycleTime = 0; // cycle time in ns 
	orc::Time Ts;
	orc::Time t;

	orc::robots::LinearAxis* arc_contr_ptr;
	orc::logic::StateMachine* state_machine_ptr;

	using JointVector = orc::robots::LinearAxis::JointVector;
	using JointArray = orc::robots::LinearAxis::JointArray;
	using JacobianMatrix = orc::robots::LinearAxis::JacobianMatrix;

	// File access helper functions
	ITcFileAccessPtr m_spFileAccess;
	// Setting the model_binary type to unsigned char, leads to correct representation of the data
	// when compared to the hex editor of Notepad++.
	PUCHAR model_binary;
	UINT model_size;
	HRESULT readBinaryModel(PCCH fileName);
};
