///////////////////////////////////////////////////////////////////////////////
// ArcLinAxisControlInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "ArcLinAxisControlServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
