///////////////////////////////////////////////////////////////////////////////
// ArcLinAxisContr.cpp
#include "TcPch.h"
#pragma hdrstop

#include "ArcLinAxisContr.h"
#include "ArcLinAxisControlVersion.h"
#include "orc/robots/LinearAxis.h"
#include "orc/com/TcServerUtil.h"

#include <mujoco_tc/mujoco_tc.h>
#include <mujoco_tc/engine_util_misc_tc.h>
#include <mujoco_tc/engine_io_tc.h>

#ifdef _DEBUG
#define new DEBUG_NEW
#endif
DEFINE_THIS_FILE()

///////////////////////////////////////////////////////////////////////////////
// CArcLinAxisContr
///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////
// Collection of interfaces implemented by module CArcLinAxisContr
BEGIN_INTERFACE_MAP(CArcLinAxisContr)
	INTERFACE_ENTRY_ITCOMOBJECT()
	INTERFACE_ENTRY(IID_ITcADI, ITcADI)
	INTERFACE_ENTRY(IID_ITcWatchSource, ITcWatchSource)
///<AutoGeneratedContent id="InterfaceMap">
	INTERFACE_ENTRY(IID_ITcCyclic, ITcCyclic)
///</AutoGeneratedContent>
END_INTERFACE_MAP()

IMPLEMENT_IPERSIST_LIB(CArcLinAxisContr, VID_ArcLinAxisControl, CID_ArcLinAxisControlCArcLinAxisContr)
IMPLEMENT_ITCOMOBJECT(CArcLinAxisContr)
IMPLEMENT_ITCOMOBJECT_SETSTATE_LOCKOP2(CArcLinAxisContr)
IMPLEMENT_ITCADI(CArcLinAxisContr)
IMPLEMENT_ITCWATCHSOURCE(CArcLinAxisContr)


///////////////////////////////////////////////////////////////////////////////
// Set parameters of CArcLinAxisContr 
BEGIN_SETOBJPARA_MAP(CArcLinAxisContr)
	SETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="SetObjectParameterMap">
	SETOBJPARA_VALUE(PID_TcTraceLevel, m_TraceLevelMax)
	SETOBJPARA_VALUE(PID_ArcLinAxisContrmode_of_operation, m_mode_of_operation)
	SETOBJPARA_VALUE(PID_ArcLinAxisContrTs, m_Ts)
	SETOBJPARA_VALUE(PID_ArcLinAxisContrMujocoModelPath, m_MujocoModelPath)
	SETOBJPARA_ITFPTR(PID_Ctx_TaskOid, m_spCyclicCaller)
	SETOBJPARA_DATAPTR(PID_ArcLinAxisContrudp_tx_msg, m_spudp_tx_msg)
	SETOBJPARA_DATAPTR(PID_ArcLinAxisContrudp_rx_msg, m_spudp_rx_msg)
///</AutoGeneratedContent>
END_SETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get parameters of CArcLinAxisContr 
BEGIN_GETOBJPARA_MAP(CArcLinAxisContr)
	GETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="GetObjectParameterMap">
	GETOBJPARA_VALUE(PID_TcTraceLevel, m_TraceLevelMax)
	GETOBJPARA_VALUE(PID_ArcLinAxisContrmode_of_operation, m_mode_of_operation)
	GETOBJPARA_VALUE(PID_ArcLinAxisContrTs, m_Ts)
	GETOBJPARA_VALUE(PID_ArcLinAxisContrMujocoModelPath, m_MujocoModelPath)
	GETOBJPARA_ITFPTR(PID_Ctx_TaskOid, m_spCyclicCaller)
///</AutoGeneratedContent>
END_GETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get watch entries of CArcLinAxisContr
BEGIN_OBJPARAWATCH_MAP(CArcLinAxisContr)
	OBJPARAWATCH_DATAAREA_MAP()
///<AutoGeneratedContent id="ObjectParameterWatchMap">
///</AutoGeneratedContent>
END_OBJPARAWATCH_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get data area members of CArcLinAxisContr
BEGIN_OBJDATAAREA_MAP(CArcLinAxisContr)
///<AutoGeneratedContent id="ObjectDataAreaMap">
	OBJDATAAREA_VALUE(ADI_ArcLinAxisContrInputs, m_Inputs)
	OBJDATAAREA_VALUE(ADI_ArcLinAxisContrOutputs, m_Outputs)
	OBJDATAAREA_VALUE(ADI_ArcLinAxisContrmotor_interface_in, m_motor_interface_in)
	OBJDATAAREA_VALUE(ADI_ArcLinAxisContrmotor_interface_out, m_motor_interface_out)
///</AutoGeneratedContent>
END_OBJDATAAREA_MAP()


///////////////////////////////////////////////////////////////////////////////
CArcLinAxisContr::CArcLinAxisContr()
	: m_Trace(m_TraceLevelMax, m_spSrv)
	, t(0.0)
	, Ts(0.0)
	/*, arc_contr_param()*/
	, arc_contr_ptr(NULL)
{
///<AutoGeneratedContent id="MemberInitialization">
	m_TraceLevelMax = tlAlways;
	m_mode_of_operation = Stop;
	m_Ts = 0;
	memset(&m_MujocoModelPath, 0, sizeof(m_MujocoModelPath));
	memset(&m_Inputs, 0, sizeof(m_Inputs));
	memset(&m_Outputs, 0, sizeof(m_Outputs));
	memset(&m_motor_interface_in, 0, sizeof(m_motor_interface_in));
	memset(&m_motor_interface_out, 0, sizeof(m_motor_interface_out));
///</AutoGeneratedContent>
}

///////////////////////////////////////////////////////////////////////////////
CArcLinAxisContr::~CArcLinAxisContr() 
{
}


///////////////////////////////////////////////////////////////////////////////
// State Transitions 
///////////////////////////////////////////////////////////////////////////////
IMPLEMENT_ITCOMOBJECT_SETOBJSTATE_IP_PI(CArcLinAxisContr)

///////////////////////////////////////////////////////////////////////////////
// State transition from PREOP to SAFEOP
//
// Initialize input parameters 
// Allocate memory
HRESULT CArcLinAxisContr::SetObjStatePS(PTComInitDataHdr pInitData)
{
	m_Trace.Log(tlVerbose, FENTERA);
	HRESULT hr = S_OK;
	IMPLEMENT_ITCOMOBJECT_EVALUATE_INITDATA(pInitData);

	// ------------------- READ IN MUJOCO FILE -------------	
	// Create file access instance
	hr = m_spSrv->TcCreateInstance(CID_TcFileAccess, IID_ITcFileAccess, (PPVOID)(&m_spFileAccess));

	// Choose mjb file as per TwinCAT parameters
	std::string model_path = "C:\\TwinCAT\\3.1\\Boot\\";
	model_path.append(m_MujocoModelPath);
	strcpy(m_Outputs.model_path, model_path.c_str());

	if (SUCCEEDED(hr)) {
		ITComObjectPtr spFileAccessObj = m_spFileAccess;
		hr = spFileAccessObj->TcSetObjState(TCOM_STATE_PREOP, m_spSrv, pInitData);
		if (SUCCEEDED(hr)) {
			// read Mujoco binary file from _Boot directory
			m_Trace.Log(tlVerbose, FENTERA "Reading MJB file!");
			hr = readBinaryModel(model_path.c_str());
		}
	}
	// ------------------- MUJOCO END ----------------------

	orc::log::start_logging_twincat(m_TraceLevelMax, &m_Trace);
	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to OP
//
// Register with other TwinCAT objects
HRESULT CArcLinAxisContr::SetObjStateSO()
{
	m_Trace.Log(tlVerbose, FENTERA);
	HRESULT hr = S_OK;

	// TODO: Add any additional initialization
	// Initialize data pointer 
	hr = FAILED(hr) ? hr : InitDataPointer();

	// current time
	t = 0.0;

	// read cycle time from TcCom Module Parameter
	Ts = m_Ts;
	m_Trace.Log(tlAlways, FLEAVEA "Cycle Time Ts = %f", Ts);

	using namespace orc::robots;
	using JointArray = LinearAxis::JointArray;
	using JointVector = LinearAxis::JointVector;
	using JointMatrix = LinearAxis::JointMatrix;

	// set controller parameter
	JointMatrix K0 = (JointVector::Ones() * 25.).asDiagonal();

	state_machine_ptr = new orc::logic::StateMachine(&m_Trace);

	// create instances
	m_Trace.Log(tlAlways, FLEAVEA "Init Linear Axis Controller");
	arc_contr_ptr = new LinearAxis((unsigned char*)model_binary, model_size, Ts, m_Trace, K0);
	if (arc_contr_ptr->model->nq != LinearAxis::DOF) {
		m_Trace.Log(tlError, "DOF of model does not match DOF of linear axis!");
		return EXIT_FAILURE;
	}

	// If following call is successful the CycleUpdate method will be called, 
	// possibly even before method has been left.
	hr = FAILED(hr) ? hr : AddModuleToCaller(); 

	// Cleanup if transition failed at some stage
	if ( FAILED(hr) )
	{
		RemoveModuleFromCaller(); 
	}

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from OP to SAFEOP
HRESULT CArcLinAxisContr::SetObjStateOS()
{
	m_Trace.Log(tlVerbose, FENTERA);

	HRESULT hr = S_OK;

	RemoveModuleFromCaller(); 

	// TODO: Add any additional deinitialization
	DeinitDataPointer();
	delete arc_contr_ptr;
	delete state_machine_ptr;
	delete model_binary;

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to PREOP
HRESULT CArcLinAxisContr::SetObjStateSP()
{
	HRESULT hr = S_OK;
	m_Trace.Log(tlVerbose, FENTERA);

	// TODO: Add deinitialization code

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///<AutoGeneratedContent id="ImplementationOf_ITcCyclic">
HRESULT CArcLinAxisContr::CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context)
{
	HRESULT hr = S_OK;

	/* Timing */
	hr = FAILED(hr) ? hr : ipTask->GetCycleTime(&TaskCycleTime);
	Ts = ((double)TaskCycleTime) / ((double)1e9);

	// current time
	t += Ts;

	/* UDP input*/

	if (m_spudp_rx_msg != NULL) {
		if (m_spudp_rx_msg->request) {
			m_spudp_rx_msg->request = false;
			orc::com::handle_receive(*arc_contr_ptr, &(m_spudp_rx_msg->data[0]), m_spudp_rx_msg->size);
		}
	}

	/* Control runs */
	/* Robot Control */

	// read inputs
	JointVector q_act(m_motor_interface_in.position_act.Values);
	JointVector q_dot_act(m_motor_interface_in.velocity_act.Values);
	JointVector tau_motor_act(m_motor_interface_in.force_act.Values);
	
	state_machine_ptr->run(m_motor_interface_in.motion_enabled,
		m_Inputs.auto_enable,
		m_Inputs.enable,
		m_Inputs.disable);

	// run controller
	JointVector vel_set;
	if (state_machine_ptr->is_enable_transition()) {
		orc::Time T_traj = 1.0;
		JointVector q_end = q_act;
		arc_contr_ptr->start(t, q_act, q_end, T_traj);
		m_Trace.Log(tlInfo, FLEAVEA "arc_contr->start() executed!", hr);
	}
	if (state_machine_ptr->get_state() == orc::logic::RobotStatus::ENABLE) {
		// select desired torque based on state
		arc_contr_ptr->set_q_act(q_act);
		if (arc_contr_ptr->update(t))
			vel_set = arc_contr_ptr->get_tau_act();
		else
			return EXIT_FAILURE;
	}
	else {
		vel_set = JointVector::Zero();
	}
	
	// robot interface outputs
	// force setpoint is unused
	JointVector::Map(m_motor_interface_out.force_set.Values) = JointVector::Zero();
	JointVector::Map(m_motor_interface_out.velocity_set.Values) = vel_set;
	JointVector::Map(m_motor_interface_out.position_set.Values) = arc_contr_ptr->get_q_set();
	m_motor_interface_out.mode_of_operation = ModeOfOperation_e::Velocity;
	m_motor_interface_out.motion_enable = 0.0;
	m_motor_interface_out.motion_disable = 0.0;
	if (state_machine_ptr->is_disable_transition()) {
		m_motor_interface_out.motion_disable = 1.0;
	}
	else if (state_machine_ptr->is_enable_transition()) {
		m_motor_interface_out.motion_enable = 1.0;
	}
	// robot interface works with double: convert bool to double
	double motor_enable = m_Inputs.auto_enable ? 1.0 : 0.0;
	m_motor_interface_out.motor_enable.Values[0] = motor_enable;
	m_motor_interface_out.motor_enable.Values[1] = motor_enable;

	/* UDP output */
	if (m_spudp_tx_msg != NULL) {
		m_spudp_tx_msg->request = true;
		auto msg_size = orc::com::send_robot_data(*arc_contr_ptr, t, state_machine_ptr->get_state(), m_spudp_tx_msg->data, sizeof(m_spudp_tx_msg->data));
		m_spudp_tx_msg->size = msg_size;
	}

	/* set outputs */

	// actual values
	JointVector::Map(m_Outputs.q_act.Values) = arc_contr_ptr->get_q_act();
	JointVector::Map(m_Outputs.q_dot_act.Values) = arc_contr_ptr->get_q_dot_act();

	// Jointspace setpoints
	JointVector::Map(m_Outputs.q_set.Values) = arc_contr_ptr->get_q_set();
	JointVector::Map(m_Outputs.q_dot_set.Values) = arc_contr_ptr->get_q_dot_set();
	JointVector::Map(m_Outputs.q_dotdot_set.Values) = arc_contr_ptr->get_q_dotdot_set();

	// control error
	JointVector::Map(m_Outputs.e_jointspace.Values) = arc_contr_ptr->get_joint_error();

	// torque setpoint
	JointVector::Map(m_Outputs.tau_set.Values) = arc_contr_ptr->get_tau_act();

	return hr;
}
///</AutoGeneratedContent>

///////////////////////////////////////////////////////////////////////////////
HRESULT CArcLinAxisContr::AddModuleToCaller()
{
	m_Trace.Log(tlVerbose, FENTERA);

	HRESULT hr = S_OK;
	if ( m_spCyclicCaller.HasOID() )
	{
		if ( SUCCEEDED_DBG(hr = m_spSrv->TcQuerySmartObjectInterface(m_spCyclicCaller)) )
		{
			if ( FAILED(hr = m_spCyclicCaller->AddModule(m_spCyclicCaller, THIS_CAST(ITcCyclic))) )
			{
				m_spCyclicCaller = NULL;
			}
		}
	}
	else
	{
		hr = ADS_E_INVALIDOBJID; 
		SUCCEEDED_DBGT(hr, "Invalid OID specified for caller task");
	}

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
VOID CArcLinAxisContr::RemoveModuleFromCaller()
{
	m_Trace.Log(tlVerbose, FENTERA);

	if ( m_spCyclicCaller )
	{
		m_spCyclicCaller->RemoveModule(m_spCyclicCaller);
	}
	m_spCyclicCaller	= NULL;

	m_Trace.Log(tlVerbose, FLEAVEA);
}

///////////////////////////////////////////////////////////////////////////////
HRESULT CArcLinAxisContr::InitDataPointer()
{
	m_Trace.Log(tlVerbose, FENTERA);

	HRESULT hr = S_OK;
	hr = FAILED(hr) ? hr : m_spudp_rx_msg.Init(m_spSrv);
	hr = FAILED(hr) ? hr : m_spudp_tx_msg.Init(m_spSrv);

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
VOID CArcLinAxisContr::DeinitDataPointer()
{
	m_Trace.Log(tlVerbose, FENTERA);

	m_spudp_rx_msg = NULL;
	m_spudp_tx_msg = NULL;

	m_Trace.Log(tlVerbose, FLEAVEA);
}


// Reads the binary file and stores its contents into CArcController::model_binary
HRESULT CArcLinAxisContr::readBinaryModel(PCCH fileName)
{
	HRESULT hr = S_OK;
	m_Trace.Log(tlVerbose, FENTERA);

	// get file size to allocate space for model_binary variable in which model will be saved
	TcFileStatus FileStatus = { 0 };
	hr = m_spFileAccess->FileGetStatus(fileName, &FileStatus);
	ULONGLONG cbData = 0;
	if (SUCCEEDED(hr)) {
		m_Trace.Log(tlVerbose, FENTERA "Model size: %i", FileStatus.ulFileSize);
		if (FileStatus.ulFileSize >= UINT_MAX) {
			m_Trace.Log(tlVerbose, FENTERA "MJB file size too large!");
			return E_ABORT;
		}
		model_size = static_cast<UINT>(FileStatus.ulFileSize);
		// model_binary is allocated on the heap as its size is a priori not known, and deleted in SetObjStateOS()
		model_binary = new UCHAR[model_size];
	}
	else {
		m_Trace.Log(tlAlways, FLEAVEA "Error while reading file!");
		return hr;
	}

	// open file
	TcFileHandle hFile = NULL;
	hr = m_spFileAccess->FileOpen(fileName, static_cast<TcFileAccessMode>(amBinary | amRead), &hFile);

	if (SUCCEEDED(hr)) {
		// read file
		UINT pcbRead = 0;
		hr = m_spFileAccess->FileRead(hFile, model_binary, model_size, &pcbRead);
	}

	// close file
	hr = m_spFileAccess->FileClose(hFile);
	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}
