///////////////////////////////////////////////////////////////////////////////
// ArcLinAxisControlClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "ArcLinAxisControlClassFactory.h"
#include "ArcLinAxisControlServices.h"
#include "ArcLinAxisControlVersion.h"
#include "ArcLinAxisContr.h"

BEGIN_CLASS_MAP(CArcLinAxisControlClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY_LIB(VID_ArcLinAxisControl, CID_ArcLinAxisControlCArcLinAxisContr, SRVNAME_ARCLINAXISCONTROL "!CArcLinAxisContr", CArcLinAxisContr)
///</AutoGeneratedContent>
END_CLASS_MAP()

CArcLinAxisControlClassFactory::CArcLinAxisControlClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME_TMX(SRVNAME_ARCLINAXISCONTROL));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(ArcLinAxisControl));
#endif //defined(TCDBG_UNIT_VERSION)
}

