///////////////////////////////////////////////////////////////////////////////
// ArcLinAxisControlServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_ArcLinAxisControl = 0x3F000000;
#define SRVNAME_ARCLINAXISCONTROL "ArcLinAxisControl"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_ArcLinAxisControlCArcLinAxisContr = {0x3352bf5b,0x5895,0x4a40,{0x9a,0x89,0xe3,0x83,0xd9,0x69,0x07,0xe8}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_ArcLinAxisContrmode_of_operation = 0x00000001;
const PTCID PID_ArcLinAxisContrTs = 0x00000004;
const PTCID PID_ArcLinAxisContrMujocoModelPath = 0x00000005;
const PTCID PID_ArcLinAxisContrudp_tx_msg = 0x00000002;
const PTCID PID_ArcLinAxisContrudp_rx_msg = 0x00000003;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
#if !defined(_TC_TYPE_A546B7AC_861C_4456_87F1_845572578330_INCLUDED_)
#define _TC_TYPE_A546B7AC_861C_4456_87F1_845572578330_INCLUDED_
typedef struct _linaxis_t
{
	double Values[2];
} linaxis_t, *Plinaxis_t;
#endif // !defined(_TC_TYPE_A546B7AC_861C_4456_87F1_845572578330_INCLUDED_)

#if !defined(_TC_TYPE_A310A946_D536_4A8A_9C58_A521C053E0BD_INCLUDED_)
#define _TC_TYPE_A310A946_D536_4A8A_9C58_A521C053E0BD_INCLUDED_
#pragma pack(push,1)
typedef struct _udp_msg
{
	bool request;
	USHORT size;
	BYTE data[1472];
} udp_msg, *Pudp_msg;
#pragma pack(pop)
#endif // !defined(_TC_TYPE_A310A946_D536_4A8A_9C58_A521C053E0BD_INCLUDED_)

#if !defined(_TC_TYPE_7081F11C_23FB_4BBB_A810_166A40CF032A_INCLUDED_)
#define _TC_TYPE_7081F11C_23FB_4BBB_A810_166A40CF032A_INCLUDED_
typedef struct _Vec2D
{
	double x;
	double y;
} Vec2D, *PVec2D;
#endif // !defined(_TC_TYPE_7081F11C_23FB_4BBB_A810_166A40CF032A_INCLUDED_)

#if !defined(_TC_TYPE_27EDEB22_D66A_44FB_9B83_67FEFD6FEF17_INCLUDED_)
#define _TC_TYPE_27EDEB22_D66A_44FB_9B83_67FEFD6FEF17_INCLUDED_
enum ModeOfOperation_e : SHORT {
	Stop = 0,
	Position = 8,
	Velocity = 9,
	Force = 10
};
#endif // !defined(_TC_TYPE_27EDEB22_D66A_44FB_9B83_67FEFD6FEF17_INCLUDED_)

#if !defined(_TC_TYPE_18071995_0000_0000_0000_00010000007F_INCLUDED_)
#define _TC_TYPE_18071995_0000_0000_0000_00010000007F_INCLUDED_
typedef CHAR STRING127[128];
#endif // !defined(_TC_TYPE_18071995_0000_0000_0000_00010000007F_INCLUDED_)

#pragma pack(push,1)
typedef struct _ArcLinAxisContrInputs
{
	bool enable;
	bool disable;
	bool auto_enable;
} ArcLinAxisContrInputs, *PArcLinAxisContrInputs;
#pragma pack(pop)

#if !defined(_TC_TYPE_18071995_0000_0000_0000_0001000000FF_INCLUDED_)
#define _TC_TYPE_18071995_0000_0000_0000_0001000000FF_INCLUDED_
typedef CHAR STRING255[256];
#endif // !defined(_TC_TYPE_18071995_0000_0000_0000_0001000000FF_INCLUDED_)

typedef struct _ArcLinAxisContrOutputs
{
	linaxis_t q_act;
	linaxis_t q_dot_act;
	linaxis_t q_set;
	linaxis_t q_dot_set;
	linaxis_t q_dotdot_set;
	linaxis_t e_jointspace;
	linaxis_t tau_set;
	STRING255 model_path;
} ArcLinAxisContrOutputs, *PArcLinAxisContrOutputs;

typedef struct _ArcLinAxisContrmotor_interface_in
{
	linaxis_t force_act;
	linaxis_t position_act;
	linaxis_t velocity_act;
	double motion_enabled;
} ArcLinAxisContrmotor_interface_in, *PArcLinAxisContrmotor_interface_in;

#pragma pack(push,1)
typedef struct _ArcLinAxisContrmotor_interface_out
{
	unsigned char mode_of_operation;
	double motion_enable;
	double motion_disable;
	linaxis_t force_set;
	linaxis_t position_set;
	linaxis_t velocity_set;
	linaxis_t motor_enable;
} ArcLinAxisContrmotor_interface_out, *PArcLinAxisContrmotor_interface_out;
#pragma pack(pop)

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_ArcLinAxisContrInputs 3
#define ADI_ArcLinAxisContrOutputs 4
#define ADI_ArcLinAxisContrmotor_interface_in 0
#define ADI_ArcLinAxisContrmotor_interface_out 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
