///////////////////////////////////////////////////////////////////////////////
// UdpInterface.h
#pragma once

#include "UdpInterfaceInterfaces.h"

constexpr int MSG_BUFFER_LEN = 100;

class CUdpInterface 
	: public ITComObject
	, public ITcADI
	, public ITcWatchSource
///<AutoGeneratedContent id="InheritanceList">
	, public ITcCyclic
	, public ITcIoUdpProtocolRecv
///</AutoGeneratedContent>
{
public:
	DECLARE_IUNKNOWN()
	DECLARE_IPERSIST(CID_UdpInterfaceCUdpInterface)
	DECLARE_ITCOMOBJECT_LOCKOP()
	DECLARE_ITCADI()
	DECLARE_ITCWATCHSOURCE()
	DECLARE_OBJPARAWATCH_MAP()
	DECLARE_OBJDATAAREA_MAP()

	CUdpInterface();
	virtual	~CUdpInterface();


///<AutoGeneratedContent id="InterfaceMembers">
	// ITcCyclic
	virtual HRESULT TCOMAPI CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context);

	// ITcIoUdpProtocolRecv
	virtual HRESULT TCOMAPI ReceiveData(ULONG ipAddr, USHORT udpDestPort, USHORT udpSrcPort, ULONG nData, PVOID pData, ETYPE_VLAN_HEADER* pVlan=0);

///</AutoGeneratedContent>

protected:
	DECLARE_ITCOMOBJECT_SETSTATE();

	HRESULT AddModuleToCaller();
	VOID RemoveModuleFromCaller();

	// Tracing
	CTcTrace m_Trace;

///<AutoGeneratedContent id="Members">
	TcTraceLevel m_TraceLevelMax;
	IPADDR m_client_ip_addr;
	UdpInterfaceIiwa_Inputs m_Iiwa_Inputs;
	UdpInterfaceIiwa_Outputs m_Iiwa_Outputs;
	UdpInterfaceIiwa_Sil_Input m_Iiwa_Sil_Input;
	UdpInterfaceIiwa_Sil_Output m_Iiwa_Sil_Output;
	UdpInterfaceLinAxis_Inputs m_LinAxis_Inputs;
	UdpInterfaceLinAxis_Outputs m_LinAxis_Outputs;
	UdpInterfaceLinAxis_Sil_Input m_LinAxis_Sil_Input;
	UdpInterfaceLinAxis_Sil_Output m_LinAxis_Sil_Output;
	ITcCyclicCallerInfoPtr m_spCyclicCaller;
	ITcIoUdpProtocolPtr m_spUdpProt;
///</AutoGeneratedContent>

	// TODO: Custom variable
	ULONG client_ipaddr;
	
	udp_msg iiwa_msg_buffer[MSG_BUFFER_LEN];
	int iiwa_buf_write_index = -1;
	int iiwa_buf_read_index = -1;

	udp_msg linax_msg_buffer[MSG_BUFFER_LEN];
	int linax_buf_write_index = -1;
	int linax_buf_read_index = -1;
};
