///////////////////////////////////////////////////////////////////////////////
// UdpInterfaceClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "UdpInterfaceClassFactory.h"
#include "UdpInterfaceServices.h"
#include "UdpInterfaceVersion.h"
#include "UdpInterface.h"

BEGIN_CLASS_MAP(CUdpInterfaceClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY(CID_UdpInterfaceCUdpInterface, SRVNAME_UDPINTERFACE "!CUdpInterface", CUdpInterface)
///</AutoGeneratedContent>
END_CLASS_MAP()

CUdpInterfaceClassFactory::CUdpInterfaceClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_UDPINTERFACE)); 
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(UdpInterface));
#endif //defined(TCDBG_UNIT_VERSION)
}

