///////////////////////////////////////////////////////////////////////////////
// UdpInterface.cpp
#include "TcPch.h"
#pragma hdrstop

#include <cmath>
#include "UdpInterface.h"
#include <orc/com/com_settings.h>
#include <orc/robots/Iiwa.h>
#include <orc/robots/LinearAxis.h>

#ifdef _DEBUG
#define new DEBUG_NEW
#endif
DEFINE_THIS_FILE()

///////////////////////////////////////////////////////////////////////////////
// CUdpInterface
///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////
// Collection of interfaces implemented by module CUdpInterface
BEGIN_INTERFACE_MAP(CUdpInterface)
	INTERFACE_ENTRY_ITCOMOBJECT()
	INTERFACE_ENTRY(IID_ITcADI, ITcADI)
	INTERFACE_ENTRY(IID_ITcWatchSource, ITcWatchSource)
///<AutoGeneratedContent id="InterfaceMap">
	INTERFACE_ENTRY(IID_ITcCyclic, ITcCyclic)
	INTERFACE_ENTRY(IID_ITcIoUdpProtocolRecv, ITcIoUdpProtocolRecv)
///</AutoGeneratedContent>
END_INTERFACE_MAP()

IMPLEMENT_ITCOMOBJECT(CUdpInterface)
IMPLEMENT_ITCOMOBJECT_SETSTATE_LOCKOP2(CUdpInterface)
IMPLEMENT_ITCADI(CUdpInterface)
IMPLEMENT_ITCWATCHSOURCE(CUdpInterface)

///////////////////////////////////////////////////////////////////////////////
// Set parameters of CUdpInterface 
BEGIN_SETOBJPARA_MAP(CUdpInterface)
	SETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="SetObjectParameterMap">
	SETOBJPARA_VALUE(PID_TcTraceLevel, m_TraceLevelMax)
	SETOBJPARA_VALUE(PID_UdpInterfaceclient_ip_addr, m_client_ip_addr)
	SETOBJPARA_ITFPTR(PID_Ctx_TaskOid, m_spCyclicCaller)
	SETOBJPARA_ITFPTR(PID_UdpInterfaceUdpProt, m_spUdpProt)
///</AutoGeneratedContent>
END_SETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get parameters of CUdpInterface 
BEGIN_GETOBJPARA_MAP(CUdpInterface)
	GETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="GetObjectParameterMap">
	GETOBJPARA_VALUE(PID_TcTraceLevel, m_TraceLevelMax)
	GETOBJPARA_VALUE(PID_UdpInterfaceclient_ip_addr, m_client_ip_addr)
	GETOBJPARA_ITFPTR(PID_Ctx_TaskOid, m_spCyclicCaller)
	GETOBJPARA_ITFPTR(PID_UdpInterfaceUdpProt, m_spUdpProt)
///</AutoGeneratedContent>
END_GETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get watch entries of CUdpInterface
BEGIN_OBJPARAWATCH_MAP(CUdpInterface)
	OBJPARAWATCH_DATAAREA_MAP()
///<AutoGeneratedContent id="ObjectParameterWatchMap">
	OBJPARAWATCH_VALUE(PID_UdpInterfaceclient_ip_addr, m_client_ip_addr)
///</AutoGeneratedContent>
END_OBJPARAWATCH_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get data area members of CUdpInterface
BEGIN_OBJDATAAREA_MAP(CUdpInterface)
///<AutoGeneratedContent id="ObjectDataAreaMap">
	OBJDATAAREA_VALUE(ADI_UdpInterfaceIiwa_Inputs, m_Iiwa_Inputs)
	OBJDATAAREA_VALUE(ADI_UdpInterfaceIiwa_Outputs, m_Iiwa_Outputs)
	OBJDATAAREA_VALUE(ADI_UdpInterfaceIiwa_Sil_Input, m_Iiwa_Sil_Input)
	OBJDATAAREA_VALUE(ADI_UdpInterfaceIiwa_Sil_Output, m_Iiwa_Sil_Output)
	OBJDATAAREA_VALUE(ADI_UdpInterfaceLinAxis_Inputs, m_LinAxis_Inputs)
	OBJDATAAREA_VALUE(ADI_UdpInterfaceLinAxis_Outputs, m_LinAxis_Outputs)
	OBJDATAAREA_VALUE(ADI_UdpInterfaceLinAxis_Sil_Input, m_LinAxis_Sil_Input)
	OBJDATAAREA_VALUE(ADI_UdpInterfaceLinAxis_Sil_Output, m_LinAxis_Sil_Output)
///</AutoGeneratedContent>
END_OBJDATAAREA_MAP()


///////////////////////////////////////////////////////////////////////////////
CUdpInterface::CUdpInterface()
	: m_Trace(m_TraceLevelMax, m_spSrv)
	, m_TraceLevelMax(tlAlways)
{
	memset(&m_Iiwa_Inputs, 0, sizeof(m_Iiwa_Inputs));
	memset(&m_Iiwa_Outputs, 0, sizeof(m_Iiwa_Outputs));
	memset(&m_Iiwa_Sil_Input, 0, sizeof(m_Iiwa_Sil_Input));
	memset(&m_Iiwa_Sil_Output, 0, sizeof(m_Iiwa_Sil_Output));

	memset(&m_LinAxis_Inputs, 0, sizeof(m_LinAxis_Inputs));
	memset(&m_LinAxis_Outputs, 0, sizeof(m_LinAxis_Outputs));
	memset(&m_LinAxis_Sil_Input, 0, sizeof(m_LinAxis_Sil_Input));
	memset(&m_LinAxis_Sil_Output, 0, sizeof(m_LinAxis_Sil_Output));

	// set default ip addr
	client_ipaddr = 0;
	client_ipaddr += static_cast<ULONG>(192) << 24;
	client_ipaddr += static_cast<ULONG>(168) << 16;
	client_ipaddr += static_cast<ULONG>(1) << 8;
	client_ipaddr += static_cast<ULONG>(3);
}

///////////////////////////////////////////////////////////////////////////////
CUdpInterface::~CUdpInterface() 
{
}


///////////////////////////////////////////////////////////////////////////////
// State Transitions 
///////////////////////////////////////////////////////////////////////////////
IMPLEMENT_ITCOMOBJECT_SETOBJSTATE_IP_PI(CUdpInterface)

///////////////////////////////////////////////////////////////////////////////
// State transition from PREOP to SAFEOP
//
// Initialize input parameters 
// Allocate memory
HRESULT CUdpInterface::SetObjStatePS(PTComInitDataHdr pInitData)
{
	m_Trace.Log(tlVerbose, FENTERA);

	HRESULT hr = S_OK;
	IMPLEMENT_ITCOMOBJECT_EVALUATE_INITDATA(pInitData);

	client_ipaddr = 0;
	client_ipaddr += static_cast<ULONG>(m_client_ip_addr[3]) << 24;
	client_ipaddr += static_cast<ULONG>(m_client_ip_addr[2]) << 16;
	client_ipaddr += static_cast<ULONG>(m_client_ip_addr[1]) << 8;
	client_ipaddr += static_cast<ULONG>(m_client_ip_addr[0]);

	m_Trace.Log(tlInfo, FLEAVEA "Client IP: %d.%d.%d.%d", m_client_ip_addr[3], m_client_ip_addr[2], m_client_ip_addr[1], m_client_ip_addr[0]);
	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to OP
//
// Register with other TwinCAT objects
HRESULT CUdpInterface::SetObjStateSO()
{
	m_Trace.Log(tlVerbose, FENTERA);
	HRESULT hr = S_OK;

	// register Trajectory Udp Receiver
	if (SUCCEEDED(hr) && m_spUdpProt.HasOID())
	{
		m_Trace.Log(tlInfo, FLEAVEA "Register UdpProt");
		if (SUCCEEDED_DBG(hr = m_spSrv->TcQuerySmartObjectInterface(m_spUdpProt)))
		{	
			/* Iiwa */
			// SIL port
			m_Trace.Log(tlInfo, FLEAVEA "Iiwa SIL Server: Listen to UDP Port: %d", orc::robots::Iiwa::SIL_CONTROLLER_PORT);
			if (FAILED(hr = m_spUdpProt->RegisterReceiver(orc::robots::Iiwa::SIL_CONTROLLER_PORT, THIS_CAST(ITcIoUdpProtocolRecv))))
			{
				m_Trace.Log(tlError, FLEAVEA "Server: UdpProt RegisterReceiver failed on Port: %d", orc::robots::Iiwa::SIL_CONTROLLER_PORT);
				m_spUdpProt = NULL;
			}

			// trajectory port
			m_Trace.Log(tlInfo, FLEAVEA "Iiwa Trajectory Server: Listen to UDP Port: %d", orc::robots::Iiwa::SERVER_PORT);
			if (FAILED(hr = m_spUdpProt->RegisterReceiver(orc::robots::Iiwa::SERVER_PORT, THIS_CAST(ITcIoUdpProtocolRecv))))
			{
				m_Trace.Log(tlError, FLEAVEA "Server: UdpProt RegisterReceiver failed on Port: %d", orc::robots::Iiwa::SERVER_PORT);
				m_spUdpProt = NULL;
			}

			/* LinearAxis */
			// SIL port
			m_Trace.Log(tlInfo, FLEAVEA "LinearAxis SIL Server: Listen to UDP Port: %d", orc::robots::LinearAxis::SIL_CONTROLLER_PORT);
			if (FAILED(hr = m_spUdpProt->RegisterReceiver(orc::robots::LinearAxis::SIL_CONTROLLER_PORT, THIS_CAST(ITcIoUdpProtocolRecv))))
			{
				m_Trace.Log(tlError, FLEAVEA "Server: UdpProt RegisterReceiver failed on Port: %d", orc::robots::Iiwa::SIL_CONTROLLER_PORT);
				m_spUdpProt = NULL;
			}

			// trajectory port
			m_Trace.Log(tlInfo, FLEAVEA "LinearAxis Trajectory Server: Listen to UDP Port: %d", orc::robots::LinearAxis::SERVER_PORT);
			if (FAILED(hr = m_spUdpProt->RegisterReceiver(orc::robots::LinearAxis::SERVER_PORT, THIS_CAST(ITcIoUdpProtocolRecv))))
			{
				m_Trace.Log(tlError, FLEAVEA "Server: UdpProt RegisterReceiver failed on Port: %d", orc::robots::LinearAxis::SERVER_PORT);
				m_spUdpProt = NULL;
			}
		}
	}
	else {
		m_Trace.Log(tlError, FLEAVEA "Not set interfacepointer UdpProt?");
		return ADS_E_INVALIDOBJID;
	}

	// If following call is successful the CycleUpdate method will be called, 
	// eventually even before method has been left.
	hr = FAILED(hr) ? hr : AddModuleToCaller(); 

	// Cleanup if transition failed at some stage
	if ( FAILED(hr) )
	{
		if (m_spUdpProt != NULL)
		{
			m_spUdpProt->UnregisterReceiver(orc::robots::Iiwa::SIL_CONTROLLER_PORT);
			m_spUdpProt->UnregisterReceiver(orc::robots::Iiwa::SERVER_PORT);

			m_spUdpProt->UnregisterReceiver(orc::robots::LinearAxis::SIL_CONTROLLER_PORT);
			m_spUdpProt->UnregisterReceiver(orc::robots::LinearAxis::SERVER_PORT);
		}
		m_spUdpProt = NULL;

		RemoveModuleFromCaller(); 
	}
	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from OP to SAFEOP
HRESULT CUdpInterface::SetObjStateOS()
{
	m_Trace.Log(tlVerbose, FENTERA);
	HRESULT hr = S_OK;

	RemoveModuleFromCaller();

	if (m_spUdpProt != NULL)
	{
		m_spUdpProt->UnregisterReceiver(orc::robots::Iiwa::SIL_CONTROLLER_PORT);
		m_spUdpProt->UnregisterReceiver(orc::robots::Iiwa::SERVER_PORT);

		m_spUdpProt->UnregisterReceiver(orc::robots::LinearAxis::SIL_CONTROLLER_PORT);
		m_spUdpProt->UnregisterReceiver(orc::robots::LinearAxis::SERVER_PORT);
	}
	m_spUdpProt = NULL;

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to PREOP
HRESULT CUdpInterface::SetObjStateSP()
{
	m_Trace.Log(tlVerbose, FENTERA);
	HRESULT hr = S_OK;

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///<AutoGeneratedContent id="ImplementationOf_ITcCyclic">
HRESULT CUdpInterface::CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context)
{
	HRESULT hr = S_OK;

	/* Iiwa TX */
	 // send data if available
	if (m_Iiwa_Inputs.tx_msg.request == true) {
		m_Iiwa_Inputs.tx_msg.request = false;
		const uint16_t msg_size = std::min<int>(m_Iiwa_Inputs.tx_msg.size, sizeof(m_Iiwa_Inputs.tx_msg.data));
		hr = m_spUdpProt->SendData(client_ipaddr, orc::robots::Iiwa::CLIENT_PORT, orc::robots::Iiwa::SERVER_PORT, msg_size, &(m_Iiwa_Inputs.tx_msg.data[0]), true);
		hr = m_spUdpProt->SendData(client_ipaddr, orc::robots::Iiwa::CLIENT_PORT + 100, orc::robots::Iiwa::SERVER_PORT + 100, msg_size, &(m_Iiwa_Inputs.tx_msg.data[0]), true);
		const ULONG ipAddr = client_ipaddr;
		//m_Trace.Log(tlInfo, FLEAVEA "ARC Send Data: IP: %d.%d.%d.%d udpSrcPort: %d DataSize: %d (hr2=%x) \n", ((PBYTE)&ipAddr)[3], ((PBYTE)&ipAddr)[2], ((PBYTE)&ipAddr)[1], ((PBYTE)&ipAddr)[0], orc::robots::Iiwa::SERVER_PORT, msg_size, hr);
	}
	
	// SIL - send torque setpoint
	hr = m_spUdpProt->SendData(client_ipaddr, orc::robots::Iiwa::SIL_MODEL_PORT, orc::robots::Iiwa::SIL_CONTROLLER_PORT, sizeof(m_Iiwa_Sil_Input.joint_torque), &(m_Iiwa_Sil_Input.joint_torque), true);


	/* Linear Axis TX */
	 // send data if available
	if (m_LinAxis_Inputs.tx_msg.request == true) {
		m_LinAxis_Inputs.tx_msg.request = false;
		const uint16_t msg_size = std::min<int>(m_LinAxis_Inputs.tx_msg.size, sizeof(m_LinAxis_Inputs.tx_msg.data));
		hr = m_spUdpProt->SendData(client_ipaddr, orc::robots::LinearAxis::CLIENT_PORT, orc::robots::LinearAxis::SERVER_PORT, msg_size, &(m_LinAxis_Inputs.tx_msg.data[0]), true);
		const ULONG ipAddr = client_ipaddr;
	}

	// SIL - send torque setpoint
	hr = m_spUdpProt->SendData(client_ipaddr, orc::robots::LinearAxis::SIL_MODEL_PORT, orc::robots::LinearAxis::SIL_CONTROLLER_PORT, sizeof(m_LinAxis_Sil_Input.joint_torque), &(m_LinAxis_Sil_Input.joint_torque), true);



	/* Receive UDP msgs */
	// check if rx data is available
	m_spUdpProt->CheckReceived();


	/* Iiwa RX*/
	// drain message buffer
	if (   iiwa_buf_read_index > -1
		&& iiwa_buf_read_index <= iiwa_buf_write_index
		&& m_Iiwa_Outputs.rx_msg.request == false)
	{
		const USHORT msg_size = iiwa_msg_buffer[iiwa_buf_read_index].size;
		m_Iiwa_Outputs.rx_msg.request = true;
		m_Iiwa_Outputs.rx_msg.size = msg_size;
		memcpy(&(m_Iiwa_Outputs.rx_msg.data[0]), iiwa_msg_buffer[iiwa_buf_read_index].data, msg_size);
		iiwa_buf_read_index++;
	}
	else if (iiwa_buf_read_index > iiwa_buf_write_index) {
		// buffer is drained; reset index
		iiwa_buf_read_index = -1;
		iiwa_buf_write_index = -1;
	}


	/* Linear Axis RX*/
	// drain message buffer
	if (linax_buf_read_index > -1
		&& linax_buf_read_index <= linax_buf_write_index
		&& m_LinAxis_Outputs.rx_msg.request == false)
	{
		const USHORT msg_size = linax_msg_buffer[linax_buf_read_index].size;
		m_LinAxis_Outputs.rx_msg.request = true;
		m_LinAxis_Outputs.rx_msg.size = msg_size;
		memcpy(&(m_LinAxis_Outputs.rx_msg.data[0]), linax_msg_buffer[linax_buf_read_index].data, msg_size);
		linax_buf_read_index++;
	}
	else if (linax_buf_read_index > linax_buf_write_index) {
		// buffer is drained; reset index
		linax_buf_read_index = -1;
		linax_buf_write_index = -1;
	}

	return hr;
}
///</AutoGeneratedContent>

///////////////////////////////////////////////////////////////////////////////
HRESULT CUdpInterface::AddModuleToCaller()
{
	m_Trace.Log(tlVerbose, FENTERA);
	HRESULT hr = S_OK;
	if ( m_spCyclicCaller.HasOID() )
	{
		if ( SUCCEEDED_DBG(hr = m_spSrv->TcQuerySmartObjectInterface(m_spCyclicCaller)) )
		{
			if ( FAILED(hr = m_spCyclicCaller->AddModule(m_spCyclicCaller, THIS_CAST(ITcCyclic))) )
			{
				m_spCyclicCaller = NULL;
			}
		}
	}
	else
	{
		hr = ADS_E_INVALIDOBJID; 
		SUCCEEDED_DBGT(hr, "Invalid OID specified for caller task");
	}
	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
VOID CUdpInterface::RemoveModuleFromCaller()
{
	m_Trace.Log(tlVerbose, FENTERA);
	if ( m_spCyclicCaller )
	{
		m_spCyclicCaller->RemoveModule(m_spCyclicCaller);
	}
	m_spCyclicCaller	= NULL;
	m_Trace.Log(tlVerbose, FLEAVEA);
}


///<AutoGeneratedContent id="ImplementationOf_ITcIoUdpProtocolRecv">
HRESULT CUdpInterface::ReceiveData(ULONG ipAddr, USHORT udpDestPort, USHORT udpSrcPort, ULONG nData, PVOID pData, ETYPE_VLAN_HEADER* pVlan)
{
	HRESULT hr = S_OK;
	
	//m_Trace.Log(tlInfo, FLEAVEA "udpSrcPort: %d udpDstPort: %d \n", udpSrcPort, udpDestPort);

	switch (udpDestPort) {

	/* Iiwa */

	case orc::robots::Iiwa::SERVER_PORT:
		//m_Iiwa_Outputs.rx_msg.request = true;
		//m_Iiwa_Outputs.rx_msg.size = sizeof(m_Iiwa_Outputs.rx_msg.data);
		//memcpy(&(m_Iiwa_Outputs.rx_msg.data[0]), pData, sizeof(m_Iiwa_Outputs.rx_msg.data));

		m_Trace.Log(tlInfo, FLEAVEA "ARC Trajectory received: IP: %d.%d.%d.%d udpSrcPort: %d DataSize: %d (hr2=%x) \n", ((PBYTE)&ipAddr)[3], ((PBYTE)&ipAddr)[2], ((PBYTE)&ipAddr)[1], ((PBYTE)&ipAddr)[0], udpSrcPort, nData, hr);

		// move received data into iiwa_msg_buffer
		if(iiwa_buf_write_index < (MSG_BUFFER_LEN-1)){
			if (nData <= sizeof(m_Iiwa_Outputs.rx_msg.data)) {
				iiwa_buf_write_index++;
				if (iiwa_buf_read_index < 0) iiwa_buf_read_index = 0;
				iiwa_msg_buffer[iiwa_buf_write_index].size = static_cast<USHORT>(nData);
				memcpy(&(iiwa_msg_buffer[iiwa_buf_write_index].data), pData, nData);
			}
			else {
				m_Trace.Log(tlInfo, FLEAVEA "ARC Trajectory received: Too much data received! Msg ignored! \n");
			}
		}
		else {
			m_Trace.Log(tlInfo, FLEAVEA "ARC Trajectory received: Msg Buffer full! Msg ignored! \n");
		}
		
		break;

	case orc::robots::Iiwa::SIL_CONTROLLER_PORT:
		// SIL receive actual joint state
		if (nData >= sizeof(m_Iiwa_Sil_Output.joint_state)) {
			memcpy(&(m_Iiwa_Sil_Output.joint_state), pData, sizeof(m_Iiwa_Sil_Output.joint_state));
		}
		break;

	/* Linear Axis */
	case orc::robots::LinearAxis::SERVER_PORT:
		m_Trace.Log(tlInfo, FLEAVEA "Linear Axis Trajectory received: IP: %d.%d.%d.%d udpSrcPort: %d DataSize: %d (hr2=%x) \n", ((PBYTE)&ipAddr)[3], ((PBYTE)&ipAddr)[2], ((PBYTE)&ipAddr)[1], ((PBYTE)&ipAddr)[0], udpSrcPort, nData, hr);

		// move received data into linax_msg_buffer
		if (linax_buf_write_index < (MSG_BUFFER_LEN - 1)) {
			if (nData <= sizeof(m_LinAxis_Outputs.rx_msg.data)) {
				linax_buf_write_index++;
				if (linax_buf_read_index < 0) linax_buf_read_index = 0;
				linax_msg_buffer[linax_buf_write_index].size = static_cast<USHORT>(nData);
				memcpy(&(linax_msg_buffer[linax_buf_write_index].data), pData, nData);
			}
			else {
				m_Trace.Log(tlInfo, FLEAVEA "Linear Axis Trajectory received: Too much data received! Msg ignored! \n");
			}
		}
		else {
			m_Trace.Log(tlInfo, FLEAVEA "Linear Axis Trajectory received: Msg Buffer full! Msg ignored! \n");
		}

		break;

	case orc::robots::LinearAxis::SIL_CONTROLLER_PORT:
		// SIL receive actual joint state
		if (nData >= sizeof(m_LinAxis_Sil_Output.joint_state)) {
			memcpy(&(m_LinAxis_Sil_Output.joint_state), pData, sizeof(m_LinAxis_Sil_Output.joint_state));
		}
		break;

	default:
		m_Trace.Log(tlInfo, FLEAVEA "UDP ReceiveData: IP: %d.%d.%d.%d udpSrcPort: %d DataSize: %d (hr2=%x) \n", ((PBYTE)&ipAddr)[3], ((PBYTE)&ipAddr)[2], ((PBYTE)&ipAddr)[1], ((PBYTE)&ipAddr)[0], udpSrcPort, nData, hr);
	}

	return hr;
}
///</AutoGeneratedContent>
