///////////////////////////////////////////////////////////////////////////////
// UdpInterfaceServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_UdpInterface = 0x3F000000;
#define SRVNAME_UDPINTERFACE "UdpInterface"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_UdpInterfaceCUdpInterface = {0xf47d354c,0x1bc6,0x4e2a,{0x84,0xc7,0x81,0xef,0xa1,0xd6,0x20,0x25}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_UdpInterfaceclient_ip_addr = 0x00000002;
const PTCID PID_UdpInterfaceUdpProt = 0x00000001;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
#if !defined(_TC_TYPE_644F3385_C5F8_4BFB_B16A_FB99EAC8BB62_INCLUDED_)
#define _TC_TYPE_644F3385_C5F8_4BFB_B16A_FB99EAC8BB62_INCLUDED_
typedef struct _ETYPE_VLAN_HEADER
{
	USHORT VLanType;
	unsigned char VLanIdH : 4;
	unsigned char reserved1 : 1;
	unsigned char Priority : 3;
	unsigned char VLanIdL : 8;
} ETYPE_VLAN_HEADER, *PETYPE_VLAN_HEADER;
#endif // !defined(_TC_TYPE_644F3385_C5F8_4BFB_B16A_FB99EAC8BB62_INCLUDED_)

#if !defined(_TC_TYPE_A310A946_D536_4A8A_9C58_A521C053E0BD_INCLUDED_)
#define _TC_TYPE_A310A946_D536_4A8A_9C58_A521C053E0BD_INCLUDED_
#pragma pack(push,1)
typedef struct _udp_msg
{
	bool request;
	USHORT size;
	BYTE data[1472];
} udp_msg, *Pudp_msg;
#pragma pack(pop)
#endif // !defined(_TC_TYPE_A310A946_D536_4A8A_9C58_A521C053E0BD_INCLUDED_)

#if !defined(_TC_TYPE_1247A85A_0A92_414F_B870_2E17BF811B63_INCLUDED_)
#define _TC_TYPE_1247A85A_0A92_414F_B870_2E17BF811B63_INCLUDED_
typedef struct _acin_control_Joints_t
{
	double Values[7];
} acin_control_Joints_t, *Pacin_control_Joints_t;
#endif // !defined(_TC_TYPE_1247A85A_0A92_414F_B870_2E17BF811B63_INCLUDED_)

#if !defined(_TC_TYPE_18071995_0000_0000_0000_00000000003E_INCLUDED_)
#define _TC_TYPE_18071995_0000_0000_0000_00000000003E_INCLUDED_
typedef BYTE IPADDR[4];
#endif // !defined(_TC_TYPE_18071995_0000_0000_0000_00000000003E_INCLUDED_)

#if !defined(_TC_TYPE_7081F11C_23FB_4BBB_A810_166A40CF032A_INCLUDED_)
#define _TC_TYPE_7081F11C_23FB_4BBB_A810_166A40CF032A_INCLUDED_
typedef struct _Vec2D
{
	double x;
	double y;
} Vec2D, *PVec2D;
#endif // !defined(_TC_TYPE_7081F11C_23FB_4BBB_A810_166A40CF032A_INCLUDED_)

#pragma pack(push,1)
typedef struct _UdpInterfaceIiwa_Inputs
{
	udp_msg tx_msg;
} UdpInterfaceIiwa_Inputs, *PUdpInterfaceIiwa_Inputs;
#pragma pack(pop)

#pragma pack(push,1)
typedef struct _UdpInterfaceIiwa_Outputs
{
	udp_msg rx_msg;
} UdpInterfaceIiwa_Outputs, *PUdpInterfaceIiwa_Outputs;
#pragma pack(pop)

typedef struct _UdpInterfaceIiwa_Sil_Input
{
	acin_control_Joints_t joint_torque;
} UdpInterfaceIiwa_Sil_Input, *PUdpInterfaceIiwa_Sil_Input;

typedef struct _UdpInterfaceIiwa_Sil_Output
{
	acin_control_Joints_t joint_state;
} UdpInterfaceIiwa_Sil_Output, *PUdpInterfaceIiwa_Sil_Output;

#pragma pack(push,1)
typedef struct _UdpInterfaceLinAxis_Inputs
{
	udp_msg tx_msg;
} UdpInterfaceLinAxis_Inputs, *PUdpInterfaceLinAxis_Inputs;
#pragma pack(pop)

#pragma pack(push,1)
typedef struct _UdpInterfaceLinAxis_Outputs
{
	udp_msg rx_msg;
} UdpInterfaceLinAxis_Outputs, *PUdpInterfaceLinAxis_Outputs;
#pragma pack(pop)

typedef struct _UdpInterfaceLinAxis_Sil_Input
{
	Vec2D joint_torque;
} UdpInterfaceLinAxis_Sil_Input, *PUdpInterfaceLinAxis_Sil_Input;

typedef struct _UdpInterfaceLinAxis_Sil_Output
{
	Vec2D joint_state;
} UdpInterfaceLinAxis_Sil_Output, *PUdpInterfaceLinAxis_Sil_Output;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_UdpInterfaceIiwa_Inputs 1
#define ADI_UdpInterfaceIiwa_Outputs 2
#define ADI_UdpInterfaceIiwa_Sil_Input 3
#define ADI_UdpInterfaceIiwa_Sil_Output 4
#define ADI_UdpInterfaceLinAxis_Inputs 5
#define ADI_UdpInterfaceLinAxis_Outputs 6
#define ADI_UdpInterfaceLinAxis_Sil_Input 7
#define ADI_UdpInterfaceLinAxis_Sil_Output 8
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
#if !defined(_TC_IID_03010097_0000_0000_E000_000000000064_INCLUDED_)
#define _TC_IID_03010097_0000_0000_E000_000000000064_INCLUDED_
TCOM_DECL_INTERFACE("03010097-0000-0000-e000-000000000064", ITcIoUdpProtocol)
#endif // !defined(_TC_IID_03010097_0000_0000_E000_000000000064_INCLUDED_)

#if !defined(_TC_IID_03010095_0000_0000_E000_000000000064_INCLUDED_)
#define _TC_IID_03010095_0000_0000_E000_000000000064_INCLUDED_
TCOM_DECL_INTERFACE("03010095-0000-0000-e000-000000000064", ITcIoUdpProtocolRecv)
#endif // !defined(_TC_IID_03010095_0000_0000_E000_000000000064_INCLUDED_)

///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
