///////////////////////////////////////////////////////////////////////////////
// IiwaSimClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "IiwaSimClassFactory.h"
#include "IiwaSimServices.h"
#include "IiwaSimVersion.h"

BEGIN_CLASS_MAP(CIiwaSimClassFactory)
///<AutoGeneratedContent id="ClassMap">
///</AutoGeneratedContent>
END_CLASS_MAP()

CIiwaSimClassFactory::CIiwaSimClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME_TMX(SRVNAME_IIWASIM));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(IiwaSim));
#endif //defined(TCDBG_UNIT_VERSION)
}

