///////////////////////////////////////////////////////////////////////////////
// IiwaSimServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_IiwaSim = 0x3F000000;
#define SRVNAME_IIWASIM "IiwaSim"

///<AutoGeneratedContent id="ClassIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
///</AutoGeneratedContent>


