///////////////////////////////////////////////////////////////////////////////
// OrcLinAxisControlInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "OrcLinAxisControlServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
