///////////////////////////////////////////////////////////////////////////////
// OrcLinAxisControlClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "OrcLinAxisControlClassFactory.h"
#include "OrcLinAxisControlServices.h"
#include "OrcLinAxisControlVersion.h"
#include "OrcLinAxisContr.h"

BEGIN_CLASS_MAP(COrcLinAxisControlClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY_LIB(VID_OrcLinAxisControl, CID_OrcLinAxisControlCOrcLinAxisContr, SRVNAME_ORCLINAXISCONTROL "!COrcLinAxisContr", COrcLinAxisContr)
///</AutoGeneratedContent>
END_CLASS_MAP()

COrcLinAxisControlClassFactory::COrcLinAxisControlClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME_TMX(SRVNAME_ORCLINAXISCONTROL));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(OrcLinAxisControl));
#endif //defined(TCDBG_UNIT_VERSION)
}

