///////////////////////////////////////////////////////////////////////////////
// OrcTcControlClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "OrcTcControlClassFactory.h"
#include "OrcTcControlServices.h"
#include "OrcTcControlVersion.h"
#include "OrcController.h"

BEGIN_CLASS_MAP(COrcTcControlClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY_LIB(VID_OrcTcControl, CID_OrcTcControlCOrcController, SRVNAME_ORCTCCONTROL "!COrcController", COrcController)
///</AutoGeneratedContent>
END_CLASS_MAP()

COrcTcControlClassFactory::COrcTcControlClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME_TMX(SRVNAME_ORCTCCONTROL));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(OrcTcControl));
#endif //defined(TCDBG_UNIT_VERSION)
}

