///////////////////////////////////////////////////////////////////////////////
// OrcTcControlInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "OrcTcControlServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
