///////////////////////////////////////////////////////////////////////////////
// ArcController.h
#pragma once

#include "ArcTcControlInterfaces.h"
#include <orc/OrcTypes.h>
#include <orc/util/Logger.h>
#include <orc/robots/Iiwa.h>
#include "StateMachine.h"

#include "TcFileAccessInterfaces.h"

#include <mujoco_tc/mujoco_tc.h>

#define LINEAR_AXIS_ENABLE_COOLDOWN 1000*8

using namespace orc;

class CArcController 
	: public ITComObject
	, public ITcADI
	, public ITcWatchSource
///<AutoGeneratedContent id="InheritanceList">
	, public ITcCyclic
	, public ITcPostCyclic
///</AutoGeneratedContent>
{
public:
	DECLARE_IUNKNOWN()
	DECLARE_IPERSIST_LIB()
	DECLARE_ITCOMOBJECT_LOCKOP()
	DECLARE_ITCADI()
	DECLARE_ITCWATCHSOURCE()
	DECLARE_OBJPARAWATCH_MAP()
	DECLARE_OBJDATAAREA_MAP()

	CArcController();
	virtual	~CArcController();


///<AutoGeneratedContent id="InterfaceMembers">
	// ITcCyclic
	virtual HRESULT TCOMAPI CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context);

	// ITcPostCyclic
	virtual HRESULT TCOMAPI PostCyclicUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context);

///</AutoGeneratedContent>

protected:
	DECLARE_ITCOMOBJECT_SETSTATE();

	HRESULT AddModuleToCaller();
	VOID RemoveModuleFromCaller();

	HRESULT InitDataPointer();
	VOID DeinitDataPointer();

	// Tracing
	CTcTrace m_Trace;

///<AutoGeneratedContent id="Members">
	typedef _TCOM_SMARTDATAPTR<udp_msg> udp_msgDataPtr;

	TcTraceLevel m_TraceLevelMax;
	double m_Ts;
	ArcControllerMujocoModel m_MujocoModel;
	STRING127 m_CustomMujocoModelPath;
	bool m_singular_perturbation_enable;
	bool m_friction_compensation_enable;
	ArcControllerInputs m_Inputs;
	ArcControllerrobot_interface_in m_robot_interface_in;
	ArcControllerrobot_interface_out m_robot_interface_out;
	ArcControllerOutputs m_Outputs;
	ITcCyclicCallerInfoPtr m_spCyclicCaller;
	ITcPostCyclicPtr m_spPostCyclic;
	udp_msgDataPtr m_spudp_tx_msg;
	udp_msgDataPtr m_spudp_rx_msg;
///</AutoGeneratedContent>

	// TODO: Custom variable
	ULONG TaskCycleTime = 0; // cycle time in ns 
	Time Ts;
	Time t;

	orc::log::Logger arc_log;
	orc::robots::Iiwa::IiwaContrParam arc_contr_param;
	orc::robots::Iiwa* arc_contr_ptr;
	orc::logic::StateMachine* state_machine_ptr;

	using JointVector = orc::robots::Iiwa::JointVector;
	using JointArray = orc::robots::Iiwa::JointArray;

	// File access helper functions
	ITcFileAccessPtr m_spFileAccess;
	// Setting the model_binary type to unsigned char, leads to correct representation of the data
	// when compared to the hex editor of Notepad++.
	PUCHAR model_binary;
	UINT model_size;
	HRESULT readBinaryModel(PCCH fileName);
	bool iniOK = false;
	UINT counter;
};
