///////////////////////////////////////////////////////////////////////////////
// ArcController.cpp
#include "TcPch.h"
#pragma hdrstop

#include "ArcController.h"
#include "ArcTcControlVersion.h"
#include "orc/robots/Iiwa.h"
#include "orc/com/TcServerUtil.h"
#include "orc/util/Logger.h"
#include "StateMachine.h"

#include <mujoco_tc/mujoco_tc.h>
#include <mujoco_tc/engine_util_misc_tc.h>
#include <mujoco_tc/engine_io_tc.h>

#ifdef _DEBUG
#define new DEBUG_NEW
#endif
DEFINE_THIS_FILE()

///////////////////////////////////////////////////////////////////////////////
// CArcController
///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////
// Collection of interfaces implemented by module CArcController
BEGIN_INTERFACE_MAP(CArcController)
	INTERFACE_ENTRY_ITCOMOBJECT()
	INTERFACE_ENTRY(IID_ITcADI, ITcADI)
	INTERFACE_ENTRY(IID_ITcWatchSource, ITcWatchSource)
///<AutoGeneratedContent id="InterfaceMap">
	INTERFACE_ENTRY(IID_ITcCyclic, ITcCyclic)
	INTERFACE_ENTRY(IID_ITcPostCyclic, ITcPostCyclic)
///</AutoGeneratedContent>
END_INTERFACE_MAP()

IMPLEMENT_IPERSIST_LIB(CArcController, VID_ArcTcControl, CID_ArcTcControlCArcController)
IMPLEMENT_ITCOMOBJECT(CArcController)
IMPLEMENT_ITCOMOBJECT_SETSTATE_LOCKOP2(CArcController)
IMPLEMENT_ITCADI(CArcController)
IMPLEMENT_ITCWATCHSOURCE(CArcController)


///////////////////////////////////////////////////////////////////////////////
// Set parameters of CArcController 
BEGIN_SETOBJPARA_MAP(CArcController)
	SETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="SetObjectParameterMap">
	SETOBJPARA_VALUE(PID_TcTraceLevel, m_TraceLevelMax)
	SETOBJPARA_VALUE(PID_ArcControllerTs, m_Ts)
	SETOBJPARA_VALUE(PID_ArcControllerMujocoModel, m_MujocoModel)
	SETOBJPARA_VALUE(PID_ArcControllerCustomMujocoModelPath, m_CustomMujocoModelPath)
	SETOBJPARA_VALUE(PID_ArcControllersingular_perturbation_enable, m_singular_perturbation_enable)
	SETOBJPARA_VALUE(PID_ArcControllerfriction_compensation_enable, m_friction_compensation_enable)
	SETOBJPARA_ITFPTR(PID_Ctx_TaskOid, m_spCyclicCaller)
	SETOBJPARA_ITFPTR(PID_ArcControllerPostCyclic, m_spPostCyclic)
	SETOBJPARA_DATAPTR(PID_ArcControllerudp_tx_msg, m_spudp_tx_msg)
	SETOBJPARA_DATAPTR(PID_ArcControllerudp_rx_msg, m_spudp_rx_msg)
///</AutoGeneratedContent>
END_SETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get parameters of CArcController 
BEGIN_GETOBJPARA_MAP(CArcController)
	GETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="GetObjectParameterMap">
	GETOBJPARA_VALUE(PID_TcTraceLevel, m_TraceLevelMax)
	GETOBJPARA_VALUE(PID_ArcControllerTs, m_Ts)
	GETOBJPARA_VALUE(PID_ArcControllerMujocoModel, m_MujocoModel)
	GETOBJPARA_VALUE(PID_ArcControllerCustomMujocoModelPath, m_CustomMujocoModelPath)
	GETOBJPARA_VALUE(PID_ArcControllersingular_perturbation_enable, m_singular_perturbation_enable)
	GETOBJPARA_VALUE(PID_ArcControllerfriction_compensation_enable, m_friction_compensation_enable)
	GETOBJPARA_ITFPTR(PID_Ctx_TaskOid, m_spCyclicCaller)
	GETOBJPARA_ITFPTR(PID_ArcControllerPostCyclic, m_spPostCyclic)
///</AutoGeneratedContent>
END_GETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get watch entries of CArcController
BEGIN_OBJPARAWATCH_MAP(CArcController)
	OBJPARAWATCH_DATAAREA_MAP()
///<AutoGeneratedContent id="ObjectParameterWatchMap">
	OBJPARAWATCH_VALUE(PID_ArcControllerMujocoModel, m_MujocoModel)
	OBJPARAWATCH_VALUE(PID_ArcControllersingular_perturbation_enable, m_singular_perturbation_enable)
	OBJPARAWATCH_VALUE(PID_ArcControllerfriction_compensation_enable, m_friction_compensation_enable)
///</AutoGeneratedContent>
END_OBJPARAWATCH_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get data area members of CArcController
BEGIN_OBJDATAAREA_MAP(CArcController)
///<AutoGeneratedContent id="ObjectDataAreaMap">
	OBJDATAAREA_VALUE(ADI_ArcControllerInputs, m_Inputs)
	OBJDATAAREA_VALUE(ADI_ArcControllerrobot_interface_in, m_robot_interface_in)
	OBJDATAAREA_VALUE(ADI_ArcControllerrobot_interface_out, m_robot_interface_out)
	OBJDATAAREA_VALUE(ADI_ArcControllerOutputs, m_Outputs)
///</AutoGeneratedContent>
END_OBJDATAAREA_MAP()


///////////////////////////////////////////////////////////////////////////////
CArcController::CArcController()
	: m_Trace(m_TraceLevelMax, m_spSrv)
	, t(0.0)
	, Ts(0.0)
	, arc_contr_param()
	, arc_contr_ptr(NULL)
	, state_machine_ptr(NULL)
	, arc_log(orc::log::Level::Debug, &m_Trace)
{
///<AutoGeneratedContent id="MemberInitialization">
	m_TraceLevelMax = tlAlways;
	m_Ts = 0;
	m_MujocoModel = iiwa_hanging;
	memset(&m_CustomMujocoModelPath, 0, sizeof(m_CustomMujocoModelPath));
	m_singular_perturbation_enable = FALSE;
	m_friction_compensation_enable = FALSE;
	memset(&m_Inputs, 0, sizeof(m_Inputs));
	memset(&m_robot_interface_in, 0, sizeof(m_robot_interface_in));
	memset(&m_robot_interface_out, 0, sizeof(m_robot_interface_out));
	memset(&m_Outputs, 0, sizeof(m_Outputs));
///</AutoGeneratedContent>
}

///////////////////////////////////////////////////////////////////////////////
CArcController::~CArcController()
{
}


///////////////////////////////////////////////////////////////////////////////
// State Transitions 
///////////////////////////////////////////////////////////////////////////////
IMPLEMENT_ITCOMOBJECT_SETOBJSTATE_IP_PI(CArcController)

///////////////////////////////////////////////////////////////////////////////
// State transition from PREOP to SAFEOP
//
// Initialize input parameters 
// Allocate memory
HRESULT CArcController::SetObjStatePS(PTComInitDataHdr pInitData)
{
	counter = 0;
	m_Trace.Log(tlVerbose, FENTERA);
	HRESULT hr = S_OK;
	IMPLEMENT_ITCOMOBJECT_EVALUATE_INITDATA(pInitData);

	// TODO: Add initialization code
	// 

	// ------------------- READ IN MUJOCO FILE -------------	
	// Create file access instance
	hr = m_spSrv->TcCreateInstance(CID_TcFileAccess, IID_ITcFileAccess, (PPVOID)(&m_spFileAccess));

	// Choose mjb file as per TwinCAT parameters
	std::string model_path = "C:\\TwinCAT\\3.1\\Boot\\";
	if (m_MujocoModel == ArcControllerMujocoModel::iiwa_hanging)
		model_path.append("iiwa_hanging.mjb");
	else if (m_MujocoModel == ArcControllerMujocoModel::iiwa_hanging_with_mass_gripped)
		model_path.append("iiwa_hanging_with_mass_gripped.mjb");
	else if (m_MujocoModel == ArcControllerMujocoModel::custom)
		model_path.append(m_CustomMujocoModelPath);
	else
		return E_FAIL;
	strcpy(m_Outputs.model_path, model_path.c_str());
	
	if (SUCCEEDED(hr)) {
		ITComObjectPtr spFileAccessObj = m_spFileAccess;
		hr = spFileAccessObj->TcSetObjState(TCOM_STATE_PREOP, m_spSrv, pInitData);
		if (SUCCEEDED(hr)) {
			// read Mujoco binary file (iiwa.mjb) from _Boot directory
			m_Trace.Log(tlVerbose, FENTERA "Reading MJB file!");
			// %BOOTPRJPATH% und %TC_TARGETPATH% funktionieren hier nicht, wieso?
			hr = readBinaryModel(model_path.c_str());
		}
	}
	// ------------------- MUJOCO END ----------------------
	
	orc::log::start_logging_twincat(m_TraceLevelMax, &m_Trace);
	m_Trace.Log(tlAlways, FLEAVEA "ORC initialized!", hr);
	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to OP
//
// Register with other TwinCAT objects
HRESULT CArcController::SetObjStateSO()
{
	m_Trace.Log(tlVerbose, FENTERA);
	HRESULT hr = S_OK;

	// TODO: Add any additional initialization

	// Initialize data pointer 
	hr = FAILED(hr) ? hr : InitDataPointer();

	// current time
	t = 0.0;

	// read cycle time from TcCom Module Parameter
	Ts = m_Ts;
	m_Trace.Log(tlAlways, FLEAVEA "Cycle Time Ts = %f", Ts);

	using namespace orc::robots;
	using JointArray = Iiwa::JointArray;
	using JointVector = Iiwa::JointVector;


	// set controller parameter
	Iiwa::IiwaContrParam contr_param(false); // true..sim, false..lab
	JointArray f_c_slow_norm = contr_param.f_c_slow * (2 * Ts.toSec());
	JointArray f_c_fast_norm = contr_param.f_c_fast * (2 * Ts.toSec());

	Iiwa::JointCTParameter js_param(contr_param);
	Iiwa::CartesianCTParameter ts_param(contr_param);
	Iiwa::SingularPerturbationParameter sp_param(contr_param.K_sp, contr_param.D_sp, contr_param.B, f_c_fast_norm);
	Iiwa::FrictionCompParameter fc_param(contr_param.L_fc, contr_param.B, f_c_fast_norm);
	Iiwa::GravityCompParameter gc_param(contr_param.D_gc);

	// create instances
	m_Trace.Log(tlAlways, FLEAVEA "Init ArcLab Controller");
	arc_contr_ptr = new robots::Iiwa((unsigned char*)model_binary, model_size, js_param, ts_param, sp_param, fc_param, gc_param, Ts, f_c_slow_norm, m_Trace);
	if (arc_contr_ptr->get_endeffector_site_id() < 0) {
		m_Trace.Log(tlError, FENTERA "Body iiwa_link_e could not be found in MuJoCo model!");
		return EXIT_FAILURE;
	}
	
	state_machine_ptr = new logic::StateMachine(&m_Trace, Ts);

	// Print robot details
	m_Trace.Log(tlInfo, FLEAVEA "model identifier = %c", arc_contr_ptr->get_model_id());
	m_Trace.Log(tlInfo, FLEAVEA "nbody = %d", arc_contr_ptr->model->nbody);
	m_Trace.Log(tlInfo, FLEAVEA "endeffector site id = %d", arc_contr_ptr->get_endeffector_site_id());

	m_Trace.Log(tlAlways, FLEAVEA "SAFEOP TO OP finished");

	// If following call is successful the CycleUpdate method will be called, 
	// possibly even before method has been left.
	hr = FAILED(hr) ? hr : AddModuleToCaller();

	// Cleanup if transition failed at some stage
	if (FAILED(hr))
	{
		RemoveModuleFromCaller();
		DeinitDataPointer();
	}

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from OP to SAFEOP
HRESULT CArcController::SetObjStateOS()
{
	m_Trace.Log(tlVerbose, FENTERA);

	HRESULT hr = S_OK;

	RemoveModuleFromCaller();

	DeinitDataPointer();
	delete arc_contr_ptr;
	delete state_machine_ptr;
	delete model_binary; // This is due to model_binary being saved on the heap

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to PREOP
HRESULT CArcController::SetObjStateSP()
{
	HRESULT hr = S_OK;
	m_Trace.Log(tlVerbose, FENTERA);

	if (m_spFileAccess != NULL)
	{
		ITComObjectPtr spFileAccessObj = m_spFileAccess;
		spFileAccessObj->TcSetObjState(TCOM_STATE_INIT, m_spSrv, NULL);
		spFileAccessObj = NULL;
		m_spFileAccess = NULL;
	}

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///<AutoGeneratedContent id="ImplementationOf_ITcCyclic">
HRESULT CArcController::CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context)
{
	HRESULT hr = S_OK;

	/* Timing */
	hr = FAILED(hr) ? hr : ipTask->GetCycleTime(&TaskCycleTime);
	Ts = ((double)TaskCycleTime) / ((double)1e9);
	orc::log::start_timing(ipTask);

	// current time
	t += Ts;

	/* UDP input*/

	if (m_spudp_rx_msg != NULL) {
		if (m_spudp_rx_msg->request) {
			m_spudp_rx_msg->request = false;
			orc::com::handle_receive(*arc_contr_ptr, &(m_spudp_rx_msg->data[0]), m_spudp_rx_msg->size);
		}
	}

	/* Control runs in PostCyclic! */
	


	/* UDP output */
	if (m_spudp_tx_msg != NULL) {
		m_spudp_tx_msg->request = true;
		auto msg_size = orc::com::send_robot_data(*arc_contr_ptr, t, state_machine_ptr->get_state(), arc_contr_ptr->get_model_id(), m_spudp_tx_msg->data, sizeof(m_spudp_tx_msg->data));
		m_spudp_tx_msg->size = msg_size;
	}

	/* set outputs */

	// actual values
	JointVector::Map(m_Outputs.q_act.Values) = arc_contr_ptr->get_q_act();
	JointVector::Map(m_Outputs.q_dot_act.Values) = arc_contr_ptr->get_q_dot_act();

	// Jointspace setpoints
	JointVector::Map(m_Outputs.q_set.Values) = arc_contr_ptr->get_q_set();
	JointVector::Map(m_Outputs.q_dot_set.Values) = arc_contr_ptr->get_q_dot_set();
	JointVector::Map(m_Outputs.q_dotdot_set.Values) = arc_contr_ptr->get_q_dotdot_set();

	// Taskspace setpoints
	PoseVector::Map(m_Outputs.pose_set.Values) = arc_contr_ptr->get_pose_set();
	CartesianVector::Map(m_Outputs.x_dot_set.Values) = arc_contr_ptr->get_x_dot_set();
	CartesianVector::Map(m_Outputs.x_dotdot_set.Values) = arc_contr_ptr->get_x_dotdot_set();
	JointVector::Map(m_Outputs.q_d_NS.Values) = arc_contr_ptr->get_q_NS_set();

	// control error
	JointVector::Map(m_Outputs.e_jointspace.Values) = arc_contr_ptr->get_joint_error();
	CartesianVector::Map(m_Outputs.e_taskspace.Values) = arc_contr_ptr->get_cartesian_error();

	// torque setpoint
	JointVector::Map(m_Outputs.tau_set.Values) = arc_contr_ptr->get_tau_act();

	// trajectory type
	m_Outputs.js_traj_active = arc_contr_ptr->is_jointspace_traj_active();
	m_Outputs.ts_traj_active = arc_contr_ptr->is_taskspace_traj_active();

	m_Outputs.ncon = arc_contr_ptr->data->ncon;

	return hr;
}
///</AutoGeneratedContent>

///////////////////////////////////////////////////////////////////////////////
HRESULT CArcController::AddModuleToCaller()
{
	m_Trace.Log(tlVerbose, FENTERA);

	HRESULT hr = S_OK;
	if (m_spCyclicCaller.HasOID())
	{
		if (SUCCEEDED_DBG(hr = m_spSrv->TcQuerySmartObjectInterface(m_spCyclicCaller)))
		{
			if (FAILED(hr = m_spCyclicCaller->AddModule(m_spCyclicCaller, THIS_CAST(ITcCyclic))))
			{
				m_spCyclicCaller = NULL;
			}
		}
	}
	else
	{
		hr = ADS_E_INVALIDOBJID;
		SUCCEEDED_DBGT(hr, "Invalid OID specified for caller task");
	}

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

////////////////////////////////////////////////cat///////////////////////////////
VOID CArcController::RemoveModuleFromCaller()
{
	m_Trace.Log(tlVerbose, FENTERA);

	if (m_spCyclicCaller)
	{
		m_spCyclicCaller->RemoveModule(m_spCyclicCaller);
	}
	m_spCyclicCaller = NULL;

	m_Trace.Log(tlVerbose, FLEAVEA);
}


///<AutoGeneratedContent id="ImplementationOf_ITcPostCyclic">
HRESULT CArcController::PostCyclicUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context)
{
	HRESULT hr = S_OK;

	// read inputs
	JointVector q_act(m_robot_interface_in.joint_state_act.Values);
	JointVector tau_sens_act(m_robot_interface_in.torque_sensor_act.Values);
	JointVector tau_motor_act(m_robot_interface_in.torque_motor_act.Values);


	// Set robot state 
	arc_contr_ptr->set_q_act_filtered_derivatives(q_act);
	arc_contr_ptr->set_tau_sens(tau_sens_act);
	arc_contr_ptr->set_tau_motor(tau_motor_act);

	// run controller
	JointVector tau_set;
	bool return_value;

	if (!iniOK) {
		Time T_traj = 1.0;
		JointVector q_end = q_act;
		arc_contr_ptr->start(t, q_act, q_end, T_traj);
		m_Trace.Log(tlInfo, FLEAVEA "arc_contr->start() executed!", hr);
	}
	else {
		return_value = arc_contr_ptr->update(t, true);
	}
	iniOK = true;

	if (return_value)
		tau_set = arc_contr_ptr->get_tau_act();
	else {
		tau_set.setZero();
		return EXIT_FAILURE;
	}

	// robot interface outputs
	JointVector::Map(m_robot_interface_out.torque_set.Values) = tau_set;
	m_robot_interface_out.motion_enable = 0.0;
	m_robot_interface_out.motion_disable = 0.0;
	if (state_machine_ptr->is_disable_transition()) {
		m_robot_interface_out.motion_disable = 1.0;
	}
	else if (state_machine_ptr->is_enable_transition()) {
		m_robot_interface_out.motion_enable = 1.0;
	}

	// robot interface works with double: convert bool to double
	double motor_enable = 1.0;
	for (int i = 0; i < sizeof(m_robot_interface_out.motor_enable.Values) / sizeof(double); i++) {
		m_robot_interface_out.motor_enable.Values[i] = motor_enable;
	}
	
	return hr;
}
///</AutoGeneratedContent>


///////////////////////////////////////////////////////////////////////////////
HRESULT CArcController::InitDataPointer()
{
	m_Trace.Log(tlVerbose, FENTERA);

	HRESULT hr = S_OK;
	hr = FAILED(hr) ? hr : m_spudp_rx_msg.Init(m_spSrv);
	hr = FAILED(hr) ? hr : m_spudp_tx_msg.Init(m_spSrv);

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
VOID CArcController::DeinitDataPointer()
{
	m_Trace.Log(tlVerbose, FENTERA);

	m_spudp_rx_msg = NULL;
	m_spudp_tx_msg = NULL;

	m_Trace.Log(tlVerbose, FLEAVEA);
}


// Reads the binary file and stores its contents into CArcController::model_binary
HRESULT CArcController::readBinaryModel(PCCH fileName)
{
	HRESULT hr = S_OK;
	m_Trace.Log(tlVerbose, FENTERA);

	// get file size to allocate space for model_binary variable in which model will be saved
	TcFileStatus FileStatus = { 0 };
	hr = m_spFileAccess->FileGetStatus(fileName, &FileStatus);
	ULONGLONG cbData = 0;
	if (SUCCEEDED(hr)) {
		m_Trace.Log(tlVerbose, FENTERA "Model size: %i", FileStatus.ulFileSize);
		if (FileStatus.ulFileSize >= UINT_MAX) {
			m_Trace.Log(tlVerbose, FENTERA "MJB file size too large!");
			return E_ABORT;
		}
		model_size = static_cast<UINT>(FileStatus.ulFileSize);
		// model_binary is allocated on the heap as its size is a priori not known, and deleted in SetObjStateOS()
		model_binary = new UCHAR[model_size];
	}
	else {
		m_Trace.Log(tlAlways, FLEAVEA "Error while reading file!");
		return hr;
	}

	// open file
	TcFileHandle hFile = NULL;
	hr = m_spFileAccess->FileOpen(fileName, static_cast<TcFileAccessMode>(amBinary | amRead), &hFile);

	if (SUCCEEDED(hr)) {
		// read file
		UINT pcbRead = 0;
		hr = m_spFileAccess->FileRead(hFile, model_binary, model_size, &pcbRead);
	}

	// close file
	hr = m_spFileAccess->FileClose(hFile);
	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}
