///////////////////////////////////////////////////////////////////////////////
// ArcTcControlInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "ArcTcControlServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
