///////////////////////////////////////////////////////////////////////////////
// ArcTcControlServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_ArcTcControl = 0x3F000000;
#define SRVNAME_ARCTCCONTROL "ArcTcControl"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_ArcTcControlCArcController = {0xe2bd113c,0xddf3,0x4a93,{0x88,0x9c,0x9c,0x66,0x8b,0x2a,0xd1,0x49}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_ArcControllerTs = 0x00000006;
const PTCID PID_ArcControllerMujocoModel = 0x0000000E;
const PTCID PID_ArcControllerCustomMujocoModelPath = 0x00000007;
const PTCID PID_ArcControllersingular_perturbation_enable = 0x00000001;
const PTCID PID_ArcControllerfriction_compensation_enable = 0x00000005;
const PTCID PID_ArcControllerPostCyclic = 0x00000002;
const PTCID PID_ArcControllerudp_tx_msg = 0x00000003;
const PTCID PID_ArcControllerudp_rx_msg = 0x00000004;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
#if !defined(_TC_TYPE_1247A85A_0A92_414F_B870_2E17BF811B63_INCLUDED_)
#define _TC_TYPE_1247A85A_0A92_414F_B870_2E17BF811B63_INCLUDED_
typedef struct _acin_control_Joints_t
{
	double Values[7];
} acin_control_Joints_t, *Pacin_control_Joints_t;
#endif // !defined(_TC_TYPE_1247A85A_0A92_414F_B870_2E17BF811B63_INCLUDED_)

#if !defined(_TC_TYPE_A310A946_D536_4A8A_9C58_A521C053E0BD_INCLUDED_)
#define _TC_TYPE_A310A946_D536_4A8A_9C58_A521C053E0BD_INCLUDED_
#pragma pack(push,1)
typedef struct _udp_msg
{
	bool request;
	USHORT size;
	BYTE data[1472];
} udp_msg, *Pudp_msg;
#pragma pack(pop)
#endif // !defined(_TC_TYPE_A310A946_D536_4A8A_9C58_A521C053E0BD_INCLUDED_)

#if !defined(_TC_TYPE_8769BB03_D2AE_4D6A_9836_4C79D55C7A62_INCLUDED_)
#define _TC_TYPE_8769BB03_D2AE_4D6A_9836_4C79D55C7A62_INCLUDED_
typedef struct _PoseVec_t
{
	double Values[7];
} PoseVec_t, *PPoseVec_t;
#endif // !defined(_TC_TYPE_8769BB03_D2AE_4D6A_9836_4C79D55C7A62_INCLUDED_)

#if !defined(_TC_TYPE_09494390_351C_4BF4_8075_AFF953BFC545_INCLUDED_)
#define _TC_TYPE_09494390_351C_4BF4_8075_AFF953BFC545_INCLUDED_
typedef struct _CartesianVec_t
{
	double Values[6];
} CartesianVec_t, *PCartesianVec_t;
#endif // !defined(_TC_TYPE_09494390_351C_4BF4_8075_AFF953BFC545_INCLUDED_)

enum ArcControllerMujocoModel : SHORT {
	iiwa_hanging = 0,
	iiwa_hanging_with_mass_gripped = 1,
	custom = 2
};

#if !defined(_TC_TYPE_18071995_0000_0000_0000_00010000007F_INCLUDED_)
#define _TC_TYPE_18071995_0000_0000_0000_00010000007F_INCLUDED_
typedef CHAR STRING127[128];
#endif // !defined(_TC_TYPE_18071995_0000_0000_0000_00010000007F_INCLUDED_)

typedef struct _ArcControllerInputs
{
	bool enable;
	bool disable;
	bool move_candle;
	bool omitCCD;
} ArcControllerInputs, *PArcControllerInputs;

typedef struct _ArcControllerrobot_interface_in
{
	acin_control_Joints_t joint_state_act;
	acin_control_Joints_t torque_sensor_act;
	acin_control_Joints_t torque_motor_act;
	double motion_enabled;
	double application_button;
} ArcControllerrobot_interface_in, *PArcControllerrobot_interface_in;

typedef struct _ArcControllerrobot_interface_out
{
	double motion_disable;
	double motion_enable;
	acin_control_Joints_t torque_set;
	acin_control_Joints_t motor_enable;
} ArcControllerrobot_interface_out, *PArcControllerrobot_interface_out;

#if !defined(_TC_TYPE_18071995_0000_0000_0000_0001000000FF_INCLUDED_)
#define _TC_TYPE_18071995_0000_0000_0000_0001000000FF_INCLUDED_
typedef CHAR STRING255[256];
#endif // !defined(_TC_TYPE_18071995_0000_0000_0000_0001000000FF_INCLUDED_)

#pragma pack(push,1)
typedef struct _ArcControllerOutputs
{
	acin_control_Joints_t q_act;
	acin_control_Joints_t q_dot_act;
	acin_control_Joints_t q_set;
	acin_control_Joints_t q_dot_set;
	acin_control_Joints_t q_dotdot_set;
	acin_control_Joints_t q_d_NS;
	PoseVec_t pose_set;
	CartesianVec_t x_dot_set;
	CartesianVec_t x_dotdot_set;
	acin_control_Joints_t e_jointspace;
	CartesianVec_t e_taskspace;
	acin_control_Joints_t tau_set;
	bool js_traj_active;
	bool ts_traj_active;
	SHORT ncon;
	STRING255 model_path;
} ArcControllerOutputs, *PArcControllerOutputs;
#pragma pack(pop)

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_ArcControllerInputs 3
#define ADI_ArcControllerrobot_interface_in 0
#define ADI_ArcControllerrobot_interface_out 1
#define ADI_ArcControllerOutputs 4
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
