///////////////////////////////////////////////////////////////////////////////
// ArcTcControlClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "ArcTcControlClassFactory.h"
#include "ArcTcControlServices.h"
#include "ArcTcControlVersion.h"
#include "ArcController.h"

BEGIN_CLASS_MAP(CArcTcControlClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY_LIB(VID_ArcTcControl, CID_ArcTcControlCArcController, SRVNAME_ARCTCCONTROL "!CArcController", CArcController)
///</AutoGeneratedContent>
END_CLASS_MAP()

CArcTcControlClassFactory::CArcTcControlClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME_TMX(SRVNAME_ARCTCCONTROL));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(ArcTcControl));
#endif //defined(TCDBG_UNIT_VERSION)
}

