///////////////////////////////////////////////////////////////////////////////
// RoboSimFastServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_RoboSimFast = 0x3F000000;
#define SRVNAME_ROBOSIMFAST "RoboSimFast"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_RoboSimFastCRobotSimulation = {0x583f2ee9,0x59e2,0x40bb,{0x89,0xf2,0x3c,0x05,0x14,0x76,0x4d,0x8d}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_RobotSimulationTs = 0x00000001;
const PTCID PID_RobotSimulationMujocoModel = 0x00000004;
const PTCID PID_RobotSimulationCustomMujocoModelPath = 0x00000005;
const PTCID PID_RobotSimulationControllerFastPostCyclic = 0x00000008;
const PTCID PID_RobotSimulationPostCyclicCaller = 0x00000009;
const PTCID PID_RobotSimulationTask = 0x0000000A;
const PTCID PID_RobotSimulationControllerFastCyclic = 0x0000000B;
const PTCID PID_RobotSimulationtorque = 0x00000002;
const PTCID PID_RobotSimulationtorque_sensor = 0x00000003;
const PTCID PID_RobotSimulationtorque_motor = 0x00000006;
const PTCID PID_RobotSimulationjoint_state = 0x00000007;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
#if !defined(_TC_TYPE_1247A85A_0A92_414F_B870_2E17BF811B63_INCLUDED_)
#define _TC_TYPE_1247A85A_0A92_414F_B870_2E17BF811B63_INCLUDED_
typedef struct _acin_control_Joints_t
{
	double Values[7];
} acin_control_Joints_t, *Pacin_control_Joints_t;
#endif // !defined(_TC_TYPE_1247A85A_0A92_414F_B870_2E17BF811B63_INCLUDED_)

enum RobotSimulationMujocoModel : SHORT {
	iiwa_hanging = 0,
	iiwa_hanging_with_mass_gripped = 1,
	custom = 2
};

#if !defined(_TC_TYPE_18071995_0000_0000_0000_00010000007F_INCLUDED_)
#define _TC_TYPE_18071995_0000_0000_0000_00010000007F_INCLUDED_
typedef CHAR STRING127[128];
#endif // !defined(_TC_TYPE_18071995_0000_0000_0000_00010000007F_INCLUDED_)

typedef struct _RobotSimulationData
{
	ULONG Value;
} RobotSimulationData, *PRobotSimulationData;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_RobotSimulationData 2
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
