///////////////////////////////////////////////////////////////////////////////
// RobotSimulation.h
#pragma once

#include "RoboSimFastInterfaces.h"

class CRobotSimulation 
	: public ITComObject
	, public ITcADI
	, public ITcWatchSource
///<AutoGeneratedContent id="InheritanceList">
	, public ITcCyclic
	, public ITcPostCyclic
///</AutoGeneratedContent>
{
public:
	DECLARE_IUNKNOWN()
	DECLARE_IPERSIST_LIB()
	DECLARE_ITCOMOBJECT_LOCKOP()
	DECLARE_ITCADI()
	DECLARE_ITCWATCHSOURCE()
	DECLARE_OBJPARAWATCH_MAP()
	DECLARE_OBJDATAAREA_MAP()

	CRobotSimulation();
	virtual	~CRobotSimulation();

///<AutoGeneratedContent id="InterfaceMembers">
	// ITcCyclic
	virtual HRESULT TCOMAPI CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context);

	// ITcPostCyclic
	virtual HRESULT TCOMAPI PostCyclicUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context);

///</AutoGeneratedContent>

protected:
	DECLARE_ITCOMOBJECT_SETSTATE();

	HRESULT AddModuleToCaller();
	VOID RemoveModuleFromCaller();

	HRESULT InitDataPointer(); 
	VOID DeinitDataPointer();

	// Tracing
	CTcTrace m_Trace;

///<AutoGeneratedContent id="Members">
	typedef _TCOM_SMARTDATAPTR<acin_control_Joints_t> Joints_tDataPtr;

	TcTraceLevel m_TraceLevelMax;
	double m_Ts;
	RobotSimulationMujocoModel m_MujocoModel;
	STRING127 m_CustomMujocoModelPath;
	RobotSimulationData m_Data;
	ITcCyclicCallerInfoPtr m_spCyclicCaller;
	ITcPostCyclicPtr m_spControllerFastPostCyclic;
	ITcPostCyclicCallerInfoPtr m_spPostCyclicCaller;
	ITcRTimeTaskPtr m_spTask;
	ITcCyclicPtr m_spControllerFastCyclic;
	Joints_tDataPtr m_sptorque;
	Joints_tDataPtr m_sptorque_sensor;
	Joints_tDataPtr m_sptorque_motor;
	Joints_tDataPtr m_spjoint_state;
///</AutoGeneratedContent>

	// TODO: Custom variable
	UINT m_Counter;
};
