///////////////////////////////////////////////////////////////////////////////
// RoboSimFastClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "RoboSimFastClassFactory.h"
#include "RoboSimFastServices.h"
#include "RoboSimFastVersion.h"
#include "RobotSimulation.h"

BEGIN_CLASS_MAP(CRoboSimFastClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY_LIB(VID_RoboSimFast, CID_RoboSimFastCRobotSimulation, SRVNAME_ROBOSIMFAST "!CRobotSimulation", CRobotSimulation)
///</AutoGeneratedContent>
END_CLASS_MAP()

CRoboSimFastClassFactory::CRoboSimFastClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME_TMX(SRVNAME_ROBOSIMFAST));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(RoboSimFast));
#endif //defined(TCDBG_UNIT_VERSION)
}

