///////////////////////////////////////////////////////////////////////////////
// RobotSimulation.h
#pragma once

#include "RoboSimFastInterfaces.h"
#include <orc/OrcTypes.h>
#include <orc/util/Logger.h>
#include <orc/robots/Iiwa.h>
#include "TcFileAccessInterfaces.h"
#include <mujoco_tc/mujoco_tc.h>

using namespace orc;

class CRobotSimulation 
	: public ITComObject
	, public ITcADI
	, public ITcWatchSource
///<AutoGeneratedContent id="InheritanceList">
	, public ITcCyclic
	, public ITcPostCyclic
///</AutoGeneratedContent>
{
public:
	DECLARE_IUNKNOWN()
	DECLARE_IPERSIST_LIB()
	DECLARE_ITCOMOBJECT_LOCKOP()
	DECLARE_ITCADI()
	DECLARE_ITCWATCHSOURCE()
	DECLARE_OBJPARAWATCH_MAP()
	DECLARE_OBJDATAAREA_MAP()

	CRobotSimulation();
	virtual	~CRobotSimulation();

///<AutoGeneratedContent id="InterfaceMembers">
	// ITcCyclic
	virtual HRESULT TCOMAPI CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context);

	// ITcPostCyclic
	virtual HRESULT TCOMAPI PostCyclicUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context);

///</AutoGeneratedContent>

protected:
	DECLARE_ITCOMOBJECT_SETSTATE();

	HRESULT AddModuleToCaller();
	VOID RemoveModuleFromCaller();

	HRESULT InitDataPointer(); 
	VOID DeinitDataPointer();

	// Tracing
	CTcTrace m_Trace;

///<AutoGeneratedContent id="Members">
	typedef _TCOM_SMARTDATAPTR<acin_control_Joints_t> Joints_tDataPtr;

	TcTraceLevel m_TraceLevelMax;
	double m_Ts;
	RobotSimulationMujocoModel m_MujocoModel;
	STRING127 m_CustomMujocoModelPath;
	RobotSimulationData m_Data;
	ITcCyclicCallerInfoPtr m_spCyclicCaller;
	ITcPostCyclicPtr m_spControllerFastPostCyclic;
	ITcPostCyclicCallerInfoPtr m_spPostCyclicCaller;
	ITcRTimeTaskPtr m_spTask;
	ITcCyclicPtr m_spControllerFastCyclic;
	Joints_tDataPtr m_sptorque;
	Joints_tDataPtr m_sptorque_sensor;
	Joints_tDataPtr m_sptorque_motor;
	Joints_tDataPtr m_spjoint_state;
///</AutoGeneratedContent>

	// TODO: Custom variable
	ULONG TaskCycleTime = 0; // cycle time in ns 
	Time Ts;
	Time t;
	orc::log::Logger orc_log;

	using JointVector = orc::robots::Iiwa::JointVector;
	using JointArray = orc::robots::Iiwa::JointArray;

	// File access helper functions
	ITcFileAccessPtr m_spFileAccess;
	// Setting the model_binary type to unsigned char, leads to correct representation of the data
	// when compared to the hex editor of Notepad++.
	PUCHAR model_binary;
	UINT model_size;
	HRESULT readBinaryModel(PCCH fileName);

	mjModel* mj_model = nullptr; /**< Mujoco model pointer */
	mjData* mj_data = nullptr;   /**< Mujoco data pointer */

	JointVector q, qd;
	
	UINT m_Counter;
};
