///////////////////////////////////////////////////////////////////////////////
// RobotSimulation.cpp
#include "TcPch.h"
#pragma hdrstop

#include "RobotSimulation.h"
#include "TcIoServices.h"
#include "RoboSimFastVersion.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#endif
DEFINE_THIS_FILE()

///////////////////////////////////////////////////////////////////////////////
// CRobotSimulation
///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////
// Collection of interfaces implemented by module CRobotSimulation
BEGIN_INTERFACE_MAP(CRobotSimulation)
	INTERFACE_ENTRY_ITCOMOBJECT()
	INTERFACE_ENTRY(IID_ITcADI, ITcADI)
	INTERFACE_ENTRY(IID_ITcWatchSource, ITcWatchSource)
///<AutoGeneratedContent id="InterfaceMap">
	INTERFACE_ENTRY(IID_ITcCyclic, ITcCyclic)
	INTERFACE_ENTRY(IID_ITcPostCyclic, ITcPostCyclic)
///</AutoGeneratedContent>
END_INTERFACE_MAP()

IMPLEMENT_IPERSIST_LIB(CRobotSimulation, VID_RoboSimFast, CID_RoboSimFastCRobotSimulation)
IMPLEMENT_ITCOMOBJECT(CRobotSimulation)
IMPLEMENT_ITCOMOBJECT_SETSTATE_LOCKOP(CRobotSimulation)
IMPLEMENT_ITCADI(CRobotSimulation)
IMPLEMENT_ITCWATCHSOURCE(CRobotSimulation)

///////////////////////////////////////////////////////////////////////////////
// Set parameters of CRobotSimulation 
BEGIN_SETOBJPARA_MAP(CRobotSimulation)
	SETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="SetObjectParameterMap">
	SETOBJPARA_VALUE(PID_TcTraceLevel, m_TraceLevelMax)
	SETOBJPARA_VALUE(PID_RobotSimulationTs, m_Ts)
	SETOBJPARA_VALUE(PID_RobotSimulationMujocoModel, m_MujocoModel)
	SETOBJPARA_VALUE(PID_RobotSimulationCustomMujocoModelPath, m_CustomMujocoModelPath)
	SETOBJPARA_ITFPTR(PID_Ctx_TaskOid, m_spCyclicCaller)
	SETOBJPARA_ITFPTR(PID_RobotSimulationControllerFastPostCyclic, m_spControllerFastPostCyclic)
	SETOBJPARA_ITFPTR(PID_RobotSimulationPostCyclicCaller, m_spPostCyclicCaller)
	SETOBJPARA_ITFPTR(PID_RobotSimulationTask, m_spTask)
	SETOBJPARA_ITFPTR(PID_RobotSimulationControllerFastCyclic, m_spControllerFastCyclic)
	SETOBJPARA_DATAPTR(PID_RobotSimulationtorque, m_sptorque)
	SETOBJPARA_DATAPTR(PID_RobotSimulationtorque_sensor, m_sptorque_sensor)
	SETOBJPARA_DATAPTR(PID_RobotSimulationtorque_motor, m_sptorque_motor)
	SETOBJPARA_DATAPTR(PID_RobotSimulationjoint_state, m_spjoint_state)
///</AutoGeneratedContent>
END_SETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get parameters of CRobotSimulation 
BEGIN_GETOBJPARA_MAP(CRobotSimulation)
	GETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="GetObjectParameterMap">
	GETOBJPARA_VALUE(PID_TcTraceLevel, m_TraceLevelMax)
	GETOBJPARA_VALUE(PID_RobotSimulationTs, m_Ts)
	GETOBJPARA_VALUE(PID_RobotSimulationMujocoModel, m_MujocoModel)
	GETOBJPARA_VALUE(PID_RobotSimulationCustomMujocoModelPath, m_CustomMujocoModelPath)
	GETOBJPARA_ITFPTR(PID_Ctx_TaskOid, m_spCyclicCaller)
	GETOBJPARA_ITFPTR(PID_RobotSimulationControllerFastPostCyclic, m_spControllerFastPostCyclic)
	GETOBJPARA_ITFPTR(PID_RobotSimulationPostCyclicCaller, m_spPostCyclicCaller)
	GETOBJPARA_ITFPTR(PID_RobotSimulationTask, m_spTask)
	GETOBJPARA_ITFPTR(PID_RobotSimulationControllerFastCyclic, m_spControllerFastCyclic)
///</AutoGeneratedContent>
END_GETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get watch entries of CRobotSimulation
BEGIN_OBJPARAWATCH_MAP(CRobotSimulation)
	OBJPARAWATCH_DATAAREA_MAP()
///<AutoGeneratedContent id="ObjectParameterWatchMap">
///</AutoGeneratedContent>
END_OBJPARAWATCH_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get data area members of CRobotSimulation
BEGIN_OBJDATAAREA_MAP(CRobotSimulation)
///<AutoGeneratedContent id="ObjectDataAreaMap">
	OBJDATAAREA_VALUE(ADI_RobotSimulationData, m_Data)
///</AutoGeneratedContent>
END_OBJDATAAREA_MAP()

///////////////////////////////////////////////////////////////////////////////
CRobotSimulation::CRobotSimulation()
	: m_Trace(m_TraceLevelMax, m_spSrv)
	, m_Counter(0)
{
///<AutoGeneratedContent id="MemberInitialization">
	m_TraceLevelMax = tlAlways;
	m_Ts = 0;
	m_MujocoModel = iiwa_hanging;
	memset(&m_CustomMujocoModelPath, 0, sizeof(m_CustomMujocoModelPath));
	memset(&m_Data, 0, sizeof(m_Data));
///</AutoGeneratedContent>
}

///////////////////////////////////////////////////////////////////////////////
CRobotSimulation::~CRobotSimulation() 
{
}

///////////////////////////////////////////////////////////////////////////////
// State Transitions 
///////////////////////////////////////////////////////////////////////////////
IMPLEMENT_ITCOMOBJECT_SETOBJSTATE_IP_PI(CRobotSimulation)

///////////////////////////////////////////////////////////////////////////////
// State transition from PREOP to SAFEOP
//
// Initialize input parameters 
// Allocate memory
HRESULT CRobotSimulation::SetObjStatePS(PTComInitDataHdr pInitData)
{
	m_Trace.Log(tlVerbose, FENTERA);

	HRESULT hr = S_OK;
	IMPLEMENT_ITCOMOBJECT_EVALUATE_INITDATA(pInitData);

	// TODO: Add initialization code

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to OP
//
// Register with other TwinCAT objects
HRESULT CRobotSimulation::SetObjStateSO()
{
	m_Trace.Log(tlVerbose, FENTERA);

	HRESULT hr = S_OK;

	// TODO: Add any additional initialization

	// Initialize data pointer
	hr = FAILED(hr) ? hr : InitDataPointer();

	// If following call is successful the CycleUpdate method will be called, 
	// possibly even before this method has been left.
	hr = FAILED(hr) ? hr : AddModuleToCaller();

	// Cleanup if transition failed at some stage
	if ( FAILED(hr) )
	{
		RemoveModuleFromCaller();
		DeinitDataPointer();
	}

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from OP to SAFEOP
HRESULT CRobotSimulation::SetObjStateOS()
{
	m_Trace.Log(tlVerbose, FENTERA);
	HRESULT hr = S_OK;

	RemoveModuleFromCaller();
	DeinitDataPointer();

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to PREOP
// Free memory
HRESULT CRobotSimulation::SetObjStateSP()
{
	m_Trace.Log(tlVerbose, FENTERA);
	HRESULT hr = S_OK;

	// TODO: Add deinitialization code

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// Prepare to leave OP state
// Release data pointer
BOOL CRobotSimulation::TcTryToReleaseOpState()
{
	m_Trace.Log(tlVerbose, FENTERA);

	DeinitDataPointer();

	m_Trace.Log(tlVerbose, FLEAVEA);
	return TRUE;
}

///<AutoGeneratedContent id="ImplementationOf_ITcCyclic">
HRESULT CRobotSimulation::CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context)
{
	HRESULT hr = S_OK;

	// cyclic code here

	return hr;
}
///</AutoGeneratedContent>

///////////////////////////////////////////////////////////////////////////////
HRESULT CRobotSimulation::AddModuleToCaller()
{
	m_Trace.Log(tlVerbose, FENTERA);
	HRESULT hr = S_OK;

	if ( m_spCyclicCaller.HasOID() )
	{
		if ( SUCCEEDED_DBG(hr = m_spSrv->TcQuerySmartObjectInterface(m_spCyclicCaller)) )
		{
			if ( FAILED(hr = m_spCyclicCaller->AddModule(m_spCyclicCaller, THIS_CAST(ITcCyclic))) )
			{
				m_spCyclicCaller = NULL;
			}
		}
	}
	else
	{
		hr = ADS_E_INVALIDOBJID; 
		SUCCEEDED_DBGT(hr, "Invalid OID specified for caller task");
	}

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
VOID CRobotSimulation::RemoveModuleFromCaller()
{
	m_Trace.Log(tlVerbose, FENTERA);
	if ( m_spCyclicCaller )
	{
		m_spCyclicCaller->RemoveModule(m_spCyclicCaller);
	}
	m_spCyclicCaller	= NULL;
	m_Trace.Log(tlVerbose, FLEAVEA);
}


///////////////////////////////////////////////////////////////////////////////
HRESULT CRobotSimulation::InitDataPointer()
{
	m_Trace.Log(tlVerbose, FENTERA);

	HRESULT hr = S_OK;
	hr = FAILED(hr) ? hr : m_sptorque.Init(m_spSrv);
	hr = FAILED(hr) ? hr : m_sptorque_motor.Init(m_spSrv);
	hr = FAILED(hr) ? hr : m_sptorque_sensor.Init(m_spSrv);
	hr = FAILED(hr) ? hr : m_spjoint_state.Init(m_spSrv);

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
VOID CRobotSimulation::DeinitDataPointer()
{
	m_Trace.Log(tlVerbose, FENTERA);

	m_sptorque = NULL;
	m_sptorque_motor = NULL;
	m_sptorque_sensor = NULL;
	m_spjoint_state = NULL;

	m_Trace.Log(tlVerbose, FLEAVEA);
}

///<AutoGeneratedContent id="ImplementationOf_ITcPostCyclic">
HRESULT CRobotSimulation::PostCyclicUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context)
{
	HRESULT hr = E_NOTIMPL;
	return hr;
}
///</AutoGeneratedContent>
