///////////////////////////////////////////////////////////////////////////////
// RobotSimulation.cpp
#include "TcPch.h"
#pragma hdrstop

#include "RobotSimulation.h"
#include "TcIoServices.h"
#include "RoboSimFastVersion.h"

#include "orc/robots/Iiwa.h"
#include "orc/com/TcServerUtil.h"
#include "orc/util/Logger.h"
//#include "orc/util/import_mujoco.h"

#include <mujoco_tc/mujoco_tc.h>
#include <mujoco_tc/engine_util_misc_tc.h>
#include <mujoco_tc/engine_io_tc.h>
#include <mujoco_tc/engine_util_blas_tc.h>
#include <Eigen/Core>


#ifdef _DEBUG
#define new DEBUG_NEW
#endif
DEFINE_THIS_FILE()

///////////////////////////////////////////////////////////////////////////////
// CRobotSimulation
///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////
// Collection of interfaces implemented by module CRobotSimulation
BEGIN_INTERFACE_MAP(CRobotSimulation)
	INTERFACE_ENTRY_ITCOMOBJECT()
	INTERFACE_ENTRY(IID_ITcADI, ITcADI)
	INTERFACE_ENTRY(IID_ITcWatchSource, ITcWatchSource)
///<AutoGeneratedContent id="InterfaceMap">
	INTERFACE_ENTRY(IID_ITcCyclic, ITcCyclic)
	INTERFACE_ENTRY(IID_ITcPostCyclic, ITcPostCyclic)
///</AutoGeneratedContent>
END_INTERFACE_MAP()

IMPLEMENT_IPERSIST_LIB(CRobotSimulation, VID_RoboSimFast, CID_RoboSimFastCRobotSimulation)
IMPLEMENT_ITCOMOBJECT(CRobotSimulation)
IMPLEMENT_ITCOMOBJECT_SETSTATE_LOCKOP(CRobotSimulation)
IMPLEMENT_ITCADI(CRobotSimulation)
IMPLEMENT_ITCWATCHSOURCE(CRobotSimulation)

///////////////////////////////////////////////////////////////////////////////
// Set parameters of CRobotSimulation 
BEGIN_SETOBJPARA_MAP(CRobotSimulation)
	SETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="SetObjectParameterMap">
	SETOBJPARA_VALUE(PID_TcTraceLevel, m_TraceLevelMax)
	SETOBJPARA_VALUE(PID_RobotSimulationTs, m_Ts)
	SETOBJPARA_VALUE(PID_RobotSimulationMujocoModel, m_MujocoModel)
	SETOBJPARA_VALUE(PID_RobotSimulationCustomMujocoModelPath, m_CustomMujocoModelPath)
	SETOBJPARA_ITFPTR(PID_Ctx_TaskOid, m_spCyclicCaller)
	SETOBJPARA_ITFPTR(PID_RobotSimulationControllerFastPostCyclic, m_spControllerFastPostCyclic)
	SETOBJPARA_ITFPTR(PID_RobotSimulationPostCyclicCaller, m_spPostCyclicCaller)
	SETOBJPARA_ITFPTR(PID_RobotSimulationTask, m_spTask)
	SETOBJPARA_ITFPTR(PID_RobotSimulationControllerFastCyclic, m_spControllerFastCyclic)
	SETOBJPARA_DATAPTR(PID_RobotSimulationtorque, m_sptorque)
	SETOBJPARA_DATAPTR(PID_RobotSimulationtorque_sensor, m_sptorque_sensor)
	SETOBJPARA_DATAPTR(PID_RobotSimulationtorque_motor, m_sptorque_motor)
	SETOBJPARA_DATAPTR(PID_RobotSimulationjoint_state, m_spjoint_state)
///</AutoGeneratedContent>
END_SETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get parameters of CRobotSimulation 
BEGIN_GETOBJPARA_MAP(CRobotSimulation)
	GETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="GetObjectParameterMap">
	GETOBJPARA_VALUE(PID_TcTraceLevel, m_TraceLevelMax)
	GETOBJPARA_VALUE(PID_RobotSimulationTs, m_Ts)
	GETOBJPARA_VALUE(PID_RobotSimulationMujocoModel, m_MujocoModel)
	GETOBJPARA_VALUE(PID_RobotSimulationCustomMujocoModelPath, m_CustomMujocoModelPath)
	GETOBJPARA_ITFPTR(PID_Ctx_TaskOid, m_spCyclicCaller)
	GETOBJPARA_ITFPTR(PID_RobotSimulationControllerFastPostCyclic, m_spControllerFastPostCyclic)
	GETOBJPARA_ITFPTR(PID_RobotSimulationPostCyclicCaller, m_spPostCyclicCaller)
	GETOBJPARA_ITFPTR(PID_RobotSimulationTask, m_spTask)
	GETOBJPARA_ITFPTR(PID_RobotSimulationControllerFastCyclic, m_spControllerFastCyclic)
///</AutoGeneratedContent>
END_GETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get watch entries of CRobotSimulation
BEGIN_OBJPARAWATCH_MAP(CRobotSimulation)
	OBJPARAWATCH_DATAAREA_MAP()
///<AutoGeneratedContent id="ObjectParameterWatchMap">
///</AutoGeneratedContent>
END_OBJPARAWATCH_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get data area members of CRobotSimulation
BEGIN_OBJDATAAREA_MAP(CRobotSimulation)
///<AutoGeneratedContent id="ObjectDataAreaMap">
	OBJDATAAREA_VALUE(ADI_RobotSimulationData, m_Data)
///</AutoGeneratedContent>
END_OBJDATAAREA_MAP()

///////////////////////////////////////////////////////////////////////////////
CRobotSimulation::CRobotSimulation()
	: m_Trace(m_TraceLevelMax, m_spSrv)
	, m_Counter(0)
	, t(0.0)
	, Ts(0.0)
	, orc_log(orc::log::Level::Debug, &m_Trace)
{
///<AutoGeneratedContent id="MemberInitialization">
	m_TraceLevelMax = tlAlways;
	m_Ts = 0;
	m_MujocoModel = iiwa_hanging;
	memset(&m_CustomMujocoModelPath, 0, sizeof(m_CustomMujocoModelPath));
	memset(&m_Data, 0, sizeof(m_Data));
///</AutoGeneratedContent>
}

///////////////////////////////////////////////////////////////////////////////
CRobotSimulation::~CRobotSimulation() 
{
}

///////////////////////////////////////////////////////////////////////////////
// State Transitions 
///////////////////////////////////////////////////////////////////////////////
IMPLEMENT_ITCOMOBJECT_SETOBJSTATE_IP_PI(CRobotSimulation)

///////////////////////////////////////////////////////////////////////////////
// State transition from PREOP to SAFEOP
//
// Initialize input parameters 
// Allocate memory
HRESULT CRobotSimulation::SetObjStatePS(PTComInitDataHdr pInitData)
{
	m_Trace.Log(tlVerbose, FENTERA);

	HRESULT hr = S_OK;
	IMPLEMENT_ITCOMOBJECT_EVALUATE_INITDATA(pInitData);

	// ------------------- READ IN MUJOCO FILE -------------	
	// Create file access instance
	hr = m_spSrv->TcCreateInstance(CID_TcFileAccess, IID_ITcFileAccess, (PPVOID)(&m_spFileAccess));

	// Choose mjb file as per TwinCAT parameters
	std::string model_path = "C:\\TwinCAT\\3.1\\Boot\\";
	if (m_MujocoModel == RobotSimulationMujocoModel::iiwa_hanging)
		model_path.append("iiwa_hanging.mjb");
	else if (m_MujocoModel == RobotSimulationMujocoModel::iiwa_hanging_with_mass_gripped)
		model_path.append("iiwa_hanging_with_mass_gripped.mjb");
	else if (m_MujocoModel == RobotSimulationMujocoModel::custom)
		model_path.append(m_CustomMujocoModelPath);
	else
		return E_FAIL;
	//strcpy(m_pOutputs->model_path, model_path.c_str());

	if (SUCCEEDED(hr)) {
		ITComObjectPtr spFileAccessObj = m_spFileAccess;
		hr = spFileAccessObj->TcSetObjState(TCOM_STATE_PREOP, m_spSrv, pInitData);
		if (SUCCEEDED(hr)) {
			// read Mujoco binary file (iiwa.mjb) from _Boot directory
			m_Trace.Log(tlVerbose, FENTERA "Reading MJB file!");
			// %BOOTPRJPATH% und %TC_TARGETPATH% funktionieren hier nicht, wieso?
			hr = readBinaryModel(model_path.c_str());
		}
	}

	mj_model = mj_loadModelBuffer((void*)model_binary, (unsigned int)model_size, m_Trace);
	mj_data = mj_makeData(mj_model);

	// Runtime override of joint damping. Many iiwa MJCFs ship with damping=0,
	// which leaves the plant with no physical dissipation and forces the
	// closed-loop controller to provide all damping explicitly -- which fails
	// once the cycle-time / DOF-inertia ratio crosses the explicit-feedback
	// stability limit. With nonzero dof_damping the implicit fold in
	// mj_forwardSkip ((M + dt*diag(b)) qacc = qfrc_smooth) makes the closed
	// loop unconditionally stable for that damping term.
	//
	// Start with 0.5 N*m*s/rad uniformly; tune per-joint if needed. Set to 0
	// to restore the original MJCF behavior.
	// const double joint_damping_override = 0.5;
	// if (joint_damping_override > 0) {
	// 	for (int i = 0; i < mj_model->nv; ++i) {
	// 		mj_model->dof_damping[i] = joint_damping_override;
	// 	}
	// }
	// ------------------- MUJOCO END ----------------------

	orc::log::start_logging_twincat(m_TraceLevelMax, &m_Trace);
	m_Trace.Log(tlAlways, FLEAVEA "ORC initialized!", hr);

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to OP
//
// Register with other TwinCAT objects
HRESULT CRobotSimulation::SetObjStateSO()
{
	m_Trace.Log(tlVerbose, FENTERA);

	HRESULT hr = S_OK;

	t = 0.0;
	q = JointVector::Zero();
	qd = JointVector::Zero();

	// read cycle time from TcCom Module Parameter
	Ts = m_Ts;
	m_Trace.Log(tlAlways, FLEAVEA "Cycle Time Ts = %f s", Ts.toSec());

	m_Trace.Log(tlInfo, FLEAVEA "nq = %d", mj_model->nq);
	m_Trace.Log(tlInfo, FLEAVEA "nv = %d", mj_model->nv);
	m_Trace.Log(tlInfo, FLEAVEA "nu = %d", mj_model->nu);

	// sync the simulator's "expected dt" with our actual integration step.
	// mj_forwardSkip uses this to apply implicit damping (M + dt*diag(b)).
	mj_model->opt.timestep = Ts.toSec();
	m_Trace.Log(tlAlways, FLEAVEA "mj_model->opt.timestep set to %g s", mj_model->opt.timestep);

	// log model damping/armature so we can see what physical dissipation the
	// simulator actually has. Zero damping ==> Euler-class integrators ring
	// up energy and diverge under any perturbation.
	m_Trace.Log(tlAlways, FLEAVEA "dof_damping=[%g %g %g %g %g %g %g]",
		mj_model->dof_damping[0], mj_model->dof_damping[1], mj_model->dof_damping[2],
		mj_model->dof_damping[3], mj_model->dof_damping[4], mj_model->dof_damping[5],
		mj_model->dof_damping[6]);
	m_Trace.Log(tlAlways, FLEAVEA "dof_armature=[%g %g %g %g %g %g %g]",
		mj_model->dof_armature[0], mj_model->dof_armature[1], mj_model->dof_armature[2],
		mj_model->dof_armature[3], mj_model->dof_armature[4], mj_model->dof_armature[5],
		mj_model->dof_armature[6]);

	// Initialize data pointer
	hr = FAILED(hr) ? hr : InitDataPointer();

	// If following call is successful the CycleUpdate method will be called, 
	// possibly even before this method has been left.
	hr = FAILED(hr) ? hr : AddModuleToCaller();

	// Cleanup if transition failed at some stage
	if ( FAILED(hr) )
	{
		RemoveModuleFromCaller();
		DeinitDataPointer();
	}

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from OP to SAFEOP
HRESULT CRobotSimulation::SetObjStateOS()
{
	m_Trace.Log(tlVerbose, FENTERA);
	HRESULT hr = S_OK;

	RemoveModuleFromCaller();
	DeinitDataPointer();

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to PREOP
// Free memory
HRESULT CRobotSimulation::SetObjStateSP()
{
	m_Trace.Log(tlVerbose, FENTERA);
	HRESULT hr = S_OK;

	mj_deleteData(mj_data);
	mj_deleteModel(mj_model);

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// Prepare to leave OP state
// Release data pointer
BOOL CRobotSimulation::TcTryToReleaseOpState()
{
	m_Trace.Log(tlVerbose, FENTERA);

	DeinitDataPointer();

	m_Trace.Log(tlVerbose, FLEAVEA);
	return TRUE;
}

///<AutoGeneratedContent id="ImplementationOf_ITcCyclic">
HRESULT CRobotSimulation::CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context)
{
	HRESULT hr = S_OK;

	// torque input
	JointVector tau(m_sptorque->Values);
	// JointVector tau = JointVector::Zero();

	// Saturate tau to iiwa14 rated joint-torque limits (KUKA datasheet).
	// For iiwa7 R800 use {176,176,110,110,110,40,40} instead. 
	static const double tau_limit[7] = { 320.0, 320.0, 176.0, 176.0, 110.0, 40.0, 40.0 };
	for (int i = 0; i < 7; ++i) {
		if (tau(i) >  tau_limit[i]) { tau(i) =  tau_limit[i]; }
		if (tau(i) < -tau_limit[i]) { tau(i) = -tau_limit[i]; }
	}

	// RNEA - forward dynamics computation.
	// mju_copy(mj_data->qfrc_applied, tau.data(), mj_model->nv);  // applied generalized forces
	mju_copy(mj_data->ctrl, tau.data(), mj_model->nv);  // applied generalized forces


	m_Trace.Log(tlVerbose, FLEAVEA "nv=%d qfrc_applied=[%g %g %g %g %g %g %g]",
		mj_model->nv,
		mj_data->qfrc_applied[0], mj_data->qfrc_applied[1], mj_data->qfrc_applied[2],
		mj_data->qfrc_applied[3], mj_data->qfrc_applied[4], mj_data->qfrc_applied[5],
		mj_data->qfrc_applied[6]);

	mj_forward(mj_model, mj_data);
	
	// Result: accelerations in d->qacc  (length m->nv)
	JointVector qdd = Eigen::Map<JointVector>(mj_data->qacc);

	m_Trace.Log(tlVerbose, FLEAVEA "tau=[%g %g %g %g %g %g %g]",
		tau(0), tau(1), tau(2), tau(3), tau(4), tau(5), tau(6));

	m_Trace.Log(tlVerbose, FLEAVEA "qdd=[%g %g %g %g %g %g %g]",
		qdd(0), qdd(1), qdd(2), qdd(3), qdd(4), qdd(5), qdd(6));

	m_Trace.Log(tlVerbose, FLEAVEA "qd=[%g %g %g %g %g %g %g]",
		qd(0), qd(1), qd(2), qd(3), qd(4), qd(5), qd(6));
	
	m_Trace.Log(tlVerbose, FLEAVEA "q=[%g %g %g %g %g %g %g]",
		q(0), q(1), q(2), q(3), q(4), q(5), q(6));

	// semi-implicit (symplectic) Euler: update velocity first, then use the
	// new velocity to update position. Equivalent to MuJoCo's mj_Euler and is
	// stable for much larger Ts than explicit Euler on stiff mechanical systems.
	qd += Ts.toSec() * qdd;
	q  += Ts.toSec() * qd;
	/*double sample_time = 125e-6;
	qd += sample_time * qdd;
	q += sample_time  * qd;*/
	

	// update mj data
	mju_copy(mj_data->qvel, qd.data(), mj_model->nv); 
	mju_copy(mj_data->qpos, q.data(), mj_model->nq);  

	// return joint state
	JointVector::Map(m_spjoint_state->Values) = q;
	// JointVector::Map(m_sptorque_motor->Values) = tau;
	// JointVector::Map(m_sptorque_sensor->Values) = tau;

	return hr;
}
///</AutoGeneratedContent>

///////////////////////////////////////////////////////////////////////////////
HRESULT CRobotSimulation::AddModuleToCaller()
{
	m_Trace.Log(tlVerbose, FENTERA);
	HRESULT hr = S_OK;

	if ( m_spCyclicCaller.HasOID() )
	{
		if ( SUCCEEDED_DBG(hr = m_spSrv->TcQuerySmartObjectInterface(m_spCyclicCaller)) )
		{
			if ( FAILED(hr = m_spCyclicCaller->AddModule(m_spCyclicCaller, THIS_CAST(ITcCyclic))) )
			{
				m_spCyclicCaller = NULL;
			}
		}
	}
	else
	{
		hr = ADS_E_INVALIDOBJID; 
		SUCCEEDED_DBGT(hr, "Invalid OID specified for caller task");
	}

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
VOID CRobotSimulation::RemoveModuleFromCaller()
{
	m_Trace.Log(tlVerbose, FENTERA);
	if ( m_spCyclicCaller )
	{
		m_spCyclicCaller->RemoveModule(m_spCyclicCaller);
	}
	m_spCyclicCaller	= NULL;
	m_Trace.Log(tlVerbose, FLEAVEA);
}


///////////////////////////////////////////////////////////////////////////////
HRESULT CRobotSimulation::InitDataPointer()
{
	m_Trace.Log(tlVerbose, FENTERA);

	HRESULT hr = S_OK;
	hr = FAILED(hr) ? hr : m_sptorque.Init(m_spSrv);
	hr = FAILED(hr) ? hr : m_sptorque_motor.Init(m_spSrv);
	hr = FAILED(hr) ? hr : m_sptorque_sensor.Init(m_spSrv);
	hr = FAILED(hr) ? hr : m_spjoint_state.Init(m_spSrv);

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
VOID CRobotSimulation::DeinitDataPointer()
{
	m_Trace.Log(tlVerbose, FENTERA);

	m_sptorque = NULL;
	m_sptorque_motor = NULL;
	m_sptorque_sensor = NULL;
	m_spjoint_state = NULL;

	m_Trace.Log(tlVerbose, FLEAVEA);
}

///<AutoGeneratedContent id="ImplementationOf_ITcPostCyclic">
HRESULT CRobotSimulation::PostCyclicUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context)
{
	HRESULT hr = E_NOTIMPL;
	return hr;
}
///</AutoGeneratedContent>

// Reads the binary file and stores its contents into CArcController::model_binary
HRESULT CRobotSimulation::readBinaryModel(PCCH fileName)
{
	HRESULT hr = S_OK;
	m_Trace.Log(tlVerbose, FENTERA);

	// get file size to allocate space for model_binary variable in which model will be saved
	TcFileStatus FileStatus = { 0 };
	hr = m_spFileAccess->FileGetStatus(fileName, &FileStatus);
	ULONGLONG cbData = 0;
	if (SUCCEEDED(hr)) {
		m_Trace.Log(tlVerbose, FENTERA "Model size: %i", FileStatus.ulFileSize);
		if (FileStatus.ulFileSize >= UINT_MAX) {
			m_Trace.Log(tlVerbose, FENTERA "MJB file size too large!");
			return E_ABORT;
		}
		model_size = static_cast<UINT>(FileStatus.ulFileSize);
		// model_binary is allocated on the heap as its size is a priori not known, and deleted in SetObjStateOS()
		model_binary = new UCHAR[model_size];
	}
	else {
		m_Trace.Log(tlAlways, FLEAVEA "Error while reading file!");
		return hr;
	}

	// open file
	TcFileHandle hFile = NULL;
	hr = m_spFileAccess->FileOpen(fileName, static_cast<TcFileAccessMode>(amBinary | amRead), &hFile);

	if (SUCCEEDED(hr)) {
		// read file
		UINT pcbRead = 0;
		hr = m_spFileAccess->FileRead(hFile, model_binary, model_size, &pcbRead);
	}

	// close file
	hr = m_spFileAccess->FileClose(hFile);
	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}
