///////////////////////////////////////////////////////////////////////////////
// RobotSim.cpp
#include "TcPch.h"
#pragma hdrstop

#include "RobotSim.h"
#include "RobotSimVersion.h"

#include "orc/robots/Iiwa.h"
#include "orc/com/TcServerUtil.h"
#include "orc/util/Logger.h"
//#include "orc/util/import_mujoco.h"

#include <mujoco_tc/mujoco_tc.h>
#include <mujoco_tc/engine_util_misc_tc.h>
#include <mujoco_tc/engine_io_tc.h>
#include <mujoco_tc/engine_util_blas_tc.h>
#include <Eigen/Core>

#ifdef _DEBUG
#define new DEBUG_NEW
#endif
DEFINE_THIS_FILE()

///////////////////////////////////////////////////////////////////////////////
// CRobotSim
///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////
// Collection of interfaces implemented by module CRobotSim
BEGIN_INTERFACE_MAP(CRobotSim)
	INTERFACE_ENTRY_ITCOMOBJECT()
	INTERFACE_ENTRY(IID_ITcADI, ITcADI)
	INTERFACE_ENTRY(IID_ITcWatchSource, ITcWatchSource)
///<AutoGeneratedContent id="InterfaceMap">
	INTERFACE_ENTRY(IID_ITcCyclic, ITcCyclic)
///</AutoGeneratedContent>
END_INTERFACE_MAP()

IMPLEMENT_IPERSIST_LIB(CRobotSim, VID_RobotSim, CID_RobotSimCRobotSim)
IMPLEMENT_ITCOMOBJECT(CRobotSim)
IMPLEMENT_ITCOMOBJECT_SETSTATE_LOCKOP2(CRobotSim)
IMPLEMENT_ITCADI(CRobotSim)
IMPLEMENT_ITCWATCHSOURCE(CRobotSim)


///////////////////////////////////////////////////////////////////////////////
// Set parameters of CRobotSim 
BEGIN_SETOBJPARA_MAP(CRobotSim)
	SETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="SetObjectParameterMap">
	SETOBJPARA_VALUE(PID_TcTraceLevel, m_TraceLevelMax)
	SETOBJPARA_VALUE(PID_RobotSimTs, m_Ts)
	SETOBJPARA_VALUE(PID_RobotSimMujocoModel, m_MujocoModel)
	SETOBJPARA_VALUE(PID_RobotSimCustomMujocoModelPath, m_CustomMujocoModelPath)
	SETOBJPARA_ITFPTR(PID_Ctx_TaskOid, m_spCyclicCaller)
///</AutoGeneratedContent>
END_SETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get parameters of CRobotSim 
BEGIN_GETOBJPARA_MAP(CRobotSim)
	GETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="GetObjectParameterMap">
	GETOBJPARA_VALUE(PID_TcTraceLevel, m_TraceLevelMax)
	GETOBJPARA_VALUE(PID_RobotSimTs, m_Ts)
	GETOBJPARA_VALUE(PID_RobotSimMujocoModel, m_MujocoModel)
	GETOBJPARA_VALUE(PID_RobotSimCustomMujocoModelPath, m_CustomMujocoModelPath)
	GETOBJPARA_ITFPTR(PID_Ctx_TaskOid, m_spCyclicCaller)
///</AutoGeneratedContent>
END_GETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get watch entries of CRobotSim
BEGIN_OBJPARAWATCH_MAP(CRobotSim)
	OBJPARAWATCH_DATAAREA_MAP()
///<AutoGeneratedContent id="ObjectParameterWatchMap">
///</AutoGeneratedContent>
END_OBJPARAWATCH_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get data area members of CRobotSim
BEGIN_OBJDATAAREA_MAP(CRobotSim)
///<AutoGeneratedContent id="ObjectDataAreaMap">
	OBJDATAAREA_VALUE(ADI_RobotSimInputs, m_Inputs)
	OBJDATAAREA_VALUE(ADI_RobotSimOutputs, m_Outputs)
///</AutoGeneratedContent>
END_OBJDATAAREA_MAP()


///////////////////////////////////////////////////////////////////////////////
CRobotSim::CRobotSim()
	: m_Trace(m_TraceLevelMax, m_spSrv)
	, m_counter(0)
	, t(0.0)
	, Ts(0.0)
	, orc_log(orc::log::Level::Debug, &m_Trace)
{
///<AutoGeneratedContent id="MemberInitialization">
	m_TraceLevelMax = tlAlways;
	m_Ts = 0;
	m_MujocoModel = iiwa_hanging;
	q = JointVector::Zero();
	qd = JointVector::Zero();
	memset(&m_CustomMujocoModelPath, 0, sizeof(m_CustomMujocoModelPath));
	memset(&m_Inputs, 0, sizeof(m_Inputs));
	memset(&m_Outputs, 0, sizeof(m_Outputs));
///</AutoGeneratedContent>
}

///////////////////////////////////////////////////////////////////////////////
CRobotSim::~CRobotSim() 
{
}


///////////////////////////////////////////////////////////////////////////////
// State Transitions 
///////////////////////////////////////////////////////////////////////////////
IMPLEMENT_ITCOMOBJECT_SETOBJSTATE_IP_PI(CRobotSim)

///////////////////////////////////////////////////////////////////////////////
// State transition from PREOP to SAFEOP
//
// Initialize input parameters 
// Allocate memory
HRESULT CRobotSim::SetObjStatePS(PTComInitDataHdr pInitData)
{
	m_Trace.Log(tlVerbose, FENTERA);
	HRESULT hr = S_OK;
	IMPLEMENT_ITCOMOBJECT_EVALUATE_INITDATA(pInitData);

	// TODO: Add initialization code

	// ------------------- READ IN MUJOCO FILE -------------	
	// Create file access instance
	hr = m_spSrv->TcCreateInstance(CID_TcFileAccess, IID_ITcFileAccess, (PPVOID)(&m_spFileAccess));

	// Choose mjb file as per TwinCAT parameters
	std::string model_path = "C:\\TwinCAT\\3.1\\Boot\\";
	if (m_MujocoModel == RobotSimMujocoModel::iiwa_hanging)
		model_path.append("iiwa_hanging.mjb");
	else if (m_MujocoModel == RobotSimMujocoModel::iiwa_hanging_with_mass_gripped)
		model_path.append("iiwa_hanging_with_mass_gripped.mjb");
	else if (m_MujocoModel == RobotSimMujocoModel::custom)
		model_path.append(m_CustomMujocoModelPath);
	else
		return E_FAIL;
	strcpy(m_Outputs.model_path, model_path.c_str());

	if (SUCCEEDED(hr)) {
		ITComObjectPtr spFileAccessObj = m_spFileAccess;
		hr = spFileAccessObj->TcSetObjState(TCOM_STATE_PREOP, m_spSrv, pInitData);
		if (SUCCEEDED(hr)) {
			// read Mujoco binary file (iiwa.mjb) from _Boot directory
			m_Trace.Log(tlVerbose, FENTERA "Reading MJB file!");
			// %BOOTPRJPATH% und %TC_TARGETPATH% funktionieren hier nicht, wieso?
			hr = readBinaryModel(model_path.c_str());
		}
	}

	mj_model = mj_loadModelBuffer((void*)model_binary, (unsigned int)model_size, m_Trace);
	mj_data = mj_makeData(mj_model);
	// ------------------- MUJOCO END ----------------------

	orc::log::start_logging_twincat(m_TraceLevelMax, &m_Trace);
	m_Trace.Log(tlAlways, FLEAVEA "ORC initialized!", hr);
	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);

	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to OP
//
// Register with other TwinCAT objects
HRESULT CRobotSim::SetObjStateSO()
{
	m_Trace.Log(tlVerbose, FENTERA);
	HRESULT hr = S_OK;

	// TODO: Add any additional initialization
	t = 0.0;
	q = JointVector::Zero();
	qd = JointVector::Zero();

	// read cycle time from TcCom Module Parameter
	Ts = m_Ts;
	m_Trace.Log(tlAlways, FLEAVEA "Cycle Time Ts = %f", Ts);

	// If following call is successful the CycleUpdate method will be called, 
	// possibly even before method has been left.
	hr = FAILED(hr) ? hr : AddModuleToCaller(); 

	// Cleanup if transition failed at some stage
	if ( FAILED(hr) )
	{
		RemoveModuleFromCaller(); 
	}

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from OP to SAFEOP
HRESULT CRobotSim::SetObjStateOS()
{
	m_Trace.Log(tlVerbose, FENTERA);

	HRESULT hr = S_OK;

	RemoveModuleFromCaller(); 

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to PREOP
HRESULT CRobotSim::SetObjStateSP()
{
	HRESULT hr = S_OK;
	m_Trace.Log(tlVerbose, FENTERA);

	mj_deleteData(mj_data);
	mj_deleteModel(mj_model);
	//delete model_binary;
	//delete mj_data;

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///<AutoGeneratedContent id="ImplementationOf_ITcCyclic">
HRESULT CRobotSim::CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context)
{
	HRESULT hr = S_OK;
	
	// torque input
	JointVector tau(m_Inputs.torque.Values);

	// RNEA - forward dynamics computation
	mju_copy(mj_data->ctrl, tau.data(), mj_model->nu);   // if using actuators
	// OR directly:
	//mju_copy(d->qfrc_applied, my_torques, m->nv);  // applied generalized forces

	mj_forward(mj_model, mj_data);

	// Result: accelerations in d->qacc  (length m->nv)
	JointVector qdd = Eigen::Map<JointVector>(mj_data->qacc);

	// integration
	qd += Ts.toSec() * qdd;
	q += Ts.toSec() * qd;

	// update mj data
	mju_copy(mj_data->qvel, qd.data(), mj_model->nv); 
	mju_copy(mj_data->qpos, q.data(), mj_model->nq);  

	// return joint state
	JointVector::Map(m_Outputs.joint_state.Values) = q;
	JointVector::Map(m_Outputs.torque_motor.Values) = JointVector::Zero();
	JointVector::Map(m_Outputs.torque_sensor.Values) = JointVector::Zero();


	return hr;
}
///</AutoGeneratedContent>

///////////////////////////////////////////////////////////////////////////////
HRESULT CRobotSim::AddModuleToCaller()
{
	m_Trace.Log(tlVerbose, FENTERA);

	HRESULT hr = S_OK;
	if ( m_spCyclicCaller.HasOID() )
	{
		if ( SUCCEEDED_DBG(hr = m_spSrv->TcQuerySmartObjectInterface(m_spCyclicCaller)) )
		{
			if ( FAILED(hr = m_spCyclicCaller->AddModule(m_spCyclicCaller, THIS_CAST(ITcCyclic))) )
			{
				m_spCyclicCaller = NULL;
			}
		}
	}
	else
	{
		hr = ADS_E_INVALIDOBJID; 
		SUCCEEDED_DBGT(hr, "Invalid OID specified for caller task");
	}

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
VOID CRobotSim::RemoveModuleFromCaller()
{
	m_Trace.Log(tlVerbose, FENTERA);

	if ( m_spCyclicCaller )
	{
		m_spCyclicCaller->RemoveModule(m_spCyclicCaller);
	}
	m_spCyclicCaller	= NULL;

	m_Trace.Log(tlVerbose, FLEAVEA);
}

// Reads the binary file and stores its contents into CArcController::model_binary
HRESULT CRobotSim::readBinaryModel(PCCH fileName)
{
	HRESULT hr = S_OK;
	m_Trace.Log(tlVerbose, FENTERA);

	// get file size to allocate space for model_binary variable in which model will be saved
	TcFileStatus FileStatus = { 0 };
	hr = m_spFileAccess->FileGetStatus(fileName, &FileStatus);
	ULONGLONG cbData = 0;
	if (SUCCEEDED(hr)) {
		m_Trace.Log(tlVerbose, FENTERA "Model size: %i", FileStatus.ulFileSize);
		if (FileStatus.ulFileSize >= UINT_MAX) {
			m_Trace.Log(tlVerbose, FENTERA "MJB file size too large!");
			return E_ABORT;
		}
		model_size = static_cast<UINT>(FileStatus.ulFileSize);
		// model_binary is allocated on the heap as its size is a priori not known, and deleted in SetObjStateOS()
		model_binary = new UCHAR[model_size];
	}
	else {
		m_Trace.Log(tlAlways, FLEAVEA "Error while reading file!");
		return hr;
	}

	// open file
	TcFileHandle hFile = NULL;
	hr = m_spFileAccess->FileOpen(fileName, static_cast<TcFileAccessMode>(amBinary | amRead), &hFile);

	if (SUCCEEDED(hr)) {
		// read file
		UINT pcbRead = 0;
		hr = m_spFileAccess->FileRead(hFile, model_binary, model_size, &pcbRead);
	}

	// close file
	hr = m_spFileAccess->FileClose(hFile);
	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}
