///////////////////////////////////////////////////////////////////////////////
// RobotSimServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_RobotSim = 0x3F000000;
#define SRVNAME_ROBOTSIM "RobotSim"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_RobotSimCRobotSim = {0xcb1245e5,0x8c1f,0x4bcf,{0xad,0x57,0x7e,0x0e,0xf9,0x00,0x85,0x7c}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_RobotSimTs = 0x00000001;
const PTCID PID_RobotSimMujocoModel = 0x00000002;
const PTCID PID_RobotSimCustomMujocoModelPath = 0x00000003;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
#if !defined(_TC_TYPE_1247A85A_0A92_414F_B870_2E17BF811B63_INCLUDED_)
#define _TC_TYPE_1247A85A_0A92_414F_B870_2E17BF811B63_INCLUDED_
typedef struct _acin_control_Joints_t
{
	double Values[7];
} acin_control_Joints_t, *Pacin_control_Joints_t;
#endif // !defined(_TC_TYPE_1247A85A_0A92_414F_B870_2E17BF811B63_INCLUDED_)

enum RobotSimMujocoModel : SHORT {
	iiwa_hanging = 0,
	iiwa_hanging_with_mass_gripped = 1,
	custom = 2
};

#if !defined(_TC_TYPE_18071995_0000_0000_0000_00010000007F_INCLUDED_)
#define _TC_TYPE_18071995_0000_0000_0000_00010000007F_INCLUDED_
typedef CHAR STRING127[128];
#endif // !defined(_TC_TYPE_18071995_0000_0000_0000_00010000007F_INCLUDED_)

typedef struct _RobotSimInputs
{
	acin_control_Joints_t torque;
} RobotSimInputs, *PRobotSimInputs;

#if !defined(_TC_TYPE_18071995_0000_0000_0000_0001000000FF_INCLUDED_)
#define _TC_TYPE_18071995_0000_0000_0000_0001000000FF_INCLUDED_
typedef CHAR STRING255[256];
#endif // !defined(_TC_TYPE_18071995_0000_0000_0000_0001000000FF_INCLUDED_)

typedef struct _RobotSimOutputs
{
	acin_control_Joints_t joint_state;
	acin_control_Joints_t torque_sensor;
	acin_control_Joints_t torque_motor;
	STRING255 model_path;
} RobotSimOutputs, *PRobotSimOutputs;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_RobotSimInputs 0
#define ADI_RobotSimOutputs 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
