///////////////////////////////////////////////////////////////////////////////
// RobotSim.h
#pragma once

#include "RobotSimInterfaces.h"
#include <orc/OrcTypes.h>
#include <orc/util/Logger.h>
#include <orc/robots/Iiwa.h>
#include "TcFileAccessInterfaces.h"
#include <mujoco_tc/mujoco_tc.h>

//#include <mujoco_tc/mujoco_tc.h>
//#include <mujoco_tc/engine_util_misc_tc.h>
//#include <mujoco_tc/engine_io_tc.h>
//#include "orc/util/import_mujoco.h"

using namespace orc;

class CRobotSim 
	: public ITComObject
	, public ITcADI
	, public ITcWatchSource
///<AutoGeneratedContent id="InheritanceList">
	, public ITcCyclic
///</AutoGeneratedContent>
{
public:
	DECLARE_IUNKNOWN()
	DECLARE_IPERSIST_LIB()
	DECLARE_ITCOMOBJECT_LOCKOP()
	DECLARE_ITCADI()
	DECLARE_ITCWATCHSOURCE()
	DECLARE_OBJPARAWATCH_MAP()
	DECLARE_OBJDATAAREA_MAP()

	CRobotSim();
	virtual	~CRobotSim();


///<AutoGeneratedContent id="InterfaceMembers">
	// ITcCyclic
	virtual HRESULT TCOMAPI CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context);

///</AutoGeneratedContent>

protected:
	DECLARE_ITCOMOBJECT_SETSTATE();

	HRESULT AddModuleToCaller();
	VOID RemoveModuleFromCaller();

	// Tracing
	CTcTrace m_Trace;

///<AutoGeneratedContent id="Members">
	TcTraceLevel m_TraceLevelMax;
	double m_Ts;
	RobotSimMujocoModel m_MujocoModel;
	STRING127 m_CustomMujocoModelPath;
	RobotSimInputs m_Inputs;
	RobotSimOutputs m_Outputs;
	ITcCyclicCallerInfoPtr m_spCyclicCaller;
///</AutoGeneratedContent>

	ULONG TaskCycleTime = 0; // cycle time in ns 
	Time Ts;
	Time t;
	orc::log::Logger orc_log;

	using JointVector = orc::robots::Iiwa::JointVector;
	using JointArray = orc::robots::Iiwa::JointArray;

	// File access helper functions
	ITcFileAccessPtr m_spFileAccess;
	// Setting the model_binary type to unsigned char, leads to correct representation of the data
	// when compared to the hex editor of Notepad++.
	PUCHAR model_binary;
	UINT model_size;
	HRESULT readBinaryModel(PCCH fileName);

	mjModel* mj_model = nullptr; /**< Mujoco model pointer */
	mjData* mj_data = nullptr;   /**< Mujoco data pointer */

	JointVector q, qd;

	UINT m_counter;
};
