///////////////////////////////////////////////////////////////////////////////
// RobotSimClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "RobotSimClassFactory.h"
#include "RobotSimServices.h"
#include "RobotSimVersion.h"
#include "RobotSim.h"

BEGIN_CLASS_MAP(CRobotSimClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY_LIB(VID_RobotSim, CID_RobotSimCRobotSim, SRVNAME_ROBOTSIM "!CRobotSim", CRobotSim)
///</AutoGeneratedContent>
END_CLASS_MAP()

CRobotSimClassFactory::CRobotSimClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME_TMX(SRVNAME_ROBOTSIM));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(RobotSim));
#endif //defined(TCDBG_UNIT_VERSION)
}

